import type { MetricDef } from '@seesby/types';

export const SCORE_METRICS: MetricDef[] = [
  {
    key: 'p.score.contentQuality',
    namespace: 'p.score',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.score.contentQuality.label',
    description: 'Content quality score for this page.',
  },
  {
    key: 'p.score.health',
    namespace: 'p.score',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.score.health.label',
    description: 'Technical health score for this page.',
  },
  {
    key: 'p.score.eeat',
    namespace: 'p.score',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.score.eeat.label',
    description: 'E-E-A-T (experience, expertise, authoritativeness, trustworthiness) score.',
  },
  {
    key: 'p.score.valueTier',
    namespace: 'p.score',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.score.valueTier.label',
    description: 'Business value tier: high, medium, or low.',
  },
  {
    key: 'p.score.overall',
    namespace: 'p.score',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.score.overall.label',
    description: 'Composite overall page score.',
  },
];
