import type { MetricDef } from '@seesby/types';

export const PAID_METRICS: MetricDef[] = [
	{
		key: 'p.paid.isLandingPage',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'L', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.paid.isLandingPage.label',
		description: 'Whether this page is used as a paid campaign landing page.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.campaignsUsing',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.paid.campaignsUsing.label',
		description: 'Number of paid campaigns driving traffic to this page.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.paidSessions',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.paid.paidSessions.label',
		description: 'Number of sessions from paid channels.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
		defaultVisible: true,
	},
	{
		key: 'p.paid.paidBounce',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.paid.paidBounce.label',
		description: 'Bounce rate for paid traffic.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.paidCvr',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.paid.paidCvr.label',
		description: 'Conversion rate for paid traffic.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.qsLpComponent',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T6', 'T8'],
		format: 'score',
		scoreComponent: 'paid',
		i18nLabelKey: 'metric.p.paid.qsLpComponent.label',
		description: 'Google Ads Quality Score landing page experience component.',
		gate: { modes: ['paid', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.paid.adIntentMatch',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T6', 'T8'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.adIntentMatch.label',
		description: 'How well the page matches the intent of paid ad keywords.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.cwvPaidUa',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T0', 'T6', 'T7'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.cwvPaidUa.label',
		description: 'Core Web Vitals score for paid traffic user agents.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	// ── Paid quality score metrics ──
	{
		key: 'p.paid.qualityScore',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.qualityScore.label',
		description: 'Quality score for this page from paid traffic perspective.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScoreDelta',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T0'],
		format: 'number',
		i18nLabelKey: 'metric.p.paid.qualityScoreDelta.label',
		description: 'Change in quality score over time.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScoreTrend',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T0'],
		format: 'text',
		i18nLabelKey: 'metric.p.paid.qualityScoreTrend.label',
		description: 'Trend direction of quality score.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopyMatch',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T0'],
		format: 'score',
		gate: { requireConnected: ['ads'], modes: ['paid', 'fullAudit'] },
		i18nLabelKey: 'metric.p.paid.adCopyMatch',
		description: 'Ad copy to landing page message match score.',
	},
	// NOTE: s.paid.* site-level metrics moved to site/index.ts
	// ── EX-I: Paid Expansion ──
	{
		key: 'p.paid.adCopy.text',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'text',
		i18nLabelKey: 'metric.p.paid.adCopy.text.label',
		description: 'Ad copy text driving traffic to this page.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopy.headlineMatch',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.adCopy.headlineMatch.label',
		description: 'Ad headline to page title match score.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopy.descriptionMatch',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.adCopy.descriptionMatch.label',
		description: 'Ad description to page content match score.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.total',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.qualityScore.total.label',
		description: 'Total Quality Score (1-10).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.landingPage',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'I', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.qualityScore.landingPage.label',
		description: 'Landing page experience component (1-10).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.adRelevance',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.qualityScore.adRelevance.label',
		description: 'Ad relevance component (1-10).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.expCtr',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.qualityScore.expCtr.label',
		description: 'Expected CTR component (1-10).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.bucket',
		namespace: 'p.paid',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T0'],
		format: 'enum',
		i18nLabelKey: 'metric.p.paid.qualityScore.bucket.label',
		description: 'Quality Score bucket: high (7-10), average (5-6), low (1-4).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.qualityScore.trend',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		i18nLabelKey: 'metric.p.paid.qualityScore.trend.label',
		description: 'Quality Score trend time-series.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopy.types',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.paid.adCopy.types.label',
		description: 'Ad types using this page (RSA, DSA, etc.).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopy.assetCount',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'number',
		i18nLabelKey: 'metric.p.paid.adCopy.assetCount.label',
		description: 'Number of ad assets/headlines used.',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.adCopy.assetCoverage',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.adCopy.assetCoverage.label',
		description: 'Asset coverage score (how many asset slots filled).',
		gate: { modes: ['paid', 'fullAudit'] },
	},
	{
		key: 'p.paid.spend.total',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'money',
		i18nLabelKey: 'metric.p.paid.spend.total.label',
		description: 'Total ad spend driving to this page (28d).',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.spend.trend',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		i18nLabelKey: 'metric.p.paid.spend.trend.label',
		description: 'Spend trend time-series.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.conversions.total',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'number',
		i18nLabelKey: 'metric.p.paid.conversions.total.label',
		description: 'Total paid conversions (28d).',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.roas',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T0'],
		format: 'score',
		i18nLabelKey: 'metric.p.paid.roas.label',
		description: 'Return on ad spend for this landing page.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.cpc',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'money',
		i18nLabelKey: 'metric.p.paid.cpc.label',
		description: 'Average cost per click.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.paid.cpa',
		namespace: 'p.paid',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T0'],
		format: 'money',
		i18nLabelKey: 'metric.p.paid.cpa.label',
		description: 'Average cost per acquisition.',
		gate: { modes: ['paid', 'fullAudit'], requireConnected: ['ga4'] },
	},
];
