import type { MetricDef } from '@seesby/types';

export const userMetrics: MetricDef[] = [
  {
    key: 'u.thresholds.cwvGood',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.cwvGood',
    description: 'Good CWV threshold.',
  },
  {
    key: 'u.thresholds.cwvPoor',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.cwvPoor',
    description: 'Poor CWV threshold.',
  },
  {
    key: 'u.thresholds.wordCountMin',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.wordCountMin',
    description: 'Minimum word count threshold.',
  },
  {
    key: 'u.thresholds.readabilityMax',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.readabilityMax',
    description: 'Max readability grade level.',
  },
  {
    key: 'u.thresholds.imageMissingAltMax',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.imageMissingAltMax',
    description: 'Max missing alt threshold.',
  },
  {
    key: 'u.thresholds.a11yViolationMax',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.a11yViolationMax',
    description: 'Max a11y violations threshold.',
  },
  {
    key: 'u.thresholds.toxicBacklinkMax',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.toxicBacklinkMax',
    description: 'Max toxic backlink % threshold.',
  },
  {
    key: 'u.thresholds.sslDaysMin',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.thresholds.sslDaysMin',
    description: 'Min SSL days before alert.',
  },
  {
    key: 'u.weights.health',
    namespace: 'u.weights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.weights.health',
    description: 'Health score weight.',
  },
  {
    key: 'u.weights.content',
    namespace: 'u.weights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.weights.content',
    description: 'Content score weight.',
  },
  {
    key: 'u.weights.tech',
    namespace: 'u.weights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.weights.tech',
    description: 'Tech score weight.',
  },
  {
    key: 'u.weights.links',
    namespace: 'u.weights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.weights.links',
    description: 'Links score weight.',
  },
  {
    key: 'u.weights.ai',
    namespace: 'u.weights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.weights.ai',
    description: 'AI score weight.',
  },
  {
    key: 'u.scoring.dampingFactor',
    namespace: 'u.scoring',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.scoring.dampingFactor',
    description: 'PageRank damping factor.',
  },
  {
    key: 'u.scoring.maxCrawlDepth',
    namespace: 'u.scoring',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.u.scoring.maxCrawlDepth',
    description: 'Maximum crawl depth.',
  },

  // ─── EX-P: Universal Config Expansion ──────────────────────────
  {
    key: 'u.thresholds.wordCount',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.thresholds.wordCount',
    description: 'Word count thresholds: {thin: 300, short: 800, medium: 1500, long: 3000}',
  },
  {
    key: 'u.thresholds.readability',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.thresholds.readability',
    description: 'Readability thresholds per grade level',
  },
  {
    key: 'u.thresholds.cwv',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.thresholds.cwv',
    description: 'CWV thresholds: {lcp: {good: 2.5, poor: 4.0}, inp: {good: 200, poor: 500}, cls: {good: 0.1, poor: 0.25}}',
  },
  {
    key: 'u.thresholds.security',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.thresholds.security',
    description: 'Security grade thresholds and header requirements',
  },
  {
    key: 'u.thresholds.a11y',
    namespace: 'u.thresholds',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.thresholds.a11y',
    description: 'Accessibility score thresholds and violation severity mappings',
  },
  {
    key: 'u.scoringWeights.content',
    namespace: 'u.scoringWeights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.scoringWeights.content',
    description: 'Content score dimension weights',
  },
  {
    key: 'u.scoringWeights.tech',
    namespace: 'u.scoringWeights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.scoringWeights.tech',
    description: 'Tech score dimension weights',
  },
  {
    key: 'u.scoringWeights.search',
    namespace: 'u.scoringWeights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.scoringWeights.search',
    description: 'Search score dimension weights',
  },
  {
    key: 'u.scoringWeights.overall',
    namespace: 'u.scoringWeights',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.scoringWeights.overall',
    description: 'Overall Q-score dimension weights',
  },
  {
    key: 'u.actionBands.multipliers',
    namespace: 'u.actionBands',
    level: 'U',
    roles: ['G'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.u.actionBands.multipliers',
    description: 'Band score multipliers: {BLOCKING: 5.0, REVENUE_LOSS: 3.0, HIGH_LEVERAGE: 2.0, STRATEGIC: 1.5, HYGIENE: 1.0}',
  },
];
