import type { MetricDef } from '@seesby/types';

export const FP_METRICS: MetricDef[] = [
  {
    key: 'fp.industry',
    namespace: 'fp',
    level: 'F',
    roles: ['H', 'R', 'L'],
    sources: ['T0', 'T6', 'T7', 'T8'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.fp.industry',
    description: 'Detected industry type.',
  },
  {
    key: 'fp.industrySecondary',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'A'],
    sources: ['T6'],
    format: 'text',
    width: '100px',
    i18nLabelKey: 'metric.fp.industrySecondary',
    description: 'Secondary or niche industry classification.',
  },
  {
    key: 'fp.languagePrimary',
    namespace: 'fp',
    level: 'F',
    roles: ['H', 'R', 'L'],
    sources: ['T1', 'T6', 'T7'],
    format: 'enum',
    width: '80px',
    i18nLabelKey: 'metric.fp.languagePrimary',
    description: 'Primary content language.',
  },
  {
    key: 'fp.languageSet',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'L'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.languageSet',
    description: 'All detected content languages.',
  },
  {
    key: 'fp.cms',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'L', 'A'],
    sources: ['T1', 'T2', 'T6', 'T7'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.fp.cms',
    description: 'Detected CMS platform.',
  },
  {
    key: 'fp.stackHosting',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T1', 'T2'],
    format: 'text',
    width: '100px',
    i18nLabelKey: 'metric.fp.stackHosting',
    description: 'Hosting provider or platform.',
  },
  {
    key: 'fp.stackCdn',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T1'],
    format: 'text',
    width: '80px',
    i18nLabelKey: 'metric.fp.stackCdn',
    description: 'CDN provider in use.',
  },
  {
    key: 'fp.stackFramework',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'text',
    width: '100px',
    i18nLabelKey: 'metric.fp.stackFramework',
    description: 'Detected front-end framework.',
  },
  {
    key: 'fp.stackSsg',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'text',
    width: '80px',
    i18nLabelKey: 'metric.fp.stackSsg',
    description: 'Static site generator, if any.',
  },
  {
    key: 'fp.stackAnalytics',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackAnalytics',
    description: 'Analytics tools detected on the site.',
  },
  {
    key: 'fp.stackAdPlatforms',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackAdPlatforms',
    description: 'Advertising platforms detected.',
  },
  {
    key: 'fp.stackBehavior',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackBehavior',
    description: 'Behavioral tracking tools detected.',
  },
  {
    key: 'fp.stackExperiments',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackExperiments',
    description: 'A/B testing or experimentation tools detected.',
  },
  {
    key: 'fp.stackChat',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackChat',
    description: 'Live chat or chatbot tools detected.',
  },
  {
    key: 'fp.stackEmail',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackEmail',
    description: 'Email marketing tools detected.',
  },
  {
    key: 'fp.stackEcom',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackEcom',
    description: 'E-commerce platform or plugin detected.',
  },
  {
    key: 'fp.stackSchemaStack',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.stackSchemaStack',
    description: 'Schema / structured data tooling detected.',
  },
  {
    key: 'fp.sizeUrls',
    namespace: 'fp',
    level: 'F',
    roles: ['H', 'R', 'L'],
    sources: ['T0'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.fp.sizeUrls',
    description: 'Estimated number of indexable URLs.',
  },
  {
    key: 'fp.sizeEmployees',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T1', 'T3', 'T6'],
    format: 'number',
    width: '100px',
    i18nLabelKey: 'metric.fp.sizeEmployees',
    description: 'Estimated employee count.',
  },
  {
    key: 'fp.sizeFunding',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T3', 'T6'],
    format: 'money',
    width: '100px',
    i18nLabelKey: 'metric.fp.sizeFunding',
    description: 'Total funding raised, if known.',
  },
  {
    key: 'fp.sizeRevenue',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'X'],
    sources: ['T3', 'T6'],
    format: 'money',
    width: '100px',
    i18nLabelKey: 'metric.fp.sizeRevenue',
    description: 'Estimated annual revenue.',
  },
  {
    key: 'fp.geoPrimary',
    namespace: 'fp',
    level: 'F',
    roles: ['H', 'R', 'L'],
    sources: ['T0', 'T1', 'T7'],
    format: 'enum',
    width: '80px',
    i18nLabelKey: 'metric.fp.geoPrimary',
    description: 'Primary geographic market.',
  },
  {
    key: 'fp.geoLocales',
    namespace: 'fp',
    level: 'F',
    roles: ['R', 'L'],
    sources: ['T0'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.fp.geoLocales',
    description: 'All geographic locales targeted.',
  },
  {
    key: 'fp.intentPrimary',
    namespace: 'fp',
    level: 'F',
    roles: ['H', 'R', 'A'],
    sources: ['T6'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.fp.intentPrimary',
    description: 'Primary user intent for the domain.',
  },
  {
    key: 'fp.readinessSeo',
    namespace: 'fp',
    level: 'F',
    roles: ['R'],
    sources: ['T0', 'T6'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.fp.readinessSeo',
    description: 'Overall SEO readiness score.',
    scoreComponent: 'health',
  },
  {
    key: 'fp.readinessAi',
    namespace: 'fp',
    level: 'F',
    roles: ['R'],
    sources: ['T0', 'T6'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.fp.readinessAi',
    description: 'AI discoverability readiness score.',
    scoreComponent: 'ai',
  },
];
