import type { MetricDef } from '@seesby/types';

export const INDEXING_METRICS: MetricDef[] = [
  {
    key: 'p.indexing.url',
    namespace: 'p.indexing',
    level: 'K',
    roles: ['G', 'I', 'X'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.indexing.url',
    description: 'Original crawl URL of the page.',
  },
  {
    key: 'p.indexing.finalUrl',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'X', 'A'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.indexing.finalUrl',
    description: 'Final resolved URL after all redirects.',
  },
  {
    key: 'p.indexing.statusCode',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'R', 'L', 'V', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.statusCode',
    description: 'HTTP response status code.',
  },
  {
    key: 'p.indexing.contentType',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'X', 'L'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.contentType',
    description: 'Content-Type header value.',
  },
  {
    key: 'p.indexing.isHtmlPage',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.isHtmlPage',
    description: 'Whether the response is an HTML page.',
  },
  {
    key: 'p.indexing.canonical',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.indexing.canonical',
    description: 'Canonical URL declared in the page.',
  },
  {
    key: 'p.indexing.canonicalIsSelf',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.canonicalIsSelf',
    description: 'Whether the canonical points to the page itself.',
  },
  {
    key: 'p.indexing.canonicalChain',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.canonicalChain',
    description: 'Full chain of canonical hops from this page.',
  },
  {
    key: 'p.indexing.metaRobots',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.metaRobots',
    description: 'Content of the meta robots tag.',
  },
  {
    key: 'p.indexing.xRobots',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.xRobots',
    description: 'X-Robots-Tag header value.',
  },
  {
    key: 'p.indexing.indexable',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'R', 'L', 'S', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.indexable',
    description: 'Whether the page is indexable by search engines.',
  },
  {
    key: 'p.indexing.indexabilityReason',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.indexabilityReason',
    description: 'Explanation of why page is/isn\'t indexable.',
  },
  {
    key: 'p.indexing.inSitemap',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.inSitemap',
    description: 'Whether the page appears in any sitemap.',
  },
  {
    key: 'p.indexing.sitemapPriority',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.sitemapPriority',
    description: 'Priority value from sitemap entry.',
  },
  {
    key: 'p.indexing.sitemapLastmod',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.indexing.sitemapLastmod',
    description: 'Last modified date from sitemap entry.',
  },
  {
    key: 'p.indexing.sitemapChangefreq',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.indexing.sitemapChangefreq',
    description: 'Change frequency from sitemap entry.',
  },
  {
    key: 'p.indexing.depthCrawl',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'R', 'L', 'V', 'A', 'S'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.depthCrawl',
    description: 'Crawl depth from the start URL (hops).',
  },
  {
    key: 'p.indexing.depthFolder',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.depthFolder',
    description: 'Folder depth in the URL path.',
  },
  {
    key: 'p.indexing.redirectUrl',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.indexing.redirectUrl',
    description: 'The URL this page redirects to.',
  },
  {
    key: 'p.indexing.redirectChain',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.redirectChain',
    description: 'Full redirect chain from this URL.',
  },
  {
    key: 'p.indexing.redirectLoop',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.redirectLoop',
    description: 'Whether a redirect loop is detected.',
  },
  {
    key: 'p.indexing.redirectType',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.redirectType',
    description: 'Redirect type (301, 302, meta, JS)',
  },
  {
    key: 'p.indexing.httpVersion',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X', 'R'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.httpVersion',
    description: 'HTTP protocol version.',
  },
  {
    key: 'p.indexing.responseHeaders',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.p.indexing.responseHeaders',
    description: 'Raw response headers blob.',
  },
  {
    key: 'p.indexing.languageHtml',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.languageHtml',
    description: 'Language attribute from the HTML lang tag.',
  },
  {
    key: 'p.indexing.languageDetected',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.languageDetected',
    description: 'Language detected from page content.',
  },
  {
    key: 'p.indexing.languageMatch',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.languageMatch',
    description: 'Whether declared and detected languages match.',
  },
  {
    key: 'p.indexing.localeDetected',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.localeDetected',
    description: 'Locale detected from URL or content.',
  },
  {
    key: 'p.indexing.hreflangSet',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.indexing.hreflangSet',
    description: 'Set of hreflang annotations on the page.',
  },
  {
    key: 'p.indexing.hreflangErrors',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.hreflangErrors',
    description: 'Number of hreflang annotation errors.',
  },
  {
    key: 'p.indexing.urlLength',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I'],
    sources: ['T0'],
    unit: 'chars',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.urlLength',
    description: 'Character length of the URL.',
  },
  {
    key: 'p.indexing.urlHasQuery',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlHasQuery',
    description: 'Whether URL contains query parameters.',
  },
  {
    key: 'p.indexing.urlHasUppercase',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlHasUppercase',
    description: 'Whether URL contains uppercase characters.',
  },
  {
    key: 'p.indexing.urlHasSessionId',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlHasSessionId',
    description: 'Whether URL contains session ID parameters.',
  },
  {
    key: 'p.indexing.urlHasSpacesEncoded',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlHasSpacesEncoded',
    description: 'Whether URL contains encoded spaces.',
  },
  {
    key: 'p.indexing.urlTrailingSlash',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlTrailingSlash',
    description: 'Whether URL ends with trailing slash.',
  },
  {
    key: 'p.indexing.urlDepthSlug',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlDepthSlug',
    description: 'Whether URL slug is deeply nested.',
  },
  {
    key: 'p.indexing.urlReadableSlug',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlReadableSlug',
    description: 'Whether URL slug is human-readable.',
  },
  {
    key: 'p.indexing.urlHasDate',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.urlHasDate',
    description: 'Whether URL contains date pattern.',
  },
  {
    key: 'p.indexing.favicon',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.indexing.favicon',
    description: 'URL of the favicon used by the page.',
  },
  {
    key: 'p.indexing.charset',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.charset',
    description: 'Document charset.',
  },
  {
    key: 'p.indexing.viewportMeta',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.viewportMeta',
    description: 'Whether viewport meta tag is present.',
  },
  {
    key: 'p.indexing.viewportWidth',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.viewportWidth',
    description: 'Viewport width value.',
  },
  {
    key: 'p.indexing.viewportUserScalable',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.viewportUserScalable',
    description: 'Whether viewport allows user scaling.',
  },
  {
    key: 'p.indexing.rssFeed',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.rssFeed',
    description: 'Whether RSS feed link is present.',
  },
  {
    key: 'p.indexing.serviceWorker',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.serviceWorker',
    description: 'Whether service worker is registered.',
  },
  {
    key: 'p.indexing.webManifest',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.webManifest',
    description: 'Whether web app manifest is linked.',
  },
  {
    key: 'p.indexing.isSoft404',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'L', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.isSoft404',
    description: 'Whether page is a soft 404.',
  },
  // ── EX-A: Page Fundamentals Expansion ──
  {
    key: 'p.indexing.statusCode.mobile',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.statusCode.mobile',
    legacyAlias: ['p.statusCode.mobile'],
    description: 'Status code when crawled with mobile user agent.',
  },
  {
    key: 'p.indexing.statusCode.desktop',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.statusCode.desktop',
    legacyAlias: ['p.statusCode.desktop'],
    description: 'Status code when crawled with desktop user agent.',
  },
  {
    key: 'p.indexing.statusCode.delta',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E', 'T'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.statusCode.delta',
    legacyAlias: ['p.statusCode.delta'],
    description: 'Status code change vs previous crawl.',
  },
  {
    key: 'p.indexing.redirect.count',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.redirect.count',
    legacyAlias: ['p.redirect.count'],
    description: 'Number of redirects in chain.',
  },
  {
    key: 'p.indexing.redirect.hops',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.indexing.redirect.hops',
    legacyAlias: ['p.redirect.hops'],
    description: 'Each hop in the redirect chain with status code and time.',
  },
  {
    key: 'p.indexing.redirect.totalTime',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.redirect.totalTime',
    legacyAlias: ['p.redirect.totalTime'],
    description: 'Total time spent following redirects.',
  },
  {
    key: 'p.indexing.canonical.matchSitemap',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.canonical.matchSitemap',
    legacyAlias: ['p.canonical.matchSitemap'],
    description: 'Whether canonical URL matches sitemap entry.',
  },
  {
    key: 'p.indexing.canonical.matchIndex',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.canonical.matchIndex',
    legacyAlias: ['p.canonical.matchIndex'],
    description: 'Whether canonical is actually indexed (cross-check with GSC).',
  },
  {
    key: 'p.indexing.robots.directives',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.p.indexing.robots.directives',
    legacyAlias: ['p.robots.directives'],
    description: 'Full robots directives parsed: {noindex, nofollow, nosnippet, max-snippet, etc.}.',
  },
  {
    key: 'p.indexing.robots.xRobotsDirectives',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.p.indexing.robots.xRobotsDirectives',
    legacyAlias: ['p.robots.xRobotsDirectives'],
    description: 'X-Robots-Tag header directives.',
  },
  {
    key: 'p.indexing.indexability.signals',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'json',
    i18nLabelKey: 'metric.p.indexing.indexability.signals',
    legacyAlias: ['p.indexability.signals'],
    description: 'All indexability signals: {robots, canonical, noindex, status, depth, sitemap}.',
  },
  {
    key: 'p.indexing.indexability.conflict',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.indexability.conflict',
    legacyAlias: ['p.indexability.conflict'],
    description: 'Whether conflicting indexability signals exist (e.g. noindex + in-sitemap).',
  },
  {
    key: 'p.indexing.sitemap.indexCount',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.sitemap.indexCount',
    legacyAlias: ['p.sitemap.indexCount'],
    description: 'Number of sitemaps containing this URL.',
  },
  {
    key: 'p.indexing.depth.crawl.mobile',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.depth.crawl.mobile',
    legacyAlias: ['p.depth.crawl.mobile'],
    description: 'Click depth from homepage on mobile crawl.',
  },
  {
    key: 'p.indexing.depth.crawl.desktop',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.depth.crawl.desktop',
    legacyAlias: ['p.depth.crawl.desktop'],
    description: 'Click depth from homepage on desktop crawl.',
  },
  {
    key: 'p.indexing.depth.crawl.delta',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.depth.crawl.delta',
    legacyAlias: ['p.depth.crawl.delta'],
    description: 'Click depth change vs previous crawl.',
  },
  {
    key: 'p.indexing.httpVersion.mobile',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.indexing.httpVersion.mobile',
    legacyAlias: ['p.httpVersion.mobile'],
    description: 'HTTP version for mobile user agent.',
  },
  {
    key: 'p.indexing.httpVersion.delta',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.indexing.httpVersion.delta',
    legacyAlias: ['p.httpVersion.delta'],
    description: 'HTTP version change vs previous crawl (e.g. HTTP/1.1 to HTTP/2).',
  },
  {
    key: 'p.indexing.language.htmlValid',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.language.htmlValid',
    legacyAlias: ['p.language.htmlValid'],
    description: 'Whether HTML lang attribute is a valid ISO 639-1 code.',
  },
  {
    key: 'p.indexing.language.contentMatch',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T6', 'T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.indexing.language.contentMatch',
    legacyAlias: ['p.language.contentMatch'],
    description: 'Confidence score that content matches declared language (0-1).',
  },
  {
    key: 'p.indexing.hreflang.selfPresent',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.hreflang.selfPresent',
    legacyAlias: ['p.hreflang.selfPresent'],
    description: 'Whether hreflang set includes self-referencing entry.',
  },
  {
    key: 'p.indexing.hreflang.returnPresent',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.hreflang.returnPresent',
    legacyAlias: ['p.hreflang.returnPresent'],
    description: 'Whether all hreflang alternatives have return tags pointing back.',
  },
  {
    key: 'p.indexing.hreflang.validCount',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.hreflang.validCount',
    legacyAlias: ['p.hreflang.validCount'],
    description: 'Count of valid hreflang annotations.',
  },
  {
    key: 'p.indexing.hreflang.errorCount',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.hreflang.errorCount',
    legacyAlias: ['p.hreflang.errorCount'],
    description: 'Count of hreflang errors.',
  },
  {
    key: 'p.indexing.url.canonicalized',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.url.canonicalized',
    legacyAlias: ['p.url.canonicalized'],
    description: 'Whether URL is the canonical version of a group.',
  },
  {
    key: 'p.indexing.url.parameters',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.indexing.url.parameters',
    legacyAlias: ['p.url.parameters'],
    description: 'Query parameter names present in URL.',
  },
  {
    key: 'p.indexing.url.parameterCount',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.url.parameterCount',
    legacyAlias: ['p.url.parameterCount'],
    description: 'Number of query parameters.',
  },
  {
    key: 'p.indexing.url.utmPresent',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.url.utmPresent',
    legacyAlias: ['p.url.utmPresent'],
    description: 'Whether UTM tracking parameters are present.',
  },
  {
    key: 'p.indexing.url.hashPresent',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.url.hashPresent',
    legacyAlias: ['p.url.hashPresent'],
    description: 'Whether URL fragment (#) is present.',
  },
  {
    key: 'p.indexing.url.protocol',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.indexing.url.protocol',
    legacyAlias: ['p.url.protocol'],
    description: 'URL protocol (http, https).',
  },
  {
    key: 'p.indexing.url.domain',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.url.domain',
    legacyAlias: ['p.url.domain'],
    description: 'Domain portion of URL.',
  },
  {
    key: 'p.indexing.url.subdomain',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'text',
    i18nLabelKey: 'metric.p.indexing.url.subdomain',
    legacyAlias: ['p.url.subdomain'],
    description: 'Subdomain portion (www, blog, docs, etc.).',
  },
  {
    key: 'p.indexing.url.tld',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.indexing.url.tld',
    legacyAlias: ['p.url.tld'],
    description: 'Top-level domain (com, org, co.uk, etc.).',
  },
  {
    key: 'p.indexing.url.pathSegments',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.indexing.url.pathSegments',
    legacyAlias: ['p.url.pathSegments'],
    description: 'Individual path segments as array.',
  },
  {
    key: 'p.indexing.url.hasTrailingSlash',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.url.hasTrailingSlash',
    legacyAlias: ['p.url.hasTrailingSlash'],
    description: 'Whether URL has trailing slash.',
  },
  {
    key: 'p.indexing.url.isCanonical',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.indexing.url.isCanonical',
    legacyAlias: ['p.url.isCanonical'],
    description: 'Whether this URL is the canonical version (self-referencing).',
  },
  {
    key: 'p.indexing.url.canonicalGroup',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.indexing.url.canonicalGroup',
    legacyAlias: ['p.url.canonicalGroup'],
    description: 'All URLs in the same canonical group.',
  },
  {
    key: 'p.indexing.url.canonicalGroupSize',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.indexing.url.canonicalGroupSize',
    legacyAlias: ['p.url.canonicalGroupSize'],
    description: 'Number of URLs pointing to same canonical (large = potential issue).',
  },
  {
    key: 'p.indexing.contentLength.bytes',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.indexing.contentLength.bytes',
    legacyAlias: ['p.contentLength.bytes'],
    description: 'Total HTML response size in bytes.',
  },
  {
    key: 'p.indexing.contentLength.compressed',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.indexing.contentLength.compressed',
    legacyAlias: ['p.contentLength.compressed'],
    description: 'Compressed (gzip/brotli) response size.',
  },
  {
    key: 'p.indexing.contentLength.textBytes',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.indexing.contentLength.textBytes',
    legacyAlias: ['p.contentLength.textBytes'],
    description: 'Visible text content size in bytes.',
  },
  {
    key: 'p.indexing.contentLength.htmlOverhead',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'percent',
    i18nLabelKey: 'metric.p.indexing.contentLength.htmlOverhead',
    legacyAlias: ['p.contentLength.htmlOverhead'],
    description: 'Percentage of HTML that is markup overhead vs visible text.',
  },
  {
    key: 'p.indexing.responseTime.total',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.total',
    legacyAlias: ['p.responseTime.total'],
    description: 'Total response time (DNS + connect + TLS + TTFB + download).',
  },
  {
    key: 'p.indexing.responseTime.dns',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.dns',
    legacyAlias: ['p.responseTime.dns'],
    description: 'DNS resolution time.',
  },
  {
    key: 'p.indexing.responseTime.connect',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.connect',
    legacyAlias: ['p.responseTime.connect'],
    description: 'TCP connection time.',
  },
  {
    key: 'p.indexing.responseTime.tls',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.tls',
    legacyAlias: ['p.responseTime.tls'],
    description: 'TLS handshake time.',
  },
  {
    key: 'p.indexing.responseTime.ttfb',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['G', 'I', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.ttfb',
    legacyAlias: ['p.responseTime.ttfb'],
    description: 'Time to first byte.',
  },
  {
    key: 'p.indexing.responseTime.download',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.download',
    legacyAlias: ['p.responseTime.download'],
    description: 'Content download time.',
  },
  {
    key: 'p.indexing.responseTime.totalMobile',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.totalMobile',
    legacyAlias: ['p.responseTime.totalMobile'],
    description: 'Total response time from mobile user agent.',
  },
  {
    key: 'p.indexing.responseTime.delta',
    namespace: 'p.indexing',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.indexing.responseTime.delta',
    legacyAlias: ['p.responseTime.delta'],
    description: 'Response time change vs previous crawl.',
  },
];
