import type { ActionDescriptor } from '@seesby/types';

export const ACTION_CATALOG: readonly ActionDescriptor[] = [
  // ─── Content Actions (C01–C17) ──────────────────────
  {
    code: 'C01',
    title: 'Rewrite title',
    description: 'Title is missing, too short, too long, or has low CTR vs SERP expectations.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'high',
    requires: ['p.content.title'],
    capabilityRequires: [],
    triggerKey: 'rewrite_title',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C02',
    title: 'Rewrite meta description',
    description: 'Meta description is missing, too short, truncated, or has low CTR.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 20,
    impactHint: 'medium',
    requires: ['p.content.metaDesc'],
    capabilityRequires: [],
    triggerKey: 'rewrite_meta',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C03',
    title: 'Refresh content',
    description: 'Content is decaying, freshness >180 days, and ranks 4–20.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 120,
    impactHint: 'high',
    requires: ['p.content.freshnessDays', 'p.content.contentDecay'],
    capabilityRequires: [],
    triggerKey: 'refresh_content',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C04',
    title: 'Expand thin content',
    description: 'Word count <300, informational intent, ranks <50.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 90,
    impactHint: 'high',
    requires: ['p.content.wordCount', 'p.content.intentSearch'],
    capabilityRequires: [],
    triggerKey: 'expand_thin_content',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C05',
    title: 'Merge cannibalized pages',
    description: 'Two or more pages target the same intent with overlap >0.8.',
    modes: ['content', 'wqa'],
    severity: 'HIGH',
    effortMinutes: 60,
    impactHint: 'high',
    requires: ['p.content.cannibalization'],
    capabilityRequires: [],
    triggerKey: 'merge_cannibal',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C06',
    title: 'Split overlapping page',
    description: 'One page ranks for two distinct intents.',
    modes: ['content', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 90,
    impactHint: 'medium',
    requires: ['p.content.intentSearch'],
    capabilityRequires: [],
    triggerKey: 'split_overlap',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C07',
    title: 'Deprecate page',
    description: 'Zero clicks for 180 days, no rankings, few inlinks.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 10,
    impactHint: 'low',
    requires: ['p.search.gsc.clicks', 'p.links.inlinks'],
    capabilityRequires: [],
    triggerKey: 'deprecate',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C08',
    title: 'Redirect to stronger page',
    description: 'Zombie page with a similar sibling that has traffic.',
    modes: ['content', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 15,
    impactHint: 'medium',
    requires: ['p.search.gsc.clicks'],
    capabilityRequires: [],
    triggerKey: 'redirect_to_stronger',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C09',
    title: 'Add FAQ schema',
    description: 'Q&A content detected but schema is missing.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: ['p.content.faqPresent'],
    capabilityRequires: [],
    triggerKey: 'add_faq_schema',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C10',
    title: 'Add HowTo schema',
    description: 'Procedure steps detected but HowTo schema is missing.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: ['p.content.howtoPresent'],
    capabilityRequires: [],
    triggerKey: 'add_howto_schema',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C11',
    title: 'Add author E-E-A-T signals',
    description: 'YMYL page with no author and no bio.',
    modes: ['content', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.content.eeatScore'],
    capabilityRequires: [],
    triggerKey: 'add_author_eeat',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C12',
    title: 'Rebuild topic cluster',
    description: 'Topic cluster coverage below 60%.',
    modes: ['content', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 180,
    impactHint: 'high',
    requires: ['p.content.topicCoverage'],
    capabilityRequires: [],
    triggerKey: 'rebuild_topic_cluster',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'cluster',
    autoRunCapable: false,
  },
  {
    code: 'C13',
    title: 'Fix duplicate content',
    description: 'Exact or near-duplicate detected.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 45,
    impactHint: 'high',
    requires: ['p.content.duplicateExact'],
    capabilityRequires: [],
    triggerKey: 'fix_duplicate',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C14',
    title: 'Batch add alt text',
    description: 'Five or more images missing alt text.',
    modes: ['content', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 20,
    impactHint: 'low',
    requires: ['p.content.imagesMissingAlt'],
    capabilityRequires: [],
    triggerKey: 'alt_text_batch',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C15',
    title: 'Fix readability',
    description: 'Readability grade above expected level for intent and language.',
    modes: ['content', 'wqa'],
    severity: 'LOW',
    effortMinutes: 60,
    impactHint: 'low',
    requires: ['p.content.readabilityGradeLevel'],
    capabilityRequires: [],
    triggerKey: 'fix_readability',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C16',
    title: 'Rewrite AI-generated text',
    description: 'AI-generated probability >80%, ranks <50, low E-E-A-T.',
    modes: ['content', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 90,
    impactHint: 'medium',
    requires: ['p.content.aiGeneratedProb'],
    capabilityRequires: [],
    triggerKey: 'rewrite_ai_text',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'C17',
    title: 'Add internal links',
    description: 'Orphan or near-orphan page with intent match available.',
    modes: ['content', 'wqa', 'linksAuthority'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: ['p.links.orphan'],
    capabilityRequires: [],
    triggerKey: 'add_internal_links_content',
    forecastUnit: 'clicks',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },

  // ─── Technical Actions (T01–T16) ────────────────────
  {
    code: 'T01',
    title: 'Fix indexability',
    description: 'Page is noindexed, has wrong canonical, or robots blocks a valuable page.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 10,
    impactHint: 'high',
    requires: ['p.indexing.indexable'],
    capabilityRequires: [],
    triggerKey: 'fix_indexability',
    forecastUnit: 'clicks',
    bandHint: 'CRITICAL',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T02',
    title: 'Fix 5xx errors',
    description: 'Server returns 5xx status code.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 15,
    impactHint: 'high',
    requires: ['p.indexing.statusCode'],
    capabilityRequires: [],
    triggerKey: 'fix_5xx',
    forecastUnit: 'clicks',
    bandHint: 'CRITICAL',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T03',
    title: 'Fix 4xx errors',
    description: '404 with inbound links or external backlinks.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 20,
    impactHint: 'high',
    requires: ['p.indexing.statusCode'],
    capabilityRequires: [],
    triggerKey: 'fix_4xx',
    forecastUnit: 'clicks',
    bandHint: 'CRITICAL',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T04',
    title: 'Fix redirect chain',
    description: 'Redirect chain >1 hop or loop detected.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 15,
    impactHint: 'medium',
    requires: ['p.indexing.redirectChain'],
    capabilityRequires: [],
    triggerKey: 'fix_redirect_chain',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T05',
    title: 'Fix hreflang errors',
    description: 'Hreflang errors detected (missing self, broken links, non-mutual).',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.indexing.hreflangErrors'],
    capabilityRequires: [],
    triggerKey: 'fix_hreflang',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T06',
    title: 'Fix schema errors',
    description: 'Schema validation errors detected.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.content.schemaErrors'],
    capabilityRequires: [],
    triggerKey: 'fix_schema_errors',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T07',
    title: 'Upgrade schema coverage',
    description: 'Industry-required schema types missing.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.content.schemaCoverage'],
    capabilityRequires: [],
    triggerKey: 'upgrade_schema_coverage',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T08',
    title: 'Improve Core Web Vitals',
    description: 'CWV bucket is poor and page has high sessions.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 120,
    impactHint: 'high',
    requires: ['p.tech.cwv.bucket', 'p.ga.sessions'],
    capabilityRequires: [],
    triggerKey: 'improve_cwv',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T09',
    title: 'Reduce JS dependency',
    description: 'JS render dependency >60% with critical content JS-only.',
    modes: ['technical', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 180,
    impactHint: 'medium',
    requires: ['p.tech.jsRenderDep'],
    capabilityRequires: [],
    triggerKey: 'reduce_js_dependency',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T10',
    title: 'Fix security headers',
    description: 'Security grade below C.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.tech.sec.grade'],
    capabilityRequires: [],
    triggerKey: 'fix_security_headers',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'T11',
    title: 'Rotate SSL certificate',
    description: 'SSL certificate expiring within 30 days.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 10,
    impactHint: 'high',
    requires: ['p.tech.sec.sslDays'],
    capabilityRequires: [],
    triggerKey: 'rotate_ssl',
    forecastUnit: 'none',
    bandHint: 'CRITICAL',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'T12',
    title: 'Fix accessibility violations',
    description: 'More than 10 a11y violations on a high-traffic page.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.tech.a11y.violations'],
    capabilityRequires: [],
    triggerKey: 'fix_a11y_batch',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T13',
    title: 'Fix sitemap issues',
    description: 'Sitemap inclusion mismatch or wrong lastmod.',
    modes: ['technical', 'wqa'],
    severity: 'LOW',
    effortMinutes: 15,
    impactHint: 'low',
    requires: ['p.indexing.inSitemap'],
    capabilityRequires: [],
    triggerKey: 'fix_sitemap',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'T14',
    title: 'Fix mixed content',
    description: 'Mixed HTTP/HTTPS content detected.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.tech.sec.mixedContent'],
    capabilityRequires: [],
    triggerKey: 'fix_mixedContent',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T15',
    title: 'Remove soft 404',
    description: 'Page identified as a soft 404.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 20,
    impactHint: 'medium',
    requires: ['p.indexing.isSoft404'],
    capabilityRequires: [],
    triggerKey: 'remove_soft404',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'T16',
    title: 'Fix canonical loop',
    description: 'Canonical chain forms a loop.',
    modes: ['technical', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 15,
    impactHint: 'high',
    requires: ['p.indexing.canonicalChain'],
    capabilityRequires: [],
    triggerKey: 'fix_canonical_loop',
    forecastUnit: 'none',
    bandHint: 'CRITICAL',
    units: 'page',
    autoRunCapable: false,
  },

  // ─── Links Actions (L01–L07) ────────────────────────
  {
    code: 'L01',
    title: 'Add internal links',
    description: 'Orphan or near-orphan page needs internal links.',
    modes: ['linksAuthority', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'high',
    requires: ['p.links.orphan'],
    capabilityRequires: [],
    triggerKey: 'add_internal_links',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'L02',
    title: 'Redistribute PageRank',
    description: 'Valuable page has low internal PageRank.',
    modes: ['linksAuthority', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.links.internalPagerank'],
    capabilityRequires: [],
    triggerKey: 'redistribute_pagerank',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'L03',
    title: 'Remove toxic backlinks',
    description: 'Toxic backlink share >5% and rankings dropping.',
    modes: ['linksAuthority', 'wqa'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'high',
    requires: ['p.links.toxicBacklinkShare'],
    capabilityRequires: [],
    triggerKey: 'remove_toxic_backlinks',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'L04',
    title: 'Reclaim unlinked mention',
    description: 'Brand mention detected without a link.',
    modes: ['linksAuthority', 'wqa'],
    severity: 'LOW',
    effortMinutes: 20,
    impactHint: 'low',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'reclaim_unlinked_mention',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'L05',
    title: 'Fix broken links',
    description: 'Broken internal or external links on high-value pages.',
    modes: ['linksAuthority', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.links.broken'],
    capabilityRequires: [],
    triggerKey: 'fix_broken_links',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'L06',
    title: 'Shorten redirect chain',
    description: 'Redirect chain length exceeds 2 hops.',
    modes: ['linksAuthority', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 15,
    impactHint: 'low',
    requires: ['p.indexing.redirectChain'],
    capabilityRequires: [],
    triggerKey: 'shorten_redirect_chain',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'L07',
    title: 'Diversify anchor text',
    description: 'Exact-match anchor text exceeds 30% (spam signal).',
    modes: ['linksAuthority', 'wqa'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: ['p.links.exactMatchAnchorPct'],
    capabilityRequires: [],
    triggerKey: 'diversify_anchors',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'site',
    autoRunCapable: false,
  },

  // ─── Search Actions (S01–S06) ───────────────────────
  {
    code: 'S01',
    title: 'Target near-miss keywords',
    description: 'Page ranks 4–10 with significant volume; small content tweak can push to top 3.',
    modes: ['wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 60,
    impactHint: 'high',
    requires: ['p.search.gsc.position'],
    capabilityRequires: [],
    triggerKey: 'target_near_miss_kw',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'S02',
    title: 'Win featured snippet',
    description: 'Rank top 5, answerBox fit is high, but snippet is not owned.',
    modes: ['wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 45,
    impactHint: 'medium',
    requires: ['p.search.gsc.position', 'p.content.answerBoxFit'],
    capabilityRequires: [],
    triggerKey: 'win_featured_snippet',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'S03',
    title: 'Reclaim lost keywords',
    description: 'Keyword dropped from top 10 in last 28 days.',
    modes: ['wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 60,
    impactHint: 'high',
    requires: ['p.search.gsc.isLosing'],
    capabilityRequires: [],
    triggerKey: 'reclaim_lost_kw',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'S04',
    title: 'Expand intent coverage',
    description: 'People Also Ask and related questions gap identified.',
    modes: ['wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 90,
    impactHint: 'medium',
    requires: ['p.content.questionsList'],
    capabilityRequires: [],
    triggerKey: 'expand_intent_coverage',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'S05',
    title: 'Deduplicate SERP cannibalization',
    description: 'Multiple URLs rotating for the same keyword.',
    modes: ['wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 45,
    impactHint: 'high',
    requires: ['p.search.snippetCannibalized'],
    capabilityRequires: [],
    triggerKey: 'dedupe_serp_cannibal',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'S06',
    title: 'Optimize CTR',
    description: 'High impressions but CTR below expected for position.',
    modes: ['wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.search.gsc.ctr'],
    capabilityRequires: [],
    triggerKey: 'optimize_ctr',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },

  // ─── AI Actions (A01–A05) ───────────────────────────
  {
    code: 'A01',
    title: 'Unblock AI bots',
    description: 'Valuable AI bot is blocked and citation rate is low.',
    modes: ['ai', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 15,
    impactHint: 'medium',
    requires: ['p.ai.botsAllowed', 'p.ai.citationRate'],
    capabilityRequires: [],
    triggerKey: 'unblock_ai_bots',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'A02',
    title: 'Add llms.txt',
    description: 'No llms.txt file and site has >1k URLs.',
    modes: ['ai', 'wqa'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.ai.llmsTxt'],
    capabilityRequires: [],
    triggerKey: 'add_llms_txt',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'A03',
    title: 'Add answer structure',
    description: 'Answer box fit is low on informational intent page.',
    modes: ['ai', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.ai.answerBoxFit'],
    capabilityRequires: [],
    triggerKey: 'add_answer_structure',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'A04',
    title: 'Add speakable markup',
    description: 'Voice-relevant intent detected but speakable schema missing.',
    modes: ['ai', 'wqa'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: ['p.ai.speakable'],
    capabilityRequires: [],
    triggerKey: 'add_speakable',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'A05',
    title: 'Claim entity in Knowledge Graph',
    description: 'Organization schema is weak or Knowledge Panel is missing.',
    modes: ['ai', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.search.entityInKG'],
    capabilityRequires: [],
    triggerKey: 'claim_entity',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'site',
    autoRunCapable: false,
  },

  // ─── Paid Actions (P01–P08) ─────────────────────────
  {
    code: 'P01',
    title: 'Pause low Quality Score ads',
    description: 'Quality Score <6 with spend above threshold.',
    modes: ['paid', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 5,
    impactHint: 'high',
    requires: ['p.paid.qsLpComponent'],
    capabilityRequires: [],
    triggerKey: 'pause_low_qs',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: true,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P02',
    title: 'Add negative keywords',
    description: 'Irrelevant search terms triggering ads detected.',
    modes: ['paid', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'add_negatives',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: true,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P03',
    title: 'Refresh fatigued ad',
    description: 'CTR declined 25% over 14 days.',
    modes: ['paid', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'refresh_fatigued_ad',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P04',
    title: 'Fix landing page for Quality Score',
    description: 'Landing page experience component of Quality Score is low.',
    modes: ['paid', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 120,
    impactHint: 'high',
    requires: ['p.paid.qsLpComponent'],
    capabilityRequires: [],
    triggerKey: 'fix_lp_for_qs',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P05',
    title: 'Reallocate budget',
    description: 'ROAS <1 while sibling campaigns have ROAS >3 with budget headroom.',
    modes: ['paid'],
    severity: 'HIGH',
    effortMinutes: 15,
    impactHint: 'high',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'reallocate_budget',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: true,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P06',
    title: 'Stop disapproved ads',
    description: 'Ad is disapproved but still active in campaign.',
    modes: ['paid', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 10,
    impactHint: 'high',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'stop_disapproved',
    forecastUnit: 'none',
    bandHint: 'CRITICAL',
    units: 'site',
    autoRunCapable: true,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P07',
    title: 'Add assets to RSA',
    description: 'Responsive Search Ad asset coverage below "Good".',
    modes: ['paid'],
    severity: 'LOW',
    effortMinutes: 30,
    impactHint: 'low',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'add_assets_to_rsa',
    forecastUnit: 'clicks',
    bandHint: 'HYGIENE',
    units: 'site',
    autoRunCapable: false,
    industries: ['ecommerce', 'saas'],
  },
  {
    code: 'P08',
    title: 'Align message match',
    description: 'Ad-to-landing-page message match score below 0.6.',
    modes: ['paid', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: ['p.paid.adIntentMatch'],
    capabilityRequires: [],
    triggerKey: 'align_message_match',
    forecastUnit: 'conversions',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce', 'saas'],
  },

  // ─── UX Actions (U01–U05) ───────────────────────────
  {
    code: 'U01',
    title: 'Fix form field',
    description: 'Single form field has >30% drop-off.',
    modes: ['uxConversion', 'wqa'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'high',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'fix_form_field',
    forecastUnit: 'conversions',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'U02',
    title: 'Reduce form fields',
    description: 'Form has >6 fields and completion rate <40%.',
    modes: ['uxConversion', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 60,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'reduce_form_fields',
    forecastUnit: 'conversions',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'U03',
    title: 'Fix rage click hotspot',
    description: 'Rage click density above threshold on converter pages.',
    modes: ['uxConversion', 'wqa'],
    severity: 'HIGH',
    effortMinutes: 60,
    impactHint: 'high',
    requires: ['p.ux.rageClicks'],
    capabilityRequires: [],
    triggerKey: 'fix_rage_hotspot',
    forecastUnit: 'conversions',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'U04',
    title: 'Move CTA above fold',
    description: 'Fold line is above primary CTA and conversion rate is low.',
    modes: ['uxConversion', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.ga.conversionRate'],
    capabilityRequires: [],
    triggerKey: 'move_cta_above_fold',
    forecastUnit: 'conversions',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'U05',
    title: 'Run experiment',
    description: 'Friction point identified and traffic exceeds minimum sample.',
    modes: ['uxConversion', 'wqa'],
    severity: 'LOW',
    effortMinutes: 120,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'run_experiment',
    forecastUnit: 'conversions',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
  },

  // ─── Social Actions (SO01–SO04) ─────────────────────
  {
    code: 'SO01',
    title: 'Fix Open Graph tags',
    description: 'OG issues detected and traffic from social is present.',
    modes: ['socialBrand', 'wqa', 'fullAudit'],
    severity: 'MEDIUM',
    effortMinutes: 15,
    impactHint: 'medium',
    requires: ['p.social.ogMissingTags'],
    capabilityRequires: [],
    triggerKey: 'fix_og_tags',
    forecastUnit: 'clicks',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
  },
  {
    code: 'SO02',
    title: 'Respond to crisis',
    description: 'Social crisis signal detected (negative sentiment spike).',
    modes: ['socialBrand'],
    severity: 'CRITICAL',
    effortMinutes: 60,
    impactHint: 'high',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'respond_crisis',
    forecastUnit: 'none',
    bandHint: 'CRITICAL',
    units: 'site',
    autoRunCapable: false,
    industries: ['ecommerce', 'saas', 'restaurant', 'local'],
  },
  {
    code: 'SO03',
    title: 'Shift posting time',
    description: 'Current posting cadence does not align with best engagement times.',
    modes: ['socialBrand'],
    severity: 'LOW',
    effortMinutes: 5,
    impactHint: 'low',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'shift_posting_time',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'site',
    autoRunCapable: false,
  },
  {
    code: 'SO04',
    title: 'Increase short-form video',
    description: 'Engagement lift from short-form video but posting cadence is low.',
    modes: ['socialBrand'],
    severity: 'LOW',
    effortMinutes: 120,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'increase_short_video',
    forecastUnit: 'none',
    bandHint: 'STRATEGIC',
    units: 'site',
    autoRunCapable: false,
  },

  // ─── Commerce Actions (E01–E04) ─────────────────────
  {
    code: 'E01',
    title: 'Fix feed attributes',
    description: 'Product feed errors on revenue-generating products.',
    modes: ['commerce', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'high',
    requires: ['p.commerce.feedErrors'],
    capabilityRequires: [],
    triggerKey: 'fix_feed_attrs',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce'],
  },
  {
    code: 'E02',
    title: 'Restore visibility for out-of-stock',
    description: 'Product out of stock >7 days but still indexed.',
    modes: ['commerce', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 15,
    impactHint: 'high',
    requires: ['p.commerce.availability'],
    capabilityRequires: [],
    triggerKey: 'restock_visibility',
    forecastUnit: 'revenue',
    bandHint: 'HIGH',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce'],
  },
  {
    code: 'E03',
    title: 'Add review schema',
    description: 'Reviews present but aggregate rating schema is missing.',
    modes: ['commerce', 'wqa', 'fullAudit'],
    severity: 'LOW',
    effortMinutes: 15,
    impactHint: 'low',
    requires: ['p.commerce.reviewsCount'],
    capabilityRequires: [],
    triggerKey: 'add_review_schema',
    forecastUnit: 'none',
    bandHint: 'HYGIENE',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce'],
  },
  {
    code: 'E04',
    title: 'Flatten category depth',
    description: 'Category depth >3 with traffic on the category page.',
    modes: ['commerce', 'wqa'],
    severity: 'MEDIUM',
    effortMinutes: 90,
    impactHint: 'medium',
    requires: [],
    capabilityRequires: [],
    triggerKey: 'flatten_category_depth',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
    industries: ['ecommerce'],
  },

  // ─── Local Actions (LO01–LO04) ──────────────────────
  {
    code: 'LO01',
    title: 'Fix NAP consistency',
    description: 'Name/Address/Phone consistency score below 0.9.',
    modes: ['local', 'wqa', 'fullAudit'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'high',
    requires: ['p.local.napScore'],
    capabilityRequires: [],
    triggerKey: 'fix_nap',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
    industries: ['local', 'restaurant', 'healthcare'],
  },
  {
    code: 'LO02',
    title: 'Claim Google Business Profile',
    description: 'GBP is unverified or missing.',
    modes: ['local', 'wqa', 'fullAudit'],
    severity: 'CRITICAL',
    effortMinutes: 10,
    impactHint: 'high',
    requires: ['p.local.gbpVerified'],
    capabilityRequires: [],
    triggerKey: 'claim_gbp',
    forecastUnit: 'none',
    bandHint: 'CRITICAL',
    units: 'site',
    autoRunCapable: false,
    industries: ['local', 'restaurant', 'healthcare'],
  },
  {
    code: 'LO03',
    title: 'Respond to negative reviews',
    description: 'Three or more unresponded negative reviews.',
    modes: ['local', 'wqa'],
    severity: 'HIGH',
    effortMinutes: 30,
    impactHint: 'medium',
    requires: ['p.local.reviewsNegative'],
    capabilityRequires: [],
    triggerKey: 'respond_reviews',
    forecastUnit: 'none',
    bandHint: 'HIGH',
    units: 'site',
    autoRunCapable: false,
    industries: ['local', 'restaurant', 'healthcare'],
  },
  {
    code: 'LO04',
    title: 'Add service area page',
    description: 'Claimed service area has no dedicated landing page.',
    modes: ['local', 'wqa'],
    severity: 'LOW',
    effortMinutes: 90,
    impactHint: 'medium',
    requires: ['p.local.serviceAreaPages'],
    capabilityRequires: [],
    triggerKey: 'add_service_area_page',
    forecastUnit: 'clicks',
    bandHint: 'STRATEGIC',
    units: 'page',
    autoRunCapable: false,
    industries: ['local', 'restaurant', 'healthcare'],
  },
] as const;

// ─── Helpers ──────────────────────────────────────────
const _ACTION_MAP = new Map<string, ActionDescriptor>(
  ACTION_CATALOG.map(a => [a.code, a as ActionDescriptor]),
);

export function getAction(code: string): ActionDescriptor | undefined {
  return _ACTION_MAP.get(code);
}

export function getAllActions(): readonly ActionDescriptor[] {
  return ACTION_CATALOG;
}

export function getActionsByMode(mode: string): ActionDescriptor[] {
  return ACTION_CATALOG.filter(a => a.modes.includes(mode as any));
}

export function getActionsByIndustry(industry: string): ActionDescriptor[] {
  return ACTION_CATALOG.filter(
    a => !a.industries || a.industries.includes(industry as any),
  );
}
