import type { MetricDef } from '@seesby/types';

export const ISSUES_METRICS: MetricDef[] = [
  {
    key: 'p.issues.count',
    namespace: 'p.issues',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.issues.count.label',
    description: 'Total number of issues found on this page.',
  },

  // ─── EX-Q.4: Diagnostic / Anomaly Flags (page-level) ──────────────
  {
    key: 'p.diag.statusAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.statusAnomaly',
    description: 'Status code changed unexpectedly since last crawl.',
  },
  {
    key: 'p.diag.redirectAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.redirectAnomaly',
    description: 'Redirect behavior changed since last crawl.',
  },
  {
    key: 'p.diag.canonicalAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.canonicalAnomaly',
    description: 'Canonical target changed since last crawl.',
  },
  {
    key: 'p.diag.robotsAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.robotsAnomaly',
    description: 'Robots directive changed since last crawl.',
  },
  {
    key: 'p.diag.indexabilityAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.indexabilityAnomaly',
    description: 'Indexability status changed since last crawl.',
  },
  {
    key: 'p.diag.titleAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.titleAnomaly',
    description: 'Title changed significantly since last crawl.',
  },
  {
    key: 'p.diag.metaDescAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.metaDescAnomaly',
    description: 'Meta description changed since last crawl.',
  },
  {
    key: 'p.diag.schemaAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.schemaAnomaly',
    description: 'Schema types changed since last crawl.',
  },
  {
    key: 'p.diag.cwvAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.cwvAnomaly',
    description: 'CWV degraded significantly since last measurement.',
  },
  {
    key: 'p.diag.contentAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.contentAnomaly',
    description: 'Content changed significantly (>30% word diff).',
  },
  {
    key: 'p.diag.linkAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.linkAnomaly',
    description: 'Link count changed significantly.',
  },
  {
    key: 'p.diag.trafficAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.trafficAnomaly',
    description: 'Traffic changed >50% vs previous period.',
  },
  {
    key: 'p.diag.revenueAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.revenueAnomaly',
    description: 'Revenue changed >50% vs previous period.',
  },
  {
    key: 'p.diag.citationAnomaly',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.diag.citationAnomaly',
    description: 'AI citation status changed.',
  },
  {
    key: 'p.diag.soft404Risk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.soft404Risk',
    description: 'Soft 404 risk score (0-1).',
  },
  {
    key: 'p.diag.cloakingRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.cloakingRisk',
    description: 'Cloaking risk score (static vs rendered content diff).',
  },
  {
    key: 'p.diag.doorwayRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.doorwayRisk',
    description: 'Doorway page risk score.',
  },
  {
    key: 'p.diag.thinContentRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.thinContentRisk',
    description: 'Thin content risk score.',
  },
  {
    key: 'p.diag.duplicateRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.duplicateRisk',
    description: 'Duplicate content risk score.',
  },
  {
    key: 'p.diag.cannibalizationRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.cannibalizationRisk',
    description: 'Cannibalization risk score.',
  },
  {
    key: 'p.diag.anchorSpamRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.anchorSpamRisk',
    description: 'Anchor text spam risk score.',
  },
  {
    key: 'p.diag.linkSpamRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.linkSpamRisk',
    description: 'Link spam risk score.',
  },
  {
    key: 'p.diag.securityRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.securityRisk',
    description: 'Security vulnerability risk score.',
  },
  {
    key: 'p.diag.a11yRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.a11yRisk',
    description: 'Accessibility compliance risk score.',
  },
  {
    key: 'p.diag.seoRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.seoRisk',
    description: 'Overall SEO risk composite score.',
  },
  {
    key: 'p.diag.contentRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.contentRisk',
    description: 'Content quality risk composite score.',
  },
  {
    key: 'p.diag.techRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.techRisk',
    description: 'Technical risk composite score.',
  },
  {
    key: 'p.diag.linkRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T4'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.linkRisk',
    description: 'Link profile risk composite score.',
  },
  {
    key: 'p.diag.overallRisk',
    namespace: 'p.diag',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.diag.overallRisk',
    description: 'Overall page risk score (composite of all risks).',
  },
  {
    key: 'p.diag.riskBucket',
    namespace: 'p.diag',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.diag.riskBucket',
    description: 'Risk severity bucket.',
  },
];
