import type { MetricDef } from '@seesby/types';

export const LINKS_METRICS: MetricDef[] = [
  {
    key: 'p.links.inlinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.inlinks.label',
    description: 'Number of internal links pointing to this page.',
  },
  {
    key: 'p.links.uniqueInlinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A', 'S'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.uniqueInlinks.label',
    description: 'Number of unique internal pages linking to this page.',
  },
  {
    key: 'p.links.outlinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.label',
    description: 'Number of outgoing links on this page.',
  },
  {
    key: 'p.links.externalOutlinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.externalOutlinks.label',
    description: 'Number of outgoing external links on this page.',
  },
  {
    key: 'p.links.uniqueExternalDomains',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.uniqueExternalDomains.label',
    description: 'Number of unique external domains linked from this page.',
  },
  {
    key: 'p.links.internalPagerank',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'V', 'S', 'A'],
    sources: ['T0'],
    format: 'score',
    scoreComponent: 'links',
    width: '70px',
    i18nLabelKey: 'metric.p.links.internalPagerank.label',
    description: 'Internal PageRank score for this page.',
  },
  {
    key: 'p.links.linkEquity',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'V', 'S', 'A'],
    sources: ['T0'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.links.linkEquity.label',
    description: 'Estimated link equity passing to this page.',
  },
  {
    key: 'p.links.linkScore',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'S'],
    sources: ['T0'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.links.linkScore.label',
    description: 'Composite link quality score for this page.',
  },
  {
    key: 'p.links.broken',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.broken.label',
    description: 'Number of broken outgoing links on this page.',
  },
  {
    key: 'p.links.insecure',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.insecure.label',
    description: 'Number of insecure (HTTP) outgoing links on this page.',
  },
  {
    key: 'p.links.redirectsIn',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.redirectsIn.label',
    description: 'Number of internal redirects pointing to this page.',
  },
  {
    key: 'p.links.orphan',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.links.orphan.label',
    description: 'Whether this page has zero internal inbound links (orphan page).',
  },
  {
    key: 'p.links.nearOrphan',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.links.nearOrphan.label',
    description: 'Whether this page has very few internal inbound links (near-orphan).',
  },
  {
    key: 'p.links.clickDepth',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    unit: 'hops',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.clickDepth.label',
    description: 'Minimum number of clicks from the homepage to reach this page.',
  },
  {
    key: 'p.links.navLinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.navLinks.label',
    description: 'Number of navigation links on this page.',
  },
  {
    key: 'p.links.footerLinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.footerLinks.label',
    description: 'Number of footer links on this page.',
  },
  {
    key: 'p.links.referringDomains',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.referringDomains.label',
    description: 'Number of unique referring domains linking to this page.',
  },
  {
    key: 'p.links.backlinks',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'R', 'V'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.backlinks.label',
    description: 'Total number of backlinks pointing to this page.',
  },
  {
    key: 'p.links.urlRating',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.links.urlRating.label',
    description: 'URL rating (0-100) based on backlink profile quality.',
  },
  {
    key: 'p.links.anchorTextDiversity',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T0'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.links.anchorTextDiversity.label',
    description: 'Diversity score of anchor texts pointing to this page.',
  },
  {
    key: 'p.links.anchorCloud',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.links.anchorCloud.label',
    description: 'Top anchor texts used in links to this page.',
  },
  {
    key: 'p.links.anchorCloudMovement',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.links.anchorCloudMovement.label',
    description: 'Changes in anchor text distribution over time.',
  },
  {
    key: 'p.links.genericAnchorCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.genericAnchorCount.label',
    description: 'Number of generic anchor texts (e.g. "click here") linking to this page.',
  },
  {
    key: 'p.links.toxicBacklinkShare',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A', 'E', 'S'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.links.toxicBacklinkShare.label',
    description: 'Percentage of backlinks classified as toxic or spammy.',
  },
  {
    key: 'p.links.lostBacklinks7d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.lostBacklinks7d.label',
    description: 'Number of backlinks lost in the last 7 days.',
  },
  {
    key: 'p.links.newBacklinks7d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.newBacklinks7d.label',
    description: 'Number of new backlinks gained in the last 7 days.',
  },
  {
    key: 'p.links.velocity',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0', 'T1', 'T2', 'T3'],
    unit: 'links/day',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.velocity.label',
    description: 'Rate of backlink acquisition over time.',
  },
  {
    key: 'p.links.brandedAnchorPct',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.links.brandedAnchorPct.label',
    description: 'Percentage of backlinks with branded anchor text.',
  },
  {
    key: 'p.links.exactMatchAnchorPct',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.links.exactMatchAnchorPct.label',
    description: 'Percentage of backlinks with exact-match anchor text.',
  },
  {
    key: 'p.links.redirectLoss',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.links.redirectLoss.label',
    description: 'Percentage of link equity lost through redirect chains.',
  },

  // ── EX-D: Links Expansion ──
  {
    key: 'p.links.inlinks.mobile',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.inlinks.mobile.label',
    description: 'Internal inlinks found on mobile crawl.',
  },
  {
    key: 'p.links.inlinks.delta7d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.inlinks.delta7d.label',
    description: 'Inlink change vs 7 days ago.',
  },
  {
    key: 'p.links.inlinks.delta28d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.inlinks.delta28d.label',
    description: 'Inlink change vs 28 days ago.',
  },
  {
    key: 'p.links.inlinks.trend',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T3', 'T4'],
    format: 'json',
    i18nLabelKey: 'metric.p.links.inlinks.trend.label',
    description: 'Inlink count time-series.',
  },
  {
    key: 'p.links.outlinks.internal',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.internal.label',
    description: 'Internal outgoing links.',
  },
  {
    key: 'p.links.outlinks.external',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.external.label',
    description: 'External outgoing links.',
  },
  {
    key: 'p.links.outlinks.nofollow',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.nofollow.label',
    description: 'Nofollow outgoing links.',
  },
  {
    key: 'p.links.outlinks.sponsored',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.sponsored.label',
    description: 'Sponsored outgoing links.',
  },
  {
    key: 'p.links.outlinks.ugc',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.ugc.label',
    description: 'UGC outgoing links.',
  },
  {
    key: 'p.links.outlinks.toSameDomain',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.toSameDomain.label',
    description: 'Links to same domain (internal).',
  },
  {
    key: 'p.links.outlinks.toSubdomain',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.outlinks.toSubdomain.label',
    description: 'Links to different subdomain.',
  },
  {
    key: 'p.links.referringDomains.trend',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T3', 'T4'],
    format: 'json',
    i18nLabelKey: 'metric.p.links.referringDomains.trend.label',
    description: 'Referring domains count time-series.',
  },
  {
    key: 'p.links.referringDomains.delta7d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.referringDomains.delta7d.label',
    description: 'Referring domain change vs 7 days ago.',
  },
  {
    key: 'p.links.referringDomains.delta28d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.referringDomains.delta28d.label',
    description: 'Referring domain change vs 28 days ago.',
  },
  {
    key: 'p.links.referringDomains.quality',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T3', 'T4'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.links.referringDomains.quality.label',
    description: 'Average quality of referring domains.',
  },
  {
    key: 'p.links.referringDomains.topList',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T3', 'T4'],
    format: 'list',
    i18nLabelKey: 'metric.p.links.referringDomains.topList.label',
    description: 'Top 10 referring domains by authority.',
  },
  {
    key: 'p.links.backlinks.trend',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T3', 'T4'],
    format: 'json',
    i18nLabelKey: 'metric.p.links.backlinks.trend.label',
    description: 'Backlink count time-series.',
  },
  {
    key: 'p.links.backlinks.new30d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.backlinks.new30d.label',
    description: 'New backlinks in last 30 days.',
  },
  {
    key: 'p.links.backlinks.lost30d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.backlinks.lost30d.label',
    description: 'Lost backlinks in last 30 days.',
  },
  {
    key: 'p.links.backlinks.net30d',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.backlinks.net30d.label',
    description: 'Net backlink gain/loss in 30 days.',
  },
  {
    key: 'p.links.urlRating.bucket',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T3'],
    format: 'enum',
    i18nLabelKey: 'metric.p.links.urlRating.bucket.label',
    description: 'URL rating bucket (high: 70-100, medium: 40-69, low: 10-39, none: 0-9).',
  },
  {
    key: 'p.links.urlRating.trend',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.p.links.urlRating.trend.label',
    description: 'URL rating time-series.',
  },
  {
    key: 'p.links.urlRating.delta',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T3'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.urlRating.delta.label',
    description: 'URL rating change vs previous month.',
  },
  {
    key: 'p.links.internalPagerank.bucket',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.links.internalPagerank.bucket.label',
    description: 'Internal PageRank bucket (high, medium, low, none).',
  },
  {
    key: 'p.links.internalPagerank.percentile',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.internalPagerank.percentile.label',
    description: 'Internal PageRank percentile within site.',
  },
  {
    key: 'p.links.internalPagerank.trend',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T7'],
    format: 'json',
    i18nLabelKey: 'metric.p.links.internalPagerank.trend.label',
    description: 'Internal PageRank time-series.',
  },
  {
    key: 'p.links.linkEquity.bucket',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.links.linkEquity.bucket.label',
    description: 'Link equity bucket (high, medium, low, none).',
  },
  {
    key: 'p.links.broken.count',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.broken.count.label',
    description: 'Total broken link count.',
  },
  {
    key: 'p.links.broken.internal',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.broken.internal.label',
    description: 'Broken internal links.',
  },
  {
    key: 'p.links.broken.external',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.broken.external.label',
    description: 'Broken external links.',
  },
  {
    key: 'p.links.broken.newSinceLastCrawl',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.broken.newSinceLastCrawl.label',
    description: 'New broken links since last crawl.',
  },
  {
    key: 'p.links.anchorCloud.topAnchors',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T3', 'T4'],
    format: 'list',
    i18nLabelKey: 'metric.p.links.anchorCloud.topAnchors.label',
    description: 'Top 20 anchor text phrases.',
  },
  {
    key: 'p.links.anchorCloud.topAnchorsByCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T3', 'T4'],
    format: 'list',
    i18nLabelKey: 'metric.p.links.anchorCloud.topAnchorsByCount.label',
    description: 'Top 20 anchors sorted by count.',
  },
  {
    key: 'p.links.anchorCloud.brandedCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.anchorCloud.brandedCount.label',
    description: 'Count of branded anchor variations.',
  },
  {
    key: 'p.links.anchorCloud.exactMatchCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.anchorCloud.exactMatchCount.label',
    description: 'Count of exact-match anchor variations.',
  },
  {
    key: 'p.links.anchorCloud.partialMatchCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.anchorCloud.partialMatchCount.label',
    description: 'Count of partial-match anchor variations.',
  },
  {
    key: 'p.links.anchorCloud.nakedUrlCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.anchorCloud.nakedUrlCount.label',
    description: 'Count of naked URL anchors.',
  },
  {
    key: 'p.links.toxicBacklinkShare.bucket',
    namespace: 'p.links',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T3', 'T4'],
    format: 'enum',
    i18nLabelKey: 'metric.p.links.toxicBacklinkShare.bucket.label',
    description: 'Toxic backlink share bucket (clean: <2%, low: 2-5%, moderate: 5-15%, high: >15%).',
  },
  {
    key: 'p.links.toxicBacklinkCount',
    namespace: 'p.links',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T4'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.links.toxicBacklinkCount.label',
    description: 'Absolute count of toxic backlinks.',
  },
  // ── EX-Q.6: Comparison Metrics ──
  { key: 'p.links.inlinks.vsPrev30d', namespace: 'p.links', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.links.inlinks.vsPrev30d', description: 'Backlinks change vs previous 30d period' },
  { key: 'p.links.refDomains.vsPrev30d', namespace: 'p.links', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.links.refDomains.vsPrev30d', description: 'Referring domains change vs previous 30d' },
  { key: 'p.links.domainRating.vsPrev30d', namespace: 'p.links', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.links.domainRating.vsPrev30d', description: 'Domain rating change vs previous 30d' },
];
