import type { MetricDef } from '@seesby/types';

export const SEARCH_METRICS: MetricDef[] = [
  // ── GSC (Google Search Console) ──
  {
    key: 'p.search.gsc.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.clicks.label',
    description: 'Total clicks from Google Search in the reporting period.',
  },
  {
    key: 'p.search.gsc.impressions',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.impressions.label',
    description: 'Total impressions in Google Search in the reporting period.',
  },
  {
    key: 'p.search.gsc.ctr',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A', 'T'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.ctr.label',
    description: 'Click-through rate from Google Search results.',
  },
  {
    key: 'p.search.gsc.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A', 'T'],
    sources: ['T0'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.position.label',
    description: 'Average ranking position in Google Search.',
    defaultVisible: true,
  },
  {
    key: 'p.search.gsc.deltaClicks28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'E', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.deltaClicks28d.label',
    description: 'Change in Google Search clicks over the last 28 days.',
  },
  {
    key: 'p.search.gsc.deltaPosition28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'E', 'T'],
    sources: ['T0'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.deltaPosition28d.label',
    description: 'Change in average Google Search position over the last 28 days.',
  },
  {
    key: 'p.search.gsc.isLosing',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.isLosing.label',
    description: 'Whether this page is losing search visibility.',
  },
  {
    key: 'p.search.gsc.isGaining',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.isGaining.label',
    description: 'Whether this page is gaining search visibility.',
  },
  {
    key: 'p.search.gsc.brandedPct',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'S', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.brandedPct.label',
    description: 'Percentage of impressions from branded queries.',
  },

  // ── Bing ──
  {
    key: 'p.search.bing.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireCapability: ['bing'] },
    i18nLabelKey: 'metric.p.search.bing.clicks.label',
    description: 'Total clicks from Bing Search.',
  },
  {
    key: 'p.search.bing.impressions',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireCapability: ['bing'] },
    i18nLabelKey: 'metric.p.search.bing.impressions.label',
    description: 'Total impressions in Bing Search.',
  },
  {
    key: 'p.search.bing.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'T'],
    sources: ['T0'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    gate: { requireCapability: ['bing'] },
    i18nLabelKey: 'metric.p.search.bing.position.label',
    description: 'Average ranking position in Bing Search.',
  },
  {
    key: 'p.search.bing.ctr',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'T'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['bing'] },
    i18nLabelKey: 'metric.p.search.bing.ctr.label',
    description: 'Bing search click-through rate.',
  },
  {
    key: 'p.search.bing.crawlErrors',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireCapability: ['bing'] },
    i18nLabelKey: 'metric.p.search.bing.crawlErrors.label',
    description: 'Number of Bing crawl errors for this page.',
  },

  // ── Primary keyword signals ──
  {
    key: 'p.search.mainKw',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.search.mainKw.label',
    description: 'Primary keyword this page targets.',
  },
  {
    key: 'p.search.mainKwPos',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.mainKwPos.label',
    description: 'Current ranking position for the primary keyword.',
  },
  {
    key: 'p.search.mainKwVolume',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.mainKwVolume.label',
    description: 'Monthly search volume for the primary keyword.',
  },
  {
    key: 'p.search.bestKw',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.search.bestKw.label',
    description: 'Best-performing keyword for this page by traffic.',
  },
  {
    key: 'p.search.bestKwPos',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.bestKwPos.label',
    description: 'Ranking position for the best-performing keyword.',
  },
  {
    key: 'p.search.bestKwVolume',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.bestKwVolume.label',
    description: 'Monthly search volume for the best-performing keyword.',
  },
  {
    key: 'p.search.volumeMethod',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5'],
    format: 'text',
    i18nLabelKey: 'metric.p.search.volumeMethod.label',
    description: 'Method used to estimate keyword search volume.',
  },

  // ── Keyword distribution ──
  {
    key: 'p.search.topKeywords',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'R', 'V'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.topKeywords.label',
    description: 'Top keywords this page ranks for.',
  },
  {
    key: 'p.search.totalKeywords',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.totalKeywords.label',
    description: 'Total number of keywords this page ranks for.',
  },
  {
    key: 'p.search.keywordsTop3',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsTop3.label',
    description: 'Number of keywords ranking in positions 1-3.',
  },
  {
    key: 'p.search.keywordsTop10',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsTop10.label',
    description: 'Number of keywords ranking in positions 1-10.',
  },
  {
    key: 'p.search.keywordsTop20',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'R', 'V'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsTop20.label',
    description: 'Number of keywords ranking in positions 1-20.',
  },
  {
    key: 'p.search.keywordsTop100',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsTop100.label',
    description: 'Number of keywords ranking in positions 1-100.',
  },
  {
    key: 'p.search.keywordsLost28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'E', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsLost28d.label',
    description: 'Number of keywords lost from top 20 in the last 28 days.',
  },
  {
    key: 'p.search.keywordsNew28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.keywordsNew28d.label',
    description: 'Number of new keywords entering top 20 in the last 28 days.',
  },

  // ── SERP features ──
  {
    key: 'p.search.serpFeatures',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T5'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.serpFeatures.label',
    description: 'SERP features present for this page\'s target queries.',
  },
  {
    key: 'p.search.serpFeaturesOwned',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'S', 'A'],
    sources: ['T5'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.serpFeaturesOwned.label',
    description: 'SERP features this page currently owns.',
  },
  {
    key: 'p.search.featuredSnippetOwn',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T5'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.featuredSnippetOwn.label',
    description: 'Whether this page owns the featured snippet for its main keyword.',
  },
  {
    key: 'p.search.peopleAlsoAskOwned',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.peopleAlsoAskOwned.label',
    description: 'Whether this page appears in People Also Ask.',
  },
  {
    key: 'p.search.snippetCannibalized',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.snippetCannibalized.label',
    description: 'Whether another page on this domain captures the snippet instead.',
  },
  {
    key: 'p.search.sitelinksPresent',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.sitelinksPresent.label',
    description: 'Whether sitelinks appear for this page in search results.',
  },
  {
    key: 'p.search.knowledgePanel',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'R', 'S', 'A'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.knowledgePanel.label',
    description: 'Whether a Knowledge Panel is associated with this page or entity.',
  },
  {
    key: 'p.search.brandSERP',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T5'],
    format: 'text',
    i18nLabelKey: 'metric.p.search.brandSERP.label',
    description: 'Description of the brand SERP appearance for this entity.',
  },
  {
    key: 'p.search.entityInKG',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'R', 'S', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.entityInKG.label',
    description: 'Whether the page entity appears in the Google Knowledge Graph.',
  },

  // ── Discover / News ──
  {
    key: 'p.search.discoverImpressions',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.discoverImpressions.label',
    description: 'Number of Google Discover impressions for this page.',
  },
  {
    key: 'p.search.newsImpressions',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.newsImpressions.label',
    description: 'Number of Google News impressions for this page.',
  },

  // ── Trends & updates ──
  {
    key: 'p.search.trendFit',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T1', 'T2', 'T3', 'T4', 'T5'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.search.trendFit.label',
    description: 'How well this page aligns with current search trend trajectory.',
  },
  {
    key: 'p.search.coreUpdateImpact',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T1'],
    format: 'text',
    i18nLabelKey: 'metric.p.search.coreUpdateImpact.label',
    description: 'Impact of the most recent Google core update on this page.',
  },

  // ── Internal search ──
  {
    key: 'p.search.internalSearchTerms',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.internalSearchTerms.label',
    description: 'Top internal search terms used to find this page.',
  },
  // ── Derived search metrics ──
  {
    key: 'p.search.expectedCtr',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.search.expectedCtr.label',
    description: 'Expected click-through rate based on position.',
  },
  {
    key: 'p.search.ctrGap',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.search.ctrGap.label',
    description: 'Gap between actual and expected CTR.',
  },
  {
    key: 'p.search.cannibalized',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.p.search.cannibalized.label',
    description: 'Whether this page is cannibalized by another URL for the same keyword.',
  },
  {
    key: 'p.search.intentMatch',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.p.search.intentMatch.label',
    description: 'Whether the page content matches the search intent.',
  },

  // ── EX-E: Search Expansion ──
  // ── GSC time-window metrics ──
  {
    key: 'p.search.gsc.clicks7d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.clicks7d.label',
    description: 'GSC clicks (7d).',
  },
  {
    key: 'p.search.gsc.impr7d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.impr7d.label',
    description: 'GSC impressions (7d).',
  },
  {
    key: 'p.search.gsc.ctr7d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.ctr7d.label',
    description: 'GSC CTR (7d).',
  },
  {
    key: 'p.search.gsc.position7d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.position7d.label',
    description: 'GSC average position (7d).',
  },
  {
    key: 'p.search.gsc.clicks90d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.clicks90d.label',
    description: 'GSC clicks (90d).',
  },
  {
    key: 'p.search.gsc.impr90d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.impr90d.label',
    description: 'GSC impressions (90d).',
  },
  {
    key: 'p.search.gsc.ctr90d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.ctr90d.label',
    description: 'GSC CTR (90d).',
  },
  {
    key: 'p.search.gsc.position90d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A', 'T'],
    sources: ['T0'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.position90d.label',
    description: 'GSC average position (90d).',
  },
  {
    key: 'p.search.gsc.clicks365d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.clicks365d.label',
    description: 'GSC clicks (365d).',
  },
  {
    key: 'p.search.gsc.impr365d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.impr365d.label',
    description: 'GSC impressions (365d).',
  },

  // ── GSC trend metrics ──
  {
    key: 'p.search.gsc.ctrTrend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.ctrTrend.label',
    description: 'CTR trend time-series (weekly data points).',
  },
  {
    key: 'p.search.gsc.positionTrend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.positionTrend.label',
    description: 'Position trend time-series.',
  },
  {
    key: 'p.search.gsc.clicksTrend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.clicksTrend.label',
    description: 'Clicks trend time-series.',
  },
  {
    key: 'p.search.gsc.imprTrend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.imprTrend.label',
    description: 'Impressions trend time-series.',
  },

  // ── GSC device breakdowns ──
  {
    key: 'p.search.gsc.device.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.device.clicks.label',
    description: 'Clicks breakdown by device (mobile/desktop).',
  },
  {
    key: 'p.search.gsc.device.impr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.device.impr.label',
    description: 'Impressions breakdown by device.',
  },
  {
    key: 'p.search.gsc.device.ctr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.device.ctr.label',
    description: 'CTR breakdown by device.',
  },
  {
    key: 'p.search.gsc.device.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.device.position.label',
    description: 'Position breakdown by device.',
  },

  // ── GSC country breakdowns ──
  {
    key: 'p.search.gsc.country.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.country.clicks.label',
    description: 'Clicks breakdown by country (top 10).',
  },
  {
    key: 'p.search.gsc.country.impr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.country.impr.label',
    description: 'Impressions breakdown by country.',
  },
  {
    key: 'p.search.gsc.country.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.country.position.label',
    description: 'Position breakdown by country.',
  },

  // ── GSC query lists ──
  {
    key: 'p.search.gsc.query.top10',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.top10.label',
    description: 'Top 10 queries by clicks.',
  },
  {
    key: 'p.search.gsc.query.top10impr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.top10impr.label',
    description: 'Top 10 queries by impressions.',
  },
  {
    key: 'p.search.gsc.query.top10position',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.top10position.label',
    description: 'Top 10 queries by best position.',
  },
  {
    key: 'p.search.gsc.query.branded',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.branded.label',
    description: 'Branded queries driving traffic.',
  },
  {
    key: 'p.search.gsc.query.nonBranded',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.label',
    description: 'Non-branded queries driving traffic.',
  },
  {
    key: 'p.search.gsc.query.new28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.new28d.label',
    description: 'New queries appearing in last 28 days.',
  },
  {
    key: 'p.search.gsc.query.lost28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.lost28d.label',
    description: 'Queries lost in last 28 days.',
  },
  {
    key: 'p.search.gsc.query.gaining28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.gaining28d.label',
    description: 'Queries with improving position.',
  },
  {
    key: 'p.search.gsc.query.losing28d',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.gsc.query.losing28d.label',
    description: 'Queries with declining position.',
  },

  // ── CTR bucketing ──
  {
    key: 'p.search.gscCTR.bucket',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.search.gscCTR.bucket.label',
    description: 'CTR bucket relative to position (high: >5%, average: 2-5%, low: 1-2%, very-low: <1%).',
  },
  {
    key: 'p.search.gscCTR.vsExpected',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.gscCTR.vsExpected.label',
    description: 'CTR vs expected CTR for current position.',
  },
  {
    key: 'p.search.gscCTR.optimizable',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.search.gscCTR.optimizable.label',
    description: 'Whether CTR is significantly below expected (optimization opportunity).',
  },

  // ── Keyword bucketing ──
  {
    key: 'p.search.totalKeywords.bucket',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.search.totalKeywords.bucket.label',
    description: 'Keyword count bucket (high: >100, medium: 20-100, low: 5-20, minimal: <5).',
  },
  {
    key: 'p.search.keywordsTop3.bucket',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.search.keywordsTop3.bucket.label',
    description: 'Top-3 keyword count bucket (high: >10, medium: 3-10, low: 1-3, none: 0).',
  },
  {
    key: 'p.search.keywordsTop10.bucket',
    namespace: 'p.search',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.search.keywordsTop10.bucket.label',
    description: 'Top-10 keyword count bucket (high: >20, medium: 5-20, low: 1-5, none: 0).',
  },

  // ── SERP feature counts ──
  {
    key: 'p.search.serpFeatures.count',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.serpFeatures.count.label',
    description: 'Total SERP features present on this SERP.',
  },
  {
    key: 'p.search.serpFeatures.owned.count',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.serpFeatures.owned.count.label',
    description: 'Count of SERP features this page owns.',
  },
  {
    key: 'p.search.featuredSnippet.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.featuredSnippet.position.label',
    description: 'Position within featured snippet (if present).',
  },
  {
    key: 'p.search.peopleAlsoAsk.count',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.peopleAlsoAsk.count.label',
    description: 'Total PAA questions on this SERP.',
  },
  {
    key: 'p.search.peopleAlsoAsk.ourAnswers',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.peopleAlsoAsk.ourAnswers.label',
    description: 'PAA questions where we appear.',
  },
  {
    key: 'p.search.knowledgePanel.position',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T5'],
    unit: 'rank',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.knowledgePanel.position.label',
    description: 'Position of our entity in knowledge panel.',
  },

  // ── Discover / News expansion ──
  {
    key: 'p.search.discover.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.discover.clicks.label',
    description: 'Google Discover clicks.',
  },
  {
    key: 'p.search.discover.ctr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.discover.ctr.label',
    description: 'Google Discover CTR.',
  },
  {
    key: 'p.search.discover.trend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.discover.trend.label',
    description: 'Google Discover trend time-series.',
  },
  {
    key: 'p.search.news.clicks',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.news.clicks.label',
    description: 'Google News clicks.',
  },
  {
    key: 'p.search.news.ctr',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.news.ctr.label',
    description: 'Google News CTR.',
  },
  {
    key: 'p.search.news.trend',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    gate: { requireConnected: ['gsc'] },
    i18nLabelKey: 'metric.p.search.news.trend.label',
    description: 'Google News trend time-series.',
  },

  // ── Trend fit expansion ──
  {
    key: 'p.search.trendFit.score',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T3'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.search.trendFit.score.label',
    description: 'Trend fit score (0-1, how well page matches rising trends).',
  },
  {
    key: 'p.search.trendFit.topics',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.trendFit.topics.label',
    description: 'Related rising topics.',
  },

  // ── Internal search expansion ──
  {
    key: 'p.search.internalSearch.terms.count',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.search.internalSearch.terms.count.label',
    description: 'Number of internal search terms leading here.',
  },
  {
    key: 'p.search.internalSearch.terms.top',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.search.internalSearch.terms.top.label',
    description: 'Top internal search terms.',
  },
  {
    key: 'p.search.internalSearch.satisfaction',
    namespace: 'p.search',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T7'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.search.internalSearch.satisfaction.label',
    description: 'Internal search satisfaction score (did users find what they wanted?).',
  },
  // ── EX-Q.5: More Per-Metric Detail ──
  { key: 'p.search.gsc.query.all', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.search.gsc.query.all', description: 'All queries for this page (full list)' },
  { key: 'p.search.gsc.device.all', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.p.search.gsc.device.all', description: 'Full device breakdown: {mobile: {clicks, impr, ctr, pos}, desktop: {...}, tablet: {...}}' },
  { key: 'p.search.gsc.country.all', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.p.search.gsc.country.all', description: 'Full country breakdown (all countries)' },
  { key: 'p.search.gsc.query.branded.count', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.branded.count', description: 'Count of branded queries' },
  { key: 'p.search.gsc.query.nonBranded.count', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.count', description: 'Count of non-branded queries' },
  { key: 'p.search.gsc.query.branded.clicks', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.branded.clicks', description: 'Clicks from branded queries' },
  { key: 'p.search.gsc.query.nonBranded.clicks', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.clicks', description: 'Clicks from non-branded queries' },
  { key: 'p.search.gsc.query.branded.share', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.query.branded.share', description: 'Branded query click share' },
  { key: 'p.search.gsc.query.nonBranded.share', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.share', description: 'Non-branded query click share' },
  { key: 'p.search.gsc.query.branded.position', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.branded.position', description: 'Average branded query position' },
  { key: 'p.search.gsc.query.nonBranded.position', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.position', description: 'Average non-branded query position' },
  { key: 'p.search.gsc.query.branded.ctr', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.query.branded.ctr', description: 'Branded query CTR' },
  { key: 'p.search.gsc.query.nonBranded.ctr', namespace: 'p.search', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.query.nonBranded.ctr', description: 'Non-branded query CTR' },
  { key: 'p.search.gsc.device.clicksMobile', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.clicksMobile', description: 'Mobile clicks (28d)' },
  { key: 'p.search.gsc.device.clicksDesktop', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.clicksDesktop', description: 'Desktop clicks (28d)' },
  { key: 'p.search.gsc.device.imprMobile', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.imprMobile', description: 'Mobile impressions (28d)' },
  { key: 'p.search.gsc.device.imprDesktop', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.imprDesktop', description: 'Desktop impressions (28d)' },
  { key: 'p.search.gsc.device.ctrMobile', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.device.ctrMobile', description: 'Mobile CTR (28d)' },
  { key: 'p.search.gsc.device.ctrDesktop', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.device.ctrDesktop', description: 'Desktop CTR (28d)' },
  { key: 'p.search.gsc.device.posMobile', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.posMobile', description: 'Mobile average position (28d)' },
  { key: 'p.search.gsc.device.posDesktop', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.device.posDesktop', description: 'Desktop average position (28d)' },
  { key: 'p.search.gsc.country.clicksTop1', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.country.clicksTop1', description: 'Clicks from top country' },
  { key: 'p.search.gsc.country.imprTop1', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.country.imprTop1', description: 'Impressions from top country' },
  { key: 'p.search.gsc.country.posTop1', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.country.posTop1', description: 'Position in top country' },
  { key: 'p.search.gsc.country.ctrTop1', namespace: 'p.search', level: 'P', roles: ['I', 'V'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.country.ctrTop1', description: 'CTR in top country' },
  // ── EX-Q.6: Comparison Metrics ──
  { key: 'p.search.gsc.clicks.vsPrev7d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.clicks.vsPrev7d', description: 'Clicks change vs previous 7d period' },
  { key: 'p.search.gsc.clicks.vsPrev28d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.clicks.vsPrev28d', description: 'Clicks change vs previous 28d period' },
  { key: 'p.search.gsc.impr.vsPrev7d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.impr.vsPrev7d', description: 'Impressions change vs previous 7d period' },
  { key: 'p.search.gsc.impr.vsPrev28d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.impr.vsPrev28d', description: 'Impressions change vs previous 28d period' },
  { key: 'p.search.gsc.position.vsPrev7d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.position.vsPrev7d', description: 'Position change vs previous 7d period' },
  { key: 'p.search.gsc.position.vsPrev28d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.position.vsPrev28d', description: 'Position change vs previous 28d period' },
  { key: 'p.search.gsc.ctr.vsPrev7d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.ctr.vsPrev7d', description: 'CTR change vs previous 7d period' },
  { key: 'p.search.gsc.ctr.vsPrev28d', namespace: 'p.search', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.ctr.vsPrev28d', description: 'CTR change vs previous 28d period' },
  // ── EX-Q.6: Additional Detail Metrics ──
  { key: 'p.search.gsc.query.top1.url', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.p.search.gsc.query.top1.url', description: 'URL ranking for top query' },
  { key: 'p.search.gsc.query.top1.position', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.top1.position', description: 'Position for top query' },
  { key: 'p.search.gsc.query.top1.clicks', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.top1.clicks', description: 'Clicks from top query' },
  { key: 'p.search.gsc.query.top1.impr', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.top1.impr', description: 'Impressions from top query' },
  { key: 'p.search.gsc.query.top1.ctr', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'percent', i18nLabelKey: 'metric.p.search.gsc.query.top1.ctr', description: 'CTR from top query' },
  { key: 'p.search.gsc.query.top2.url', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.p.search.gsc.query.top2.url', description: 'URL ranking for second query' },
  { key: 'p.search.gsc.query.top2.position', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.top2.position', description: 'Position for second query' },
  { key: 'p.search.gsc.query.top3.url', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.p.search.gsc.query.top3.url', description: 'URL ranking for third query' },
  { key: 'p.search.gsc.query.top3.position', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.gsc.query.top3.position', description: 'Position for third query' },
  { key: 'p.search.gsc.query.top10.all', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.search.gsc.query.top10.all', description: 'All top 10 queries with full metrics' },
  // ── EX-Q.7: Final 35 metrics ──
  { key: 'p.search.gsc.query.all.branded', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.search.gsc.query.all.branded', description: 'All branded queries for this page' },
  { key: 'p.search.gsc.query.all.nonBranded', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.search.gsc.query.all.nonBranded', description: 'All non-branded queries for this page' },
  { key: 'p.search.gsc.query.all.byPosition', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.p.search.gsc.query.all.byPosition', description: 'All queries grouped by position bucket' },
  { key: 'p.search.gsc.query.all.byVolume', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T3'], format: 'json', i18nLabelKey: 'metric.p.search.gsc.query.all.byVolume', description: 'All queries grouped by volume bucket' },
  { key: 'p.search.gsc.query.all.byIntent', namespace: 'p.search', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'json', i18nLabelKey: 'metric.p.search.gsc.query.all.byIntent', description: 'All queries grouped by search intent' },
  // ── EX-R: Regional Search Engines ──
  { key: 'p.search.yandex.clicks', namespace: 'p.search.yandex', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.yandex.clicks', description: 'Yandex clicks (28d)' },
  { key: 'p.search.yandex.impr', namespace: 'p.search.yandex', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.yandex.impr', description: 'Yandex impressions (28d)' },
  { key: 'p.search.yandex.position', namespace: 'p.search.yandex', level: 'P', roles: ['G', 'I', 'V', 'T'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.yandex.position', description: 'Average Yandex position' },
  { key: 'p.search.baidu.clicks', namespace: 'p.search.baidu', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.baidu.clicks', description: 'Baidu clicks (28d)' },
  { key: 'p.search.baidu.impr', namespace: 'p.search.baidu', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.baidu.impr', description: 'Baidu impressions (28d)' },
  { key: 'p.search.baidu.position', namespace: 'p.search.baidu', level: 'P', roles: ['G', 'I', 'V', 'T'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.baidu.position', description: 'Average Baidu position' },
  { key: 'p.search.naver.clicks', namespace: 'p.search.naver', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.naver.clicks', description: 'Naver clicks (28d)' },
  { key: 'p.search.naver.impr', namespace: 'p.search.naver', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.naver.impr', description: 'Naver impressions (28d)' },
  { key: 'p.search.naver.position', namespace: 'p.search.naver', level: 'P', roles: ['G', 'I', 'V', 'T'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.naver.position', description: 'Average Naver position' },
  { key: 'p.search.seznam.clicks', namespace: 'p.search.seznam', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.seznam.clicks', description: 'Seznam clicks (28d)' },
  { key: 'p.search.seznam.impr', namespace: 'p.search.seznam', level: 'P', roles: ['G', 'I', 'R', 'V', 'T'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.seznam.impr', description: 'Seznam impressions (28d)' },
  { key: 'p.search.seznam.position', namespace: 'p.search.seznam', level: 'P', roles: ['G', 'I', 'V', 'T'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.p.search.seznam.position', description: 'Average Seznam position' },
  { key: 'p.search.duck.clicks', namespace: 'p.search.duck', level: 'P', roles: ['I', 'V', 'T'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.duck.clicks', description: 'Estimated DuckDuckGo clicks (inferred from referrer data)' },
  { key: 'p.search.duck.impr', namespace: 'p.search.duck', level: 'P', roles: ['I', 'V', 'T'], sources: ['T5'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.search.duck.impr', description: 'Estimated DuckDuckGo impressions (from SERP scrape)' },
  { key: 'p.search.duck.position', namespace: 'p.search.duck', level: 'P', roles: ['I', 'V', 'T'], sources: ['T5'], format: 'number', i18nLabelKey: 'metric.p.search.duck.position', description: 'Average DuckDuckGo position (from SERP scrape)' },
];
