import type { MetricDef } from '@seesby/types';

export const linkMetrics: MetricDef[] = [
  {
    key: 'l.source',
    namespace: 'l',
    level: 'L',
    roles: ['X', 'I'],
    sources: ['T0'],
    format: 'url',
    width: '200px',
    i18nLabelKey: 'metric.l.source',
    description: 'Source (referring) URL.',
  },
  {
    key: 'l.target',
    namespace: 'l',
    level: 'L',
    roles: ['X', 'I'],
    sources: ['T0'],
    format: 'url',
    width: '200px',
    i18nLabelKey: 'metric.l.target',
    description: 'Target (destination) URL.',
  },
  {
    key: 'l.anchor',
    namespace: 'l',
    level: 'L',
    roles: ['X', 'I'],
    sources: ['T0'],
    format: 'text',
    width: '120px',
    i18nLabelKey: 'metric.l.anchor',
    description: 'Anchor text of the link.',
  },
  {
    key: 'l.anchorLen',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    unit: 'chars',
    i18nLabelKey: 'metric.l.anchorLen',
    description: 'Character length of the anchor text.',
  },
  {
    key: 'l.contextSnippet',
    namespace: 'l',
    level: 'L',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    width: '200px',
    i18nLabelKey: 'metric.l.contextSnippet',
    description: 'Surrounding text context of the link.',
  },
  {
    key: 'l.rel',
    namespace: 'l',
    level: 'L',
    roles: ['X', 'I'],
    sources: ['T0'],
    format: 'text',
    width: '100px',
    i18nLabelKey: 'metric.l.rel',
    description: 'Rel attribute value.',
  },
  {
    key: 'l.isFollow',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.l.isFollow',
    description: 'Whether the link passes link equity (follow).',
  },
  {
    key: 'l.isNav',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.l.isNav',
    description: 'Whether the link is in a navigation element.',
  },
  {
    key: 'l.isFooter',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.l.isFooter',
    description: 'Whether the link is in the page footer.',
  },
  {
    key: 'l.isContentBody',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'boolean',
    width: '80px',
    i18nLabelKey: 'metric.l.isContentBody',
    description: 'Whether the link is within the main content body.',
  },
  {
    key: 'l.firstSeen',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'date',
    width: '100px',
    i18nLabelKey: 'metric.l.firstSeen',
    description: 'Date the link was first discovered.',
  },
  {
    key: 'l.lastSeen',
    namespace: 'l',
    level: 'L',
    roles: ['X'],
    sources: ['T0'],
    format: 'date',
    width: '100px',
    i18nLabelKey: 'metric.l.lastSeen',
    description: 'Date the link was most recently confirmed.',
  },
];
