import type { MetricDef } from '@seesby/types';

/**
 * Cluster-level (K) metric definitions.
 * Each cluster groups pages by topic/section affinity.
 */

export const clusterMetrics: MetricDef[] = [
  {
    key: 'k.clusterId',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'L', 'V', 'X'],
    sources: ['T6'],
    format: 'text',
    width: '120px',
    i18nLabelKey: 'metric.k.clusterId',
    description: 'Unique cluster identifier.',
  },
  {
    key: 'k.name',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V'],
    sources: ['T6'],
    format: 'text',
    width: '160px',
    i18nLabelKey: 'metric.k.name',
    description: 'Human-readable cluster name (AI-generated from topic).',
  },
  {
    key: 'k.pageCount',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V', 'K'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.pageCount',
    description: 'Number of pages in this cluster.',
  },
  {
    key: 'k.totalSessions',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '100px',
    unit: 'count',
    i18nLabelKey: 'metric.k.totalSessions',
    description: 'Sum of GA4 sessions across cluster pages.',
  },
  {
    key: 'k.totalClicks',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V', 'S'],
    sources: ['T0'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.totalClicks',
    description: 'Sum of GSC clicks across cluster pages.',
  },
  {
    key: 'k.avgWordCount',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'words',
    i18nLabelKey: 'metric.k.avgWordCount',
    description: 'Average word count across cluster pages.',
  },
  {
    key: 'k.avgReadability',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T7'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.k.avgReadability',
    description: 'Average readability score across cluster pages.',
  },
  {
    key: 'k.avgCwvBucket',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T1'],
    format: 'enum',
    width: '80px',
    i18nLabelKey: 'metric.k.avgCwvBucket',
    description: 'Most common CWV bucket across cluster pages.',
  },
  {
    key: 'k.coverage',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'percent',
    width: '80px',
    i18nLabelKey: 'metric.k.coverage',
    description: 'Topic coverage score (how well cluster covers the topic vs SERP).',
  },
  {
    key: 'k.depth',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'A'],
    sources: ['T6'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.k.depth',
    description: 'Content depth score (comprehensiveness of cluster coverage).',
  },
  {
    key: 'k.cannibalization',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V', 'A', 'E'],
    sources: ['T0', 'T6'],
    format: 'boolean',
    width: '80px',
    i18nLabelKey: 'metric.k.cannibalization',
    description: 'Whether pages in this cluster cannibalize each other.',
  },
  {
    key: 'k.gapKeywords',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'A'],
    sources: ['T6'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.gapKeywords',
    description: 'Number of high-value keywords the cluster is missing.',
  },
  {
    key: 'k.centerUrl',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'X'],
    sources: ['T4'],
    format: 'url',
    width: '200px',
    i18nLabelKey: 'metric.k.centerUrl',
    description: 'The most representative URL in the cluster.',
  },
  {
    key: 'k.topKeywords',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V'],
    sources: ['T0', 'T5'],
    format: 'json',
    i18nLabelKey: 'metric.k.topKeywords',
    description: 'Top keywords driving traffic to this cluster.',
  },
  {
    key: 'k.internalLinksIn',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.internalLinksIn',
    description: 'Total internal links pointing into this cluster.',
  },
  {
    key: 'k.internalLinksOut',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.internalLinksOut',
    description: 'Total internal links from this cluster to other clusters.',
  },
  {
    key: 'k.score',
    namespace: 'k',
    level: 'K',
    roles: ['H', 'R', 'K', 'T'],
    sources: ['T4', 'T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score',
    description: 'Composite cluster quality score (0-100).',
    scoreComponent: 'content',
  },
  {
    key: 'k.revenue',
    namespace: 'k',
    level: 'K',
    roles: ['G', 'I', 'R', 'V', 'K', 'S'],
    sources: ['T0'],
    format: 'money',
    width: '100px',
    unit: 'usd',
    i18nLabelKey: 'metric.k.revenue',
    description: 'Total GA4 revenue attributed to this cluster.',
  },
  {
    key: 'k.freshness',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'A'],
    sources: ['T4'],
    format: 'enum',
    width: '80px',
    i18nLabelKey: 'metric.k.freshness',
    description: 'Cluster freshness class (live/recent/fresh/ok/stale).',
  },
  {
    key: 'k.actionCount',
    namespace: 'k',
    level: 'K',
    roles: ['I', 'R', 'V', 'K'],
    sources: ['T6'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.actionCount',
    description: 'Number of triggered actions across cluster pages.',
  },

  // ─── EX-Q.1: Cluster-Level Expansion (additional) ──────────────────
  {
    key: 'k.totalImpr',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'number',
    width: '100px',
    unit: 'count',
    i18nLabelKey: 'metric.k.totalImpr',
    description: 'Total GSC impressions for cluster (28d).',
  },
  {
    key: 'k.avgCtr',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'percent',
    width: '80px',
    i18nLabelKey: 'metric.k.avgCtr',
    description: 'Average CTR across cluster pages.',
  },
  {
    key: 'k.avgPosition',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.k.avgPosition',
    description: 'Average ranking position across cluster.',
  },
  {
    key: 'k.totalRevenue',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'money',
    width: '100px',
    unit: 'usd',
    i18nLabelKey: 'metric.k.totalRevenue',
    description: 'Total revenue from cluster (28d).',
  },
  {
    key: 'k.avgCvr',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'percent',
    width: '80px',
    i18nLabelKey: 'metric.k.avgCvr',
    description: 'Average conversion rate across cluster.',
  },
  {
    key: 'k.totalKeywords',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.totalKeywords',
    description: 'Total ranking keywords for cluster.',
  },
  {
    key: 'k.keywordsTop10',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T0'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.keywordsTop10',
    description: 'Keywords in top 10 for cluster.',
  },
  {
    key: 'k.avgFreshness',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.k.avgFreshness',
    description: 'Average days since last update.',
  },
  {
    key: 'k.avgInlinks',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.k.avgInlinks',
    description: 'Average internal inlinks per page.',
  },
  {
    key: 'k.avgPagerank',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T4'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.k.avgPagerank',
    description: 'Average internal PageRank.',
  },
  {
    key: 'k.totalRefDomains',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.totalRefDomains',
    description: 'Total referring domains to cluster pages.',
  },
  {
    key: 'k.orphanCount',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.orphanCount',
    description: 'Orphan pages in cluster.',
  },
  {
    key: 'k.cannibalizedCount',
    namespace: 'k',
    level: 'K',
    roles: ['R', 'A', 'E'],
    sources: ['T0', 'T6'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.cannibalizedCount',
    description: 'Pages involved in cannibalization within cluster.',
  },
  {
    key: 'k.coverage.score',
    namespace: 'k.coverage',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T6'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.k.coverage.score',
    description: 'Topic coverage score (how thoroughly cluster covers the topic).',
  },
  {
    key: 'k.coverage.gaps',
    namespace: 'k.coverage',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.k.coverage.gaps',
    description: 'Sub-topics not covered in cluster.',
  },
  {
    key: 'k.coverage.depth',
    namespace: 'k.coverage',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T6'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.k.coverage.depth',
    description: 'Average topic depth across cluster.',
  },
  {
    key: 'k.score.content',
    namespace: 'k.score',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score.content',
    description: 'Cluster content quality score.',
    scoreComponent: 'content',
  },
  {
    key: 'k.score.search',
    namespace: 'k.score',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score.search',
    description: 'Cluster search performance score.',
  },
  {
    key: 'k.score.tech',
    namespace: 'k.score',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score.tech',
    description: 'Cluster technical health score.',
    scoreComponent: 'tech',
  },
  {
    key: 'k.score.links',
    namespace: 'k.score',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score.links',
    description: 'Cluster link authority score.',
    scoreComponent: 'links',
  },
  {
    key: 'k.score.overall',
    namespace: 'k.score',
    level: 'K',
    roles: ['R', 'K'],
    sources: ['T6'],
    format: 'score',
    width: '60px',
    i18nLabelKey: 'metric.k.score.overall',
    description: 'Cluster overall quality score.',
  },
  {
    key: 'k.intent.primary',
    namespace: 'k.intent',
    level: 'K',
    roles: ['R', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.k.intent.primary',
    description: 'Primary search intent for cluster.',
  },
  {
    key: 'k.intent.funnel',
    namespace: 'k.intent',
    level: 'K',
    roles: ['R', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.k.intent.funnel',
    description: 'Primary funnel stage for cluster.',
  },
  {
    key: 'k.trend.clicks',
    namespace: 'k.trend',
    level: 'K',
    roles: ['R', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.k.trend.clicks',
    description: 'Cluster clicks trend time-series.',
  },
  {
    key: 'k.trend.sessions',
    namespace: 'k.trend',
    level: 'K',
    roles: ['R', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.k.trend.sessions',
    description: 'Cluster sessions trend.',
  },
  {
    key: 'k.trend.revenue',
    namespace: 'k.trend',
    level: 'K',
    roles: ['R', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.k.trend.revenue',
    description: 'Cluster revenue trend.',
  },
  {
    key: 'k.trend.keywords',
    namespace: 'k.trend',
    level: 'K',
    roles: ['R', 'V', 'T'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.k.trend.keywords',
    description: 'Cluster keyword count trend.',
  },
  {
    key: 'k.internalLinks.inbound',
    namespace: 'k.internalLinks',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.internalLinks.inbound',
    description: 'Internal links from outside the cluster.',
  },
  {
    key: 'k.internalLinks.internal',
    namespace: 'k.internalLinks',
    level: 'K',
    roles: ['R', 'A'],
    sources: ['T4'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.k.internalLinks.internal',
    description: 'Internal links within the cluster.',
  },
];
