import type { MetricDef } from '@seesby/types';

export const CONTENT_METRICS: MetricDef[] = [
  {
    key: 'p.content.title',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.title',
    description: 'Page title text.',
  },
  {
    key: 'p.content.titleLength',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'S'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.titleLength',
    description: 'Character length of the page title.',
  },
  {
    key: 'p.content.titlePixelWidth',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'px',
    format: 'number',
    i18nLabelKey: 'metric.p.content.titlePixelWidth',
    description: 'Pixel width of the rendered page title.',
  },
  {
    key: 'p.content.metaDesc',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.metaDesc',
    description: 'Meta description text.',
  },
  {
    key: 'p.content.metaDescLength',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.metaDescLength',
    description: 'Character length of the meta description.',
  },
  {
    key: 'p.content.metaDescPixel',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'px',
    format: 'number',
    i18nLabelKey: 'metric.p.content.metaDescPixel',
    description: 'Pixel width of the rendered meta description.',
  },
  {
    key: 'p.content.h1Text',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.h1Text',
    description: 'Text content of the primary H1 heading.',
  },
  {
    key: 'p.content.h1Count',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.h1Count',
    description: 'Number of H1 tags on the page.',
  },
  {
    key: 'p.content.hTree',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.hTree',
    description: 'Full heading hierarchy tree.',
  },
  {
    key: 'p.content.hOrderValid',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.hOrderValid',
    description: 'Whether heading levels follow a valid order.',
  },
  {
    key: 'p.content.wordCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'L', 'S', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.wordCount',
    description: 'Total visible word count on the page.',
    scoreComponent: 'content',
    defaultVisible: true,
  },
  {
    key: 'p.content.sentenceCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.sentenceCount',
    description: 'Total sentence count.',
  },
  {
    key: 'p.content.paragraphCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.paragraphCount',
    description: 'Total paragraph count.',
  },
  {
    key: 'p.content.readabilityFlesch',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T0', 'T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.readabilityFlesch',
    description: 'Flesch reading ease score.',
  },
  {
    key: 'p.content.readabilityGradeLevel',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'S', 'A'],
    sources: ['T0', 'T7'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.readabilityGradeLevel',
    description: 'Flesch-Kincaid grade level.',
  },
  {
    key: 'p.content.readabilityModel',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.readabilityModel',
    description: 'Name of the readability algorithm used.',
  },
  {
    key: 'p.content.readabilityLang',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.readabilityLang',
    description: 'Language used for readability analysis.',
  },
  {
    key: 'p.content.textRatio',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.textRatio',
    description: 'Ratio of visible text to total page size.',
  },
  {
    key: 'p.content.hash',
    namespace: 'p.content',
    level: 'P',
    roles: ['X', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.hash',
    description: 'Content hash for duplicate detection.',
  },
  {
    key: 'p.content.duplicateExact',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.duplicateExact',
    description: 'Whether an exact duplicate page exists.',
  },
  {
    key: 'p.content.duplicateCluster',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.duplicateCluster',
    description: 'Identifier of the duplicate cluster this page belongs to.',
  },
  {
    key: 'p.content.duplicateNearMatch',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.duplicateNearMatch',
    description: 'List of near-duplicate page URLs.',
  },
  {
    key: 'p.content.duplicateRatio',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.duplicateRatio',
    description: 'Percentage of duplicate content across the site.',
  },
  {
    key: 'p.content.semanticSimilarity',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T0'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.semanticSimilarity',
    description: 'Semantic similarity score vs. target keyword intent.',
  },
  {
    key: 'p.content.cannibalization',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.cannibalization',
    description: 'Whether this page cannibalizes another for the same keywords.',
  },
  {
    key: 'p.content.cannibalPartners',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.cannibalPartners',
    description: 'List of URLs cannibalizing the same keywords.',
  },
  {
    key: 'p.content.spellingErrors',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T6'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.spellingErrors',
    description: 'Number of spelling errors detected.',
  },
  {
    key: 'p.content.grammarErrors',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T6'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.grammarErrors',
    description: 'Number of grammar errors detected.',
  },
  {
    key: 'p.content.hasLoremIpsum',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.hasLoremIpsum',
    description: 'Whether placeholder lorem ipsum text is present.',
  },
  {
    key: 'p.content.visibleDate',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.visibleDate',
    description: 'Publication date shown to users on the page.',
  },
  {
    key: 'p.content.lastModifiedHttp',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.lastModifiedHttp',
    description: 'Last-Modified header value.',
  },
  {
    key: 'p.content.lastModifiedDetected',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T6'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.lastModifiedDetected',
    description: 'Most recent modification date detected in content.',
  },
  {
    key: 'p.content.freshnessDays',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A', 'S'],
    sources: ['T0'],
    unit: 'days',
    format: 'number',
    i18nLabelKey: 'metric.p.content.freshnessDays',
    description: 'Days since last content update.',
    defaultVisible: true,
    gate: { industries: ['news', 'blog'] },
  },
  {
    key: 'p.content.freshnessClass',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'L', 'V'],
    sources: ['T0'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.freshnessClass',
    description: 'Content freshness classification.',
  },
  {
    key: 'p.content.contentDecay',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.contentDecay',
    description: 'Whether the content is showing signs of decay.',
  },
  {
    key: 'p.content.decayStart',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.decayStart',
    description: 'Date when content decay was first detected.',
  },
  {
    key: 'p.content.decayVelocity',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.decayVelocity',
    description: 'Rate of content decay over time.',
  },
  {
    key: 'p.content.aiGeneratedProb',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T6'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.aiGeneratedProb',
    description: 'Probability that the content is AI-generated.',
  },
  {
    key: 'p.content.humanSignals',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'A', 'S'],
    sources: ['T0', 'T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.humanSignals',
    description: 'Score of human-authorship signals found.',
  },
  {
    key: 'p.content.author',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.author',
    description: 'Named author of the page content.',
  },
  {
    key: 'p.content.authorIsLinked',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.authorIsLinked',
    description: 'Whether the author name links to an author page.',
  },
  {
    key: 'p.content.authorBioPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.authorBioPresent',
    description: 'Whether an author biography is present.',
  },
  {
    key: 'p.content.authorCredential',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.authorCredential',
    description: 'Whether author credentials or expertise are shown.',
  },
  {
    key: 'p.content.reviewer',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.reviewer',
    description: 'Name of the content reviewer.',
  },
  {
    key: 'p.content.editorialPolicyLink',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.content.editorialPolicyLink',
    description: 'URL of the editorial policy page.',
  },
  {
    key: 'p.content.eeatScore',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeatScore',
    description: 'Overall E-E-A-T score.',
    scoreComponent: 'content',
    defaultVisible: true,
  },
  {
    key: 'p.content.eeatExperience',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeatExperience',
    description: 'Experience component of E-E-A-T.',
  },
  {
    key: 'p.content.eeatExpertise',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeatExpertise',
    description: 'Expertise component of E-E-A-T.',
  },
  {
    key: 'p.content.eeatAuthoritativeness',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeatAuthoritativeness',
    description: 'Authoritativeness component of E-E-A-T.',
  },
  {
    key: 'p.content.eeatTrust',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeatTrust',
    description: 'Trust component of E-E-A-T.',
  },
  {
    key: 'p.content.ogTitle',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.ogTitle',
    description: 'Open Graph title tag content.',
  },
  {
    key: 'p.content.ogDescription',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.ogDescription',
    description: 'Open Graph description tag content.',
  },
  {
    key: 'p.content.ogImage',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X', 'A', 'E'],
    sources: ['T0'],
    format: 'url',
    i18nLabelKey: 'metric.p.content.ogImage',
    description: 'Open Graph image URL.',
  },
  {
    key: 'p.content.ogImageRatio',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.ogImageRatio',
    description: 'Aspect ratio of the Open Graph image.',
  },
  {
    key: 'p.content.ogImageBytes',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.content.ogImageBytes',
    description: 'File size of the Open Graph image.',
  },
  {
    key: 'p.content.ogType',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.ogType',
    description: 'Open Graph type (article, product, etc.).',
  },
  {
    key: 'p.content.twitterCard',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.twitterCard',
    description: 'Twitter card type.',
  },
  {
    key: 'p.content.twitterCreator',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.twitterCreator',
    description: 'Twitter creator handle.',
  },
  {
    key: 'p.content.socialLinks',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.socialLinks',
    description: 'List of social media links on the page.',
  },
  {
    key: 'p.content.schemaTypes',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.schemaTypes',
    description: 'List of structured data types found.',
  },
  {
    key: 'p.content.schemaErrors',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.schemaErrors',
    description: 'Number of schema validation errors.',
  },
  {
    key: 'p.content.schemaWarnings',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.schemaWarnings',
    description: 'Number of schema validation warnings.',
  },
  {
    key: 'p.content.schemaRichResultEligible',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.schemaRichResultEligible',
    description: 'Whether the schema qualifies for a rich result.',
  },
  {
    key: 'p.content.schemaCoverage',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'R', 'S', 'A'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.schemaCoverage',
    description: 'Percentage of recommended schema properties present.',
  },
  {
    key: 'p.content.schemaMissing',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.schemaMissing',
    description: 'List of recommended but missing schema properties.',
  },
  {
    key: 'p.content.schemaDeprecated',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.schemaDeprecated',
    description: 'List of deprecated schema properties used.',
  },
  {
    key: 'p.content.schemaValidatorLog',
    namespace: 'p.content',
    level: 'P',
    roles: ['X'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.schemaValidatorLog',
    description: 'Full schema validator log output.',
  },
  {
    key: 'p.content.breadcrumbPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.breadcrumbPresent',
    description: 'Whether breadcrumb navigation is present.',
  },
  {
    key: 'p.content.breadcrumbValid',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.breadcrumbValid',
    description: 'Whether breadcrumb structured data is valid.',
  },
  {
    key: 'p.content.topicCluster',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V', 'L', 'A'],
    sources: ['T6'],
    format: 'text',
    defaultVisible: true,
    gate: { industries: ['news', 'blog'] },
    i18nLabelKey: 'metric.p.content.topicCluster',
    description: 'AI-assigned topic cluster for the page.',
  },
  {
    key: 'p.content.topicCoverage',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topicCoverage',
    description: 'Score of topic coverage depth.',
  },
  {
    key: 'p.content.topicDepth',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T6'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.topicDepth',
    description: 'Number of subtopics covered.',
  },
  {
    key: 'p.content.entitiesList',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.entitiesList',
    description: 'List of named entities extracted from the content.',
  },
  {
    key: 'p.content.entitiesCoverage',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.entitiesCoverage',
    description: 'Percentage of expected entities covered.',
  },
  {
    key: 'p.content.entitiesSalience',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.entitiesSalience',
    description: 'Average salience score of top entities.',
  },
  {
    key: 'p.content.intentSearch',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.intentSearch',
    description: 'Search intent classification.',
  },
  {
    key: 'p.content.intentFunnel',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.intentFunnel',
    description: 'Funnel stage: TOFU, MOFU, BOFU, or retention.',
  },
  {
    key: 'p.content.intentMatch',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.intentMatch',
    description: 'Score of how well the page matches search intent.',
  },
  {
    key: 'p.content.questionsList',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.questionsList',
    description: 'List of questions addressed on the page.',
  },
  {
    key: 'p.content.answerBoxFit',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.answerBoxFit',
    description: 'Score of featured snippet / answer box fitness.',
  },
  {
    key: 'p.content.definitionFit',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.definitionFit',
    description: 'Score of definition snippet fitness.',
  },
  {
    key: 'p.content.qaStructureFit',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.qaStructureFit',
    description: 'Score of Q&A structured data fitness.',
  },
  {
    key: 'p.content.passageFitness',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.passageFitness',
    description: 'Score of passage indexing fitness.',
  },
  {
    key: 'p.content.speakableScore',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'S'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.speakableScore',
    description: 'Score of speakable schema eligibility.',
  },
  {
    key: 'p.content.listStructurePresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.listStructurePresent',
    description: 'Whether ordered or unordered lists are used.',
  },
  {
    key: 'p.content.tableStructurePresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.tableStructurePresent',
    description: 'Whether HTML tables are used.',
  },
  {
    key: 'p.content.imagesTotal',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesTotal',
    description: 'Total number of images on the page.',
  },
  {
    key: 'p.content.imagesMissingAlt',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesMissingAlt',
    description: 'Number of images missing alt attributes.',
  },
  {
    key: 'p.content.imagesLongAlt',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesLongAlt',
    description: 'Number of images with excessively long alt text.',
  },
  {
    key: 'p.content.imagesEmptyAlt',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesEmptyAlt',
    description: 'Number of images with empty alt attributes.',
  },
  {
    key: 'p.content.imagesDuplicateAlt',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesDuplicateAlt',
    description: 'Number of images sharing duplicate alt text.',
  },
  {
    key: 'p.content.imagesLegacyFmt',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesLegacyFmt',
    description: 'Number of images in legacy formats (PNG, JPEG, GIF).',
  },
  {
    key: 'p.content.imagesModernFmt',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesModernFmt',
    description: 'Number of images in modern formats (WebP, AVIF).',
  },
  {
    key: 'p.content.imagesNoSrcset',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesNoSrcset',
    description: 'Number of images missing srcset for responsive delivery.',
  },
  {
    key: 'p.content.imagesNoLazy',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesNoLazy',
    description: 'Number of images without lazy loading.',
  },
  {
    key: 'p.content.imagesNoDimensions',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesNoDimensions',
    description: 'Number of images missing width and height attributes.',
  },
  {
    key: 'p.content.imagesOriginalSize',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.content.imagesOriginalSize',
    description: 'Total original size of all images.',
  },
  {
    key: 'p.content.imagesDecorative',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.imagesDecorative',
    description: 'Number of decorative (empty alt) images.',
  },
  {
    key: 'p.content.imagesHasEXIF',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.imagesHasEXIF',
    description: 'Whether any images contain EXIF metadata.',
  },
  {
    key: 'p.content.videoTotal',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.videoTotal',
    description: 'Total number of videos embedded on the page.',
  },
  {
    key: 'p.content.videoHasSchema',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.videoHasSchema',
    description: 'Whether videos have corresponding VideoObject schema.',
  },
  {
    key: 'p.content.videoTranscript',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.videoTranscript',
    description: 'Whether a video transcript is provided.',
  },
  {
    key: 'p.content.audioTotal',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.audioTotal',
    description: 'Total number of audio elements on the page.',
  },
  {
    key: 'p.content.audioTranscript',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.audioTranscript',
    description: 'Whether an audio transcript is provided.',
  },
  {
    key: 'p.content.tablesCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.tablesCount',
    description: 'Total number of HTML tables.',
  },
  {
    key: 'p.content.codeBlocksCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.codeBlocksCount',
    description: 'Total number of code blocks.',
  },
  {
    key: 'p.content.faqPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.faqPresent',
    description: 'Whether FAQ section is present on the page.',
  },
  {
    key: 'p.content.faqSchemaMatch',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.faqSchemaMatch',
    description: 'Whether FAQ schema matches visible FAQ content.',
  },
  {
    key: 'p.content.howtoPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.howtoPresent',
    description: 'Whether a HowTo section is present on the page.',
  },
  {
    key: 'p.content.outlineValid',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.outlineValid',
    description: 'Whether the content follows a valid outline structure.',
  },
  {
    key: 'p.content.contentTypeClassified',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.contentTypeClassified',
    description: 'AI-classified content type.',
  },
  {
    key: 'p.content.regexPrices',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.regexPrices',
    description: 'Prices detected via regex on the page.',
  },
  {
    key: 'p.content.regexEmails',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.regexEmails',
    description: 'Email addresses detected via regex on the page.',
  },
  {
    key: 'p.content.regexPhones',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.regexPhones',
    description: 'Phone numbers detected via regex on the page.',
  },
  {
    key: 'p.content.regexCustom',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.regexCustom',
    description: 'Matches from user-defined custom regex patterns.',
  },
  {
    key: 'p.content.paginationPattern',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.paginationPattern',
    description: 'Detected pagination pattern (e.g., page/2/).',
  },
  {
    key: 'p.content.paginationIntegrity',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.paginationIntegrity',
    description: 'Whether pagination chain is complete and valid.',
  },
  {
    key: 'p.content.relatedContentCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.content.relatedContentCount',
    description: 'Number of related content links on the page.',
  },
  {
    key: 'p.content.updateBadge',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.updateBadge',
    description: 'Whether an "updated on" badge is displayed.',
  },
  {
    key: 'p.content.ctaDensity',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'S'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.ctaDensity',
    description: 'Number of calls-to-action per 1000 words.',
  },
  {
    key: 'p.content.trustSignalScore',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'S', 'A'],
    sources: ['T0', 'T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.trustSignalScore',
    description: 'Composite score of trust signals on the page.',
  },
  // ── Alias-targeted metrics ──
  {
    key: 'p.content.age',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'X'],
    sources: ['T0'],
    unit: 'days',
    format: 'number',
    i18nLabelKey: 'metric.p.content.age',
    description: 'Age of the content in days since first publish.',
  },
  {
    key: 'p.content.qualityScore',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.qualityScore',
    description: 'Content quality score for this page.',
  },
  {
    key: 'p.content.socialContentQuality',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'V'],
    sources: ['T0'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.socialContentQuality',
    description: 'Social content quality score.',
  },
  {
    key: 'p.content.contentFreshnessScore',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A', 'S'],
    sources: ['T0'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.contentFreshnessScore',
    description: 'Content freshness score.',
  },
  // ── EX-B: Content Expansion ──
  {
    key: 'p.content.title.duplicate',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.title.duplicate',
    description: 'Whether title is duplicated across multiple pages',
  },
  {
    key: 'p.content.title.duplicateCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.title.duplicateCount',
    description: 'Number of pages sharing this exact title',
  },
  {
    key: 'p.content.title.duplicateUrls',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.title.duplicateUrls',
    description: 'URLs sharing this title',
  },
  {
    key: 'p.content.title.matchH1',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.title.matchH1',
    description: 'Whether title matches H1 text',
  },
  {
    key: 'p.content.title.matchKw',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6', 'T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.title.matchKw',
    description: 'Whether title contains primary keyword',
  },
  {
    key: 'p.content.title.sentiment',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.title.sentiment',
    description: 'Title sentiment (positive, neutral, negative)',
  },
  {
    key: 'p.content.title.powerWords',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.title.powerWords',
    description: 'Power/emotional words detected in title',
  },
  {
    key: 'p.content.title.numberPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.title.numberPresent',
    description: 'Whether title contains a number (listicle signal)',
  },
  {
    key: 'p.content.title.questionPresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.title.questionPresent',
    description: 'Whether title is phrased as a question',
  },
  {
    key: 'p.content.metaDesc.duplicate',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.metaDesc.duplicate',
    description: 'Whether meta description is duplicated across pages',
  },
  {
    key: 'p.content.metaDesc.matchKw',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6', 'T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.metaDesc.matchKw',
    description: 'Whether meta description contains primary keyword',
  },
  {
    key: 'p.content.metaDesc.hasCTA',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.metaDesc.hasCTA',
    description: 'Whether meta description contains a call-to-action',
  },
  {
    key: 'p.content.metaDesc.ctaWords',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.metaDesc.ctaWords',
    description: 'CTA words detected in meta description',
  },
  {
    key: 'p.content.h1.duplicate',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.h1.duplicate',
    description: 'Whether H1 is duplicated across pages',
  },
  {
    key: 'p.content.h1.matchTitle',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.h1.matchTitle',
    description: 'Whether H1 closely matches page title',
  },
  {
    key: 'p.content.h1.matchKw',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6', 'T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.h1.matchKw',
    description: 'Whether H1 contains primary keyword',
  },
  {
    key: 'p.content.h1.length',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.h1.length',
    description: 'H1 character length',
  },
  {
    key: 'p.content.hTree.depth',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.hTree.depth',
    description: 'Maximum heading nesting depth',
  },
  {
    key: 'p.content.hTree.count',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.hTree.count',
    description: 'Total heading count (h1-h6)',
  },
  {
    key: 'p.content.hTree.h2Count',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.hTree.h2Count',
    description: 'Count of H2 headings',
  },
  {
    key: 'p.content.hTree.h3Count',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.hTree.h3Count',
    description: 'Count of H3 headings',
  },
  {
    key: 'p.content.hTree.avgLength',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.hTree.avgLength',
    description: 'Average heading text length',
  },
  {
    key: 'p.content.wordCount.mobile',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.wordCount.mobile',
    description: 'Word count on mobile-rendered version',
  },
  {
    key: 'p.content.wordCount.delta',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.wordCount.delta',
    description: 'Word count change vs previous crawl',
  },
  {
    key: 'p.content.wordCount.bucket',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.wordCount.bucket',
    description: 'Word count bucket for filtering',
  },
  {
    key: 'p.content.readability.fleschMobile',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0', 'T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.readability.fleschMobile',
    description: 'Readability score on mobile-rendered content',
  },
  {
    key: 'p.content.readability.gradeLevelMobile',
    namespace: 'p.content',
    level: 'P',
    roles: ['I'],
    sources: ['T0', 'T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.readability.gradeLevelMobile',
    description: 'Grade level on mobile-rendered content',
  },
  {
    key: 'p.content.readability.fleschDelta',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.readability.fleschDelta',
    description: 'Readability change vs previous crawl',
  },
  {
    key: 'p.content.readability.gradeBucket',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.content.readability.gradeBucket',
    description: 'Grade level bucket for filtering',
  },
  {
    key: 'p.content.duplicate.exactMobile',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.duplicate.exactMobile',
    description: 'Whether mobile version has exact duplicates',
  },
  {
    key: 'p.content.duplicate.crossDevice',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.duplicate.crossDevice',
    description: 'Whether mobile and desktop versions differ (cloaking risk)',
  },
  {
    key: 'p.content.freshness.publishDate',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.freshness.publishDate',
    description: 'Original publish date detected',
  },
  {
    key: 'p.content.freshness.modifiedDate',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.content.freshness.modifiedDate',
    description: 'Last modified date detected',
  },
  {
    key: 'p.content.freshness.daysSincePublish',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.freshness.daysSincePublish',
    description: 'Days since original publish date',
  },
  {
    key: 'p.content.freshness.daysSinceModified',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.freshness.daysSinceModified',
    description: 'Days since last modification',
  },
  {
    key: 'p.content.freshness.updateFrequency',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    unit: 'days',
    format: 'duration',
    i18nLabelKey: 'metric.p.content.freshness.updateFrequency',
    description: 'Average time between content updates',
  },
  {
    key: 'p.content.freshness.isEvergreen',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'L', 'A'],
    sources: ['T6', 'T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.freshness.isEvergreen',
    description: 'Whether content is evergreen (timeless topic)',
  },
  {
    key: 'p.content.freshness.decayRisk',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.freshness.decayRisk',
    description: 'Risk score for content becoming outdated',
  },
  {
    key: 'p.content.freshness.updateBadgePresent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.freshness.updateBadgePresent',
    description: 'Whether visible "last updated" badge is shown',
  },
  {
    key: 'p.content.freshness.schemaDateMatch',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.freshness.schemaDateMatch',
    description: 'Whether schema datePublished/dateModified match visible dates',
  },
  {
    key: 'p.content.eeat.authorEntity',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.content.eeat.authorEntity',
    description: 'Author entity resolved (name + credentials + links)',
  },
  {
    key: 'p.content.eeat.authorLinks',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.eeat.authorLinks',
    description: 'Author-related links (social profiles, bio pages, publications)',
  },
  {
    key: 'p.content.eeat.authorTopicality',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeat.authorTopicality',
    description: 'Author\'s topical authority in this content\'s domain',
  },
  {
    key: 'p.content.eeat.citationSources',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.eeat.citationSources',
    description: 'External sources cited in the content',
  },
  {
    key: 'p.content.eeat.citationAuthority',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6', 'T3'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeat.citationAuthority',
    description: 'Average authority of cited sources',
  },
  {
    key: 'p.content.eeat.originalAnalysis',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.eeat.originalAnalysis',
    description: 'Whether content contains original analysis/data/opinions',
  },
  {
    key: 'p.content.eeat.firstHandExperience',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.eeat.firstHandExperience',
    description: 'Whether content demonstrates first-hand experience',
  },
  {
    key: 'p.content.eeat.recency',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.eeat.recency',
    description: 'E-E-A-T recency signal (how up-to-date information is)',
  },
  {
    key: 'p.content.entities.resolved',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.entities.resolved',
    description: 'Entities with Wikipedia/Wikidata links resolved',
  },
  {
    key: 'p.content.entities.count',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.entities.count',
    description: 'Total entity count',
  },
  {
    key: 'p.content.entities.named',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.entities.named',
    description: 'Count of named entities (people, orgs, places)',
  },
  {
    key: 'p.content.entities.topical',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.entities.topical',
    description: 'Topical entities (concepts, not named entities)',
  },
  {
    key: 'p.content.entities.sentiment',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'json',
    i18nLabelKey: 'metric.p.content.entities.sentiment',
    description: 'Per-entity sentiment scores',
  },
  {
    key: 'p.content.topic.subtopics',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.topic.subtopics',
    description: 'Sub-topics covered within the main topic',
  },
  {
    key: 'p.content.topic.keywords',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6', 'T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.topic.keywords',
    description: 'Topic-relevant keywords found in content',
  },
  {
    key: 'p.content.topic.keywordCount',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.topic.keywordCount',
    description: 'Count of topic-relevant keywords used',
  },
  {
    key: 'p.content.topic.keywordDensity',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'percent',
    i18nLabelKey: 'metric.p.content.topic.keywordDensity',
    description: 'Primary keyword density percentage',
  },
  {
    key: 'p.content.topic.keywordProminence',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.keywordProminence',
    description: 'Keyword prominence (position in title, H1, first paragraph)',
  },
  {
    key: 'p.content.topic.freshness',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.freshness',
    description: 'Topic trend score (rising, stable, declining)',
  },
  {
    key: 'p.content.topic.seasonality',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.p.content.topic.seasonality',
    description: 'Topic seasonality pattern',
  },
  {
    key: 'p.content.topic.competition',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3', 'T5'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.competition',
    description: 'Topic competition level from SERP analysis',
  },
  {
    key: 'p.content.topic.gap',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6', 'T5'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.topic.gap',
    description: 'Sub-topics covered by competitors but missing here',
  },
  {
    key: 'p.content.topic.depth.score',
    namespace: 'p.content',
    level: 'P',
    roles: ['G', 'I', 'S', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.depth.score',
    description: 'Topic depth score (0-1) vs top SERP results',
  },
  {
    key: 'p.content.topic.breadth',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.breadth',
    description: 'Topic breadth score (how many sub-topics covered)',
  },
  {
    key: 'p.content.topic.authority',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'S', 'A'],
    sources: ['T6', 'T0'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.topic.authority',
    description: 'Topic authority score for this page',
  },
  {
    key: 'p.content.intent.matchTitle',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.intent.matchTitle',
    description: 'Title-to-intent match score',
  },
  {
    key: 'p.content.intent.matchContent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.intent.matchContent',
    description: 'Content body-to-intent match score',
  },
  {
    key: 'p.content.intent.matchSERP',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6', 'T5'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.intent.matchSERP',
    description: 'Page vs top-10 SERP intent alignment',
  },
  {
    key: 'p.content.cta.count',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.cta.count',
    description: 'Number of CTA elements on page',
  },
  {
    key: 'p.content.cta.prominence',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.cta.prominence',
    description: 'CTA prominence score (above fold, visual weight)',
  },
  {
    key: 'p.content.cta.types',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.content.cta.types',
    description: 'CTA types detected (button, link, form, popup, sticky bar)',
  },
  {
    key: 'p.content.cta.aboveFold',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.content.cta.aboveFold',
    description: 'Whether a CTA appears above the fold',
  },
  {
    key: 'p.content.internalLinks.inContent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.internalLinks.inContent',
    description: 'Internal links within content body (not nav/footer)',
  },
  {
    key: 'p.content.internalLinks.toCluster',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.internalLinks.toCluster',
    description: 'Internal links to same topic cluster pages',
  },
  {
    key: 'p.content.internalLinks.fromCluster',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.internalLinks.fromCluster',
    description: 'Internal links from same topic cluster pages',
  },
  {
    key: 'p.content.internalLinks.topicalRelevance',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.internalLinks.topicalRelevance',
    description: 'Topical relevance of internal links (anchor text match)',
  },
  {
    key: 'p.content.externalLinks.outContent',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.content.externalLinks.outContent',
    description: 'External links within content body',
  },
  {
    key: 'p.content.externalLinks.authority',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.externalLinks.authority',
    description: 'Average authority of externally linked domains',
  },
  {
    key: 'p.content.externalLinks.relevance',
    namespace: 'p.content',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.content.externalLinks.relevance',
    description: 'Topical relevance of external links',
  },
  // ── EX-Q.5: More Per-Metric Detail ──
  { key: 'p.content.title.chars', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.title.chars', description: 'Title character count' },
  { key: 'p.content.title.words', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.title.words', description: 'Title word count' },
  { key: 'p.content.metaDesc.chars', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.metaDesc.chars', description: 'Meta description character count' },
  { key: 'p.content.metaDesc.words', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.metaDesc.words', description: 'Meta description word count' },
  { key: 'p.content.metaDesc.truncated', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.content.metaDesc.truncated', description: 'Whether meta description is truncated in SERP (>155 chars)' },
  { key: 'p.content.title.truncated', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.content.title.truncated', description: 'Whether title is truncated in SERP (>60 chars)' },
  { key: 'p.content.h1.words', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.h1.words', description: 'H1 word count' },
  { key: 'p.content.h1.chars', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.h1.chars', description: 'H1 character count' },
  { key: 'p.content.images.totalAlt', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.images.totalAlt', description: 'Images with valid alt text' },
  { key: 'p.content.images.avgSize', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.content.images.avgSize', description: 'Average image file size' },
  { key: 'p.content.images.totalSize', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.content.images.totalSize', description: 'Total image payload' },
  { key: 'p.content.images.lazyLoaded', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.images.lazyLoaded', description: 'Images with lazy loading' },
  { key: 'p.content.images.withSrcset', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.images.withSrcset', description: 'Images with srcset (responsive)' },
  { key: 'p.content.images.withDimensions', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.images.withDimensions', description: 'Images with width/height attributes' },
  { key: 'p.content.images.avgAltLength', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.images.avgAltLength', description: 'Average alt text length' },
  { key: 'p.content.schema.allTypes', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.allTypes', description: 'All schema types present (complete list)' },
  { key: 'p.content.schema.allProperties', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.allProperties', description: 'All schema properties used' },
  { key: 'p.content.schema.missingRequired', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.missingRequired', description: 'Missing required schema properties' },
  { key: 'p.content.schema.missingRecommended', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.missingRecommended', description: 'Missing recommended schema properties' },
  { key: 'p.content.entities.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.entities.all', description: 'All extracted entities (complete list)' },
  { key: 'p.content.entities.types', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'json', i18nLabelKey: 'metric.p.content.entities.types', description: 'Entity type distribution: {person: N, org: N, place: N, ...}' },
  { key: 'p.content.questions.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.questions.all', description: 'All questions the page answers (full list)' },
  { key: 'p.content.subtopics', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.subtopics', description: 'Sub-topics covered in the content' },
  { key: 'p.content.entities.topBySalience', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.entities.topBySalience', description: 'Top 10 entities by salience score' },
  { key: 'p.content.topic.keywords.top', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.top', description: 'Top 10 topic keywords by frequency' },
  { key: 'p.content.topic.keywords.missed', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.missed', description: 'Important topic keywords not found in content' },
  { key: 'p.content.internalLinks.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.internalLinks.all', description: 'All internal links (complete list)' },
  { key: 'p.content.externalLinks.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.externalLinks.all', description: 'All external links (complete list)' },
  { key: 'p.content.images.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.images.all', description: 'All images with metadata (src, alt, size, format)' },
  { key: 'p.content.videos.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.videos.all', description: 'All video embeds with metadata' },
  { key: 'p.content.audio.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.audio.all', description: 'All audio embeds with metadata' },
  { key: 'p.content.tables.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.tables.all', description: 'All table elements with metadata' },
  { key: 'p.content.codeBlocks.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.codeBlocks.all', description: 'All code blocks with language and size' },
  { key: 'p.content.lists.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.lists.all', description: 'All list elements (ol/ul) with item counts' },
  { key: 'p.content.blockquotes.all', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.blockquotes.all', description: 'All blockquote elements' },
  { key: 'p.content.eeat.signals', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'json', i18nLabelKey: 'metric.p.content.eeat.signals', description: 'All E-E-A-T signals detected: {authorBio, authorPhoto, citations, originalAnalysis, ...}' },
  { key: 'p.content.schema.richResultTypes', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.richResultTypes', description: 'Rich result types eligible for this page' },
  { key: 'p.content.schema.requiredForPageType', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.requiredForPageType', description: 'Required schema types for this page\'s content type' },
  { key: 'p.content.schema.presentForPageType', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.presentForPageType', description: 'Schema types present matching page type requirements' },
  { key: 'p.content.schema.missingForPageType', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'list', i18nLabelKey: 'metric.p.content.schema.missingForPageType', description: 'Schema types missing for page type requirements' },
  { key: 'p.content.topic.keywords.density.top', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.density.top', description: 'Top keywords by density percentage' },
  { key: 'p.content.topic.keywords.prominence.top', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.prominence.top', description: 'Top keywords by prominence score' },
  { key: 'p.content.topic.keywords.missing.high', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.missing.high', description: 'High-priority keywords missing from content' },
  { key: 'p.content.topic.keywords.missing.medium', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.missing.medium', description: 'Medium-priority keywords missing from content' },
  { key: 'p.content.topic.keywords.missing.low', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.keywords.missing.low', description: 'Low-priority keywords missing from content' },
  { key: 'p.content.topic.relatedTopics', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.relatedTopics', description: 'Related topics that could strengthen the page' },
  { key: 'p.content.topic.competitorCoverage', namespace: 'p.content', level: 'P', roles: ['I', 'V'], sources: ['T6'], format: 'json', i18nLabelKey: 'metric.p.content.topic.competitorCoverage', description: 'How top SERP competitors cover this topic' },
  { key: 'p.content.topic.contentBrief', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'json', i18nLabelKey: 'metric.p.content.topic.contentBrief', description: 'AI-generated content brief with recommendations' },
  // ── EX-Q.6: Additional Detail Metrics ──
  { key: 'p.content.internalLinks.count', namespace: 'p.content', level: 'P', roles: ['G', 'I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.count', description: 'Internal links within content body' },
  { key: 'p.content.internalLinks.externalCount', namespace: 'p.content', level: 'P', roles: ['G', 'I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.externalCount', description: 'External links within content body' },
  { key: 'p.content.internalLinks.total', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.total', description: 'Total links within content body' },
  { key: 'p.content.internalLinks.avgPerHundredWords', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.avgPerHundredWords', description: 'Internal links per 100 words (link density)' },
  { key: 'p.content.internalLinks.externalAvgPerHundredWords', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.externalAvgPerHundredWords', description: 'External links per 100 words' },
  { key: 'p.content.internalLinks.topicalRelevance.avg', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'score', i18nLabelKey: 'metric.p.content.internalLinks.topicalRelevance.avg', description: 'Average topical relevance of internal links' },
  { key: 'p.content.internalLinks.toHighValuePages', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.toHighValuePages', description: 'Internal links to high-PageRank pages' },
  { key: 'p.content.internalLinks.fromHighValuePages', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.fromHighValuePages', description: 'Internal links from high-PageRank pages' },
  { key: 'p.content.internalLinks.toConversionPages', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.toConversionPages', description: 'Internal links to pages with conversions' },
  { key: 'p.content.internalLinks.fromConversionPages', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.internalLinks.fromConversionPages', description: 'Internal links from pages with conversions' },
  { key: 'p.content.externalLinks.toHighAuthDomains', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T3'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.externalLinks.toHighAuthDomains', description: 'Links to high-authority domains (DA > 70)' },
  { key: 'p.content.externalLinks.toLowAuthDomains', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T3'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.externalLinks.toLowAuthDomains', description: 'Links to low-authority domains (DA < 30)' },
  { key: 'p.content.externalLinks.toSameNiche', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.externalLinks.toSameNiche', description: 'Links to same-niche domains' },
  { key: 'p.content.externalLinks.toGovEdu', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.externalLinks.toGovEdu', description: 'Links to .gov and .edu domains' },
  { key: 'p.content.externalLinks.toNofollowDomains', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.externalLinks.toNofollowDomains', description: 'Links to domains with nofollow policies' },
  { key: 'p.content.entities.topBySalience.first', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.entities.topBySalience.first', description: 'Highest salience entity name' },
  { key: 'p.content.entities.topBySalience.firstScore', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'score', i18nLabelKey: 'metric.p.content.entities.topBySalience.firstScore', description: 'Highest salience entity score' },
  { key: 'p.content.entities.topBySalience.second', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.entities.topBySalience.second', description: 'Second highest salience entity' },
  { key: 'p.content.entities.topBySalience.third', namespace: 'p.content', level: 'P', roles: ['I', 'X'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.entities.topBySalience.third', description: 'Third highest salience entity' },
  { key: 'p.content.topic.keywords.density.top1', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.content.topic.keywords.density.top1', description: 'Highest density keyword percentage' },
  { key: 'p.content.topic.keywords.density.top2', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.content.topic.keywords.density.top2', description: 'Second highest density keyword percentage' },
  { key: 'p.content.topic.keywords.density.top3', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.content.topic.keywords.density.top3', description: 'Third highest density keyword percentage' },
  { key: 'p.content.topic.keywords.prominence.top1', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.content.topic.keywords.prominence.top1', description: 'Highest prominence keyword score' },
  { key: 'p.content.topic.keywords.prominence.top2', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.content.topic.keywords.prominence.top2', description: 'Second highest prominence keyword score' },
  { key: 'p.content.topic.keywords.prominence.top3', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.content.topic.keywords.prominence.top3', description: 'Third highest prominence keyword score' },
  { key: 'p.content.topic.keywords.missing.high.first', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.topic.keywords.missing.high.first', description: 'Highest priority missing keyword' },
  { key: 'p.content.topic.keywords.missing.high.second', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.topic.keywords.missing.high.second', description: 'Second highest priority missing keyword' },
  { key: 'p.content.topic.keywords.missing.high.third', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'text', i18nLabelKey: 'metric.p.content.topic.keywords.missing.high.third', description: 'Third highest priority missing keyword' },
  // ── EX-Q.7: Final 35 metrics ──
  { key: 'p.content.topic.competitorCount', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T5'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.topic.competitorCount', description: 'Number of competitors ranking for same topic' },
  { key: 'p.content.topic.competitorAvgWordCount', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T5'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.topic.competitorAvgWordCount', description: 'Average word count of top SERP competitors' },
  { key: 'p.content.topic.competitorAvgBacklinks', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T3', 'T5'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.content.topic.competitorAvgBacklinks', description: 'Average backlinks of top SERP competitors' },
  { key: 'p.content.topic.competitorAvgEeat', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'score', i18nLabelKey: 'metric.p.content.topic.competitorAvgEeat', description: 'Average E-E-A-T of top SERP competitors' },
  { key: 'p.content.topic.difficulty', namespace: 'p.content', level: 'P', roles: ['G', 'I', 'A'], sources: ['T3', 'T5'], format: 'score', i18nLabelKey: 'metric.p.content.topic.difficulty', description: 'Topic difficulty score based on SERP competition' },
  { key: 'p.content.topic.opportunity', namespace: 'p.content', level: 'P', roles: ['G', 'I', 'A'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.content.topic.opportunity', description: 'Topic opportunity score (difficulty vs current rank)' },
  { key: 'p.content.topic.recommendations', namespace: 'p.content', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.p.content.topic.recommendations', description: 'AI-generated content recommendations for topic' },
  // ── EX-R: CMS-Specific Metrics ──
  { key: 'p.wp.plugins.count', namespace: 'p.wp', level: 'P', roles: ['G', 'I', 'A'], sources: ['T2', 'T6'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.wp.plugins.count', description: 'Number of WordPress plugins detected on page', gate: { cms: ['wordpress'] } },
  { key: 'p.wp.theme', namespace: 'p.wp', level: 'P', roles: ['I', 'X'], sources: ['T2'], format: 'text', i18nLabelKey: 'metric.p.wp.theme', description: 'WordPress theme name detected', gate: { cms: ['wordpress'] } },
  { key: 'p.wp.yoast.score', namespace: 'p.wp', level: 'P', roles: ['G', 'I', 'S', 'A'], sources: ['T2'], format: 'score', i18nLabelKey: 'metric.p.wp.yoast.score', description: 'Yoast SEO score (if Yoast plugin detected)', gate: { cms: ['wordpress'] } },
  { key: 'p.wp.rankmath.score', namespace: 'p.wp', level: 'P', roles: ['G', 'I', 'S', 'A'], sources: ['T2'], format: 'score', i18nLabelKey: 'metric.p.wp.rankmath.score', description: 'RankMath SEO score (if RankMath plugin detected)', gate: { cms: ['wordpress'] } },
  { key: 'p.wp.acf.present', namespace: 'p.wp', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.wp.acf.present', description: 'Whether Advanced Custom Fields is in use', gate: { cms: ['wordpress'] } },
  { key: 'p.shopify.app.count', namespace: 'p.shopify', level: 'P', roles: ['G', 'I', 'A'], sources: ['T2'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.shopify.app.count', description: 'Number of Shopify apps detected on page', gate: { cms: ['shopify'] } },
  { key: 'p.shopify.theme', namespace: 'p.shopify', level: 'P', roles: ['I', 'X'], sources: ['T2'], format: 'text', i18nLabelKey: 'metric.p.shopify.theme', description: 'Shopify theme name detected', gate: { cms: ['shopify'] } },
  { key: 'p.shopify.metaobject', namespace: 'p.shopify', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.shopify.metaobject', description: 'Whether Shopify Metaobjects are in use (structured content)', gate: { cms: ['shopify'] } },
  { key: 'p.shopify.json-ld-pack', namespace: 'p.shopify', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.shopify.json-ld-pack', description: 'Whether a JSON-LD schema pack app is installed', gate: { cms: ['shopify'] } },
  { key: 'p.webflow.cms.item', namespace: 'p.webflow', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.webflow.cms.item', description: 'Whether page is a Webflow CMS collection item', gate: { cms: ['webflow'] } },
  { key: 'p.webflow.staticHtml', namespace: 'p.webflow', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.webflow.staticHtml', description: 'Whether page is static HTML (not CMS-driven)', gate: { cms: ['webflow'] } },
  { key: 'p.next.isr', namespace: 'p.next', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.next.isr', description: 'Whether page uses Incremental Static Regeneration', gate: { stack: ['nextjs'] } },
  { key: 'p.next.staticOrSsr', namespace: 'p.next', level: 'P', roles: ['I', 'A'], sources: ['T2', 'T7'], format: 'enum', i18nLabelKey: 'metric.p.next.staticOrSsr', description: 'Whether page is static, SSR, or ISR', gate: { stack: ['nextjs'] } },
  { key: 'p.next.hydrationMismatch', namespace: 'p.next', level: 'P', roles: ['G', 'I', 'A', 'E'], sources: ['T7'], format: 'boolean', i18nLabelKey: 'metric.p.next.hydrationMismatch', description: 'Whether hydration caused server/client content mismatch', gate: { stack: ['nextjs'] } },
  { key: 'p.headless.buildInfo', namespace: 'p.headless', level: 'P', roles: ['I', 'X'], sources: ['T2'], format: 'json', i18nLabelKey: 'metric.p.headless.buildInfo', description: 'Build/deploy info detected (preview vs production)', gate: { cms: ['contentful', 'sanity', 'strapi'] } },
  { key: 'p.headless.previewBleed', namespace: 'p.headless', level: 'P', roles: ['I', 'A', 'E'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.headless.previewBleed', description: 'Whether preview/draft content is leaking to production', gate: { cms: ['contentful', 'sanity', 'strapi'] } },
  { key: 'p.ghost.memberArea', namespace: 'p.ghost', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.ghost.memberArea', description: 'Whether page is behind Ghost member area', gate: { cms: ['ghost'] } },
  { key: 'p.ghost.portalEnabled', namespace: 'p.ghost', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.ghost.portalEnabled', description: 'Whether Ghost portal (signup/signin widget) is enabled', gate: { cms: ['ghost'] } },
  { key: 'p.substack.paywall', namespace: 'p.substack', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'boolean', i18nLabelKey: 'metric.p.substack.paywall', description: 'Whether page has Substack paywall active', gate: { cms: ['substack'] } },
  { key: 'p.substack.subscribeRate', namespace: 'p.substack', level: 'P', roles: ['I', 'A'], sources: ['T2'], format: 'score', i18nLabelKey: 'metric.p.substack.subscribeRate', description: 'Subscribe CTA prominence score', gate: { cms: ['substack'] } },
  // ── EX-R: News Metrics ──
  { key: 'p.news.headlineCount', namespace: 'p.news', level: 'P', roles: ['G', 'I', 'A'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.news.headlineCount', description: 'Number of headline elements on page (H1 + article headlines)', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.articleFreq', namespace: 'p.news', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.news.articleFreq', description: 'Publishing frequency (articles per day for this section)', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.authorDepth', namespace: 'p.news', level: 'P', roles: ['I', 'A'], sources: ['T6'], format: 'score', i18nLabelKey: 'metric.p.news.authorDepth', description: 'Author credential depth for YMYL news (0-1)', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.breakingSpeed', namespace: 'p.news', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'duration', i18nLabelKey: 'metric.p.news.breakingSpeed', description: 'Time from event to article publish (for time-sensitive content)', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.paywall.type', namespace: 'p.news', level: 'P', roles: ['G', 'I', 'A'], sources: ['T2', 'T7'], format: 'enum', i18nLabelKey: 'metric.p.news.paywall.type', description: 'Paywall type detected', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.paywall.previewLength', namespace: 'p.news', level: 'P', roles: ['I', 'A'], sources: ['T2'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.news.paywall.previewLength', description: 'Character count visible before paywall triggers', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.sitemap.newsIndex', namespace: 'p.news', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.news.sitemap.newsIndex', description: 'Whether page is in Google News sitemap', gate: { industries: ['news', 'media'] } },
  { key: 'p.news.schema.newsArticle', namespace: 'p.news', level: 'P', roles: ['G', 'I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.news.schema.newsArticle', description: 'Whether NewsArticle schema is present and valid', gate: { industries: ['news', 'media'] } },
  // ── EX-R: Job Board Metrics ──
  { key: 'p.jobs.postingCount', namespace: 'p.jobs', level: 'P', roles: ['G', 'I', 'K'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.jobs.postingCount', description: 'Total job postings on this listing page', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.applicationUrl', namespace: 'p.jobs', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.p.jobs.applicationUrl', description: 'External application URL (redirect target)', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.schema.valid', namespace: 'p.jobs', level: 'P', roles: ['G', 'I', 'A'], sources: ['T7'], format: 'boolean', i18nLabelKey: 'metric.p.jobs.schema.valid', description: 'Whether JobPosting schema is valid and complete', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.salaryPresent', namespace: 'p.jobs', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.jobs.salaryPresent', description: 'Whether salary/compensation info is present', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.locationPresent', namespace: 'p.jobs', level: 'P', roles: ['I', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.jobs.locationPresent', description: 'Whether job location is specified', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.expiryPresent', namespace: 'p.jobs', level: 'P', roles: ['I', 'A', 'E'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.p.jobs.expiryPresent', description: 'Whether job posting expiry date is set', gate: { industries: ['jobBoard'] } },
  { key: 'p.jobs.postingFreshness', namespace: 'p.jobs', level: 'P', roles: ['G', 'I', 'A'], sources: ['T0'], format: 'date', i18nLabelKey: 'metric.p.jobs.postingFreshness', description: 'Date job was posted (datePosted schema property)', gate: { industries: ['jobBoard'] } },
  // ── EX-R: RTL Language Metric ──
  { key: 'p.rtl.mirrorIssues', namespace: 'p.rtl', level: 'P', roles: ['I', 'A'], sources: ['T7'], format: 'list', i18nLabelKey: 'metric.p.rtl.mirrorIssues', description: 'RTL layout mirroring issues detected', gate: { languages: ['ar', 'he', 'fa', 'ur'] } },
];
