import type { MetricDef } from '@seesby/types';

export const AI_METRICS: MetricDef[] = [
	{
		key: 'p.ai.botsAllowed',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'L', 'A', 'E'],
		sources: ['T0', 'T6'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.botsAllowed.label',
		description: 'List of AI bots allowed by robots.txt.',
		gate: { modes: ['ai', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.ai.botsBlocked',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.botsBlocked.label',
		description: 'List of AI bots explicitly blocked by robots.txt.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.llmsTxt',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.ai.llmsTxt.label',
		description: 'Whether an llms.txt file exists at the domain root.',
		gate: { modes: ['ai', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.ai.llmsFullTxt',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.ai.llmsFullTxt.label',
		description: 'Whether an llms-full.txt file exists at the domain root.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		scoreComponent: 'ai',
		i18nLabelKey: 'metric.p.ai.extractability.label',
		description: 'How easily AI systems can extract content from this page.',
		gate: { modes: ['ai', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.ai.answerBoxFit',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.answerBoxFit.label',
		description: 'How well this page content fits an AI answer box format.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.definitionFit',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.definitionFit.label',
		description: 'How well this page provides a clear definition-style answer.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.qaStructureFit',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.qaStructureFit.label',
		description: 'How well the page content is structured for Q&A extraction.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.passageFitness',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.passageFitness.label',
		description: 'How well the page content can be extracted as standalone passages.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.speakable',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.speakable.label',
		description: 'How well the content is suited for voice/assistant readout.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.entityCoverage',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		scoreComponent: 'ai',
		i18nLabelKey: 'metric.p.ai.entityCoverage.label',
		description: 'Coverage of key entities mentioned in AI queries.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.entityLinking',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ai.entityLinking.label',
		description: 'Percentage of key entities linked to authoritative sources.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.schemaForAI',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.schemaForAI.label',
		description: 'Structured data quality for AI comprehension.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationOpenai',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'V', 'T', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citationOpenai.label',
		description: 'Number of citations from OpenAI/ChatGPT.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationAnthropic',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'V', 'T', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citationAnthropic.label',
		description: 'Number of citations from Anthropic/Claude.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationGemini',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'V', 'T', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citationGemini.label',
		description: 'Number of citations from Google Gemini.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationPerplexity',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'V', 'T', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citationPerplexity.label',
		description: 'Number of citations from Perplexity AI.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationBing',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'V', 'T', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citationBing.label',
		description: 'Number of citations from Bing Chat/Copilot.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citationRate',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A'],
		sources: ['T8'],
		format: 'percent',
		scoreComponent: 'ai',
		i18nLabelKey: 'metric.p.ai.citationRate.label',
		description: 'Rate at which this page is cited across AI platforms.',
		gate: { modes: ['ai', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.ai.sourceDiversity',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T8'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.sourceDiversity.label',
		description: 'Diversity of AI platforms citing this source.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.overviewPresence',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T8'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.ai.overviewPresence.label',
		description: 'Whether this page appears in Google AI Overview.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.aiOverviewPosition',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.aiOverviewPosition.label',
		description: 'Position within Google AI Overview when cited.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	// ── EX-G: AI Expansion ──
	{
		key: 'p.ai.bots.detail',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'json',
		i18nLabelKey: 'metric.p.ai.bots.detail.label',
		description: 'Per-bot status: {botName: allowed/blocked/unknown} for all 20+ AI bots.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.bots.blockedList',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.bots.blockedList.label',
		description: 'Names of specifically blocked AI bots.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.bots.allowedList',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.bots.allowedList.label',
		description: 'Names of explicitly allowed AI bots.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.bots.noRule',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.bots.noRule.label',
		description: 'AI bots with no specific rule (default behavior).',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.llmsTxt.sections',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.llmsTxt.sections.label',
		description: 'Sections present in llms.txt (overview, preferred, discouraged).',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.llmsTxt.linkCount',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.llmsTxt.linkCount.label',
		description: 'Number of links in llms.txt.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.llmsTxt.freshness',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'date',
		i18nLabelKey: 'metric.p.ai.llmsTxt.freshness.label',
		description: 'Last modified date of llms.txt.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability.headings',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.extractability.headings.label',
		description: 'Heading structure quality for AI extraction.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability.lists',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.extractability.lists.label',
		description: 'List structure quality for AI extraction.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability.tables',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.extractability.tables.label',
		description: 'Table structure quality for AI extraction.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability.schema',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.extractability.schema.label',
		description: 'Schema markup quality for AI extraction.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.extractability.overall',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'R', 'S', 'A'],
		sources: ['T7'],
		format: 'score',
		scoreComponent: 'ai',
		i18nLabelKey: 'metric.p.ai.extractability.overall.label',
		description: 'Overall extractability composite score.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citation.allEngines',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T5'],
		format: 'json',
		i18nLabelKey: 'metric.p.ai.citation.allEngines.label',
		description: 'Citation status across all engines: {openai: bool, anthropic: bool, ...}.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citation.count',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'I', 'A'],
		sources: ['T5'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.citation.count.label',
		description: 'Number of AI engines citing this page.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citation.rate.bucket',
		namespace: 'p.ai',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T7'],
		format: 'enum',
		i18nLabelKey: 'metric.p.ai.citation.rate.bucket.label',
		description: 'Citation rate bucket: high (>60%), medium (20-60%), low (5-20%), none (<5%).',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.citation.trend',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T5'],
		format: 'json',
		i18nLabelKey: 'metric.p.ai.citation.trend.label',
		description: 'Citation rate trend time-series.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.overviewPresence.position',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T5'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.overviewPresence.position.label',
		description: 'Position within AI Overview (1-based).',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.overviewPresence.quoteText',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T5'],
		format: 'text',
		i18nLabelKey: 'metric.p.ai.overviewPresence.quoteText.label',
		description: 'Text excerpt used in AI Overview from our page.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.overviewPresence.confidence',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T5'],
		format: 'score',
		i18nLabelKey: 'metric.p.ai.overviewPresence.confidence.label',
		description: 'Confidence that our page is cited in AI Overview.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.sourceDiversity.count',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T5'],
		format: 'number',
		i18nLabelKey: 'metric.p.ai.sourceDiversity.count.label',
		description: 'Number of pages from our domain cited alongside competitors.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.sourceDiversity.share',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T5'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ai.sourceDiversity.share.label',
		description: 'Our share of AI citations among topic competitors.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.entityLinking.rate',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T6'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ai.entityLinking.rate.label',
		description: 'Percentage of entities linked to Wikipedia/Wikidata.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	{
		key: 'p.ai.entityLinking.unlinked',
		namespace: 'p.ai',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T6'],
		format: 'list',
		i18nLabelKey: 'metric.p.ai.entityLinking.unlinked.label',
		description: 'Entities without Wikipedia/Wikidata links.',
		gate: { modes: ['ai', 'fullAudit'] },
	},
	// ── EX-Q.6: Comparison Metrics ──
	{ key: 'p.ai.score.vsPrev30d', namespace: 'p.ai', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.ai.score.vsPrev30d', description: 'AI discoverability score change vs previous 30d' },
	{ key: 'p.ai.extractability.vsPrev30d', namespace: 'p.ai', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'score', i18nLabelKey: 'metric.p.ai.extractability.vsPrev30d', description: 'Extractability change vs previous 30d' },
];
