import type { MetricDef } from '@seesby/types';

export const SOCIAL_METRICS: MetricDef[] = [
	{
		key: 'p.social.sharesFb',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sharesFb.label',
		description: 'Number of Facebook shares for this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sharesLinkedin',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sharesLinkedin.label',
		description: 'Number of LinkedIn shares for this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sharesX',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sharesX.label',
		description: 'Number of X (Twitter) shares for this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sharesPinterest',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sharesPinterest.label',
		description: 'Number of Pinterest pins for this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sharesReddit',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sharesReddit.label',
		description: 'Number of Reddit shares for this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sharesTotal',
		namespace: 'p.social',
		level: 'P',
		roles: ['G', 'I', 'V', 'S'],
		sources: ['T6', 'T8'],
		format: 'number',
		scoreComponent: 'social',
		i18nLabelKey: 'metric.p.social.sharesTotal.label',
		description: 'Total social shares across all platforms.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.ogPreviewOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['G', 'I', 'A', 'E'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.ogPreviewOk.label',
		description: 'Whether the Open Graph preview renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.ogMissingTags',
		namespace: 'p.social',
		level: 'P',
		roles: ['G', 'I', 'A', 'E'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.ogMissingTags.label',
		description: 'Number of missing Open Graph tags.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.embedsX',
		namespace: 'p.social',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.embedsX.label',
		description: 'Number of embedded X (Twitter) posts on this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.embedsInstagram',
		namespace: 'p.social',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.embedsInstagram.label',
		description: 'Number of embedded Instagram posts on this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.embedsYoutube',
		namespace: 'p.social',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.embedsYoutube.label',
		description: 'Number of embedded YouTube videos on this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.embedsTiktok',
		namespace: 'p.social',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.embedsTiktok.label',
		description: 'Number of embedded TikTok videos on this page.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.sourceLinks',
		namespace: 'p.social',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.social.sourceLinks.label',
		description: 'Number of outbound links to social media profiles.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.bestTime',
		namespace: 'p.social',
		level: 'P',
		roles: ['R', 'V'],
		sources: ['T6'],
		format: 'text',
		gate: { modes: ['socialBrand', 'fullAudit'] },
		i18nLabelKey: 'metric.p.social.bestTime',
		description: 'Best time to post based on engagement data.',
	},
	{
		key: 'p.social.bestType',
		namespace: 'p.social',
		level: 'P',
		roles: ['R', 'V'],
		sources: ['T6'],
		format: 'text',
		gate: { modes: ['socialBrand', 'fullAudit'] },
		i18nLabelKey: 'metric.p.social.bestType',
		description: 'Best content type for engagement based on historical data.',
	},
	// ── EX-H: Social Expansion ──
	{
		key: 'p.social.shares.total.trend',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3'],
		format: 'json',
		i18nLabelKey: 'metric.p.social.shares.total.trend.label',
		description: 'Total social shares trend time-series.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.shares.fb.trend',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3'],
		format: 'json',
		i18nLabelKey: 'metric.p.social.shares.fb.trend.label',
		description: 'Facebook shares trend.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.shares.x.trend',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3'],
		format: 'json',
		i18nLabelKey: 'metric.p.social.shares.x.trend.label',
		description: 'X/Twitter shares trend.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.shares.linkedin.trend',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3'],
		format: 'json',
		i18nLabelKey: 'metric.p.social.shares.linkedin.trend.label',
		description: 'LinkedIn shares trend.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.titleOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.titleOk.label',
		description: 'Whether OG title renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.descriptionOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.descriptionOk.label',
		description: 'Whether OG description renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.imageOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.imageOk.label',
		description: 'Whether OG image loads and renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.typeOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.typeOk.label',
		description: 'Whether og:type is correct for content type.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.urlOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.urlOk.label',
		description: 'Whether og:url matches canonical.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.siteNameOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.og.siteNameOk.label',
		description: 'Whether og:site_name is present and correct.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.cardOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.cardOk.label',
		description: 'Whether Twitter card renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.titleOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.titleOk.label',
		description: 'Whether Twitter title renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.descriptionOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.descriptionOk.label',
		description: 'Whether Twitter description renders correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.imageOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.imageOk.label',
		description: 'Whether Twitter image loads correctly.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.siteOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.siteOk.label',
		description: 'Whether twitter:site is present.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.twitter.creatorOk',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.social.twitter.creatorOk.label',
		description: 'Whether twitter:creator is present.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.og.missingTagsList',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T7'],
		format: 'list',
		i18nLabelKey: 'metric.p.social.og.missingTagsList.label',
		description: 'List of specific missing OG tags.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	{
		key: 'p.social.preconnects',
		namespace: 'p.social',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'list',
		i18nLabelKey: 'metric.p.social.preconnects.label',
		description: 'Social media preconnect hints in HTML.',
		gate: { modes: ['socialBrand', 'fullAudit'] },
	},
	// ── EX-Q.6: Comparison Metrics ──
	{ key: 'p.social.shares.vsPrev30d', namespace: 'p.social', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.social.shares.vsPrev30d', description: 'Social shares change vs previous 30d' },
	{ key: 'p.social.backlinks.vsPrev30d', namespace: 'p.social', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.social.backlinks.vsPrev30d', description: 'Social backlinks change vs previous 30d' },
];
