import type { MetricDef } from '@seesby/types';

export const keywordMetrics: MetricDef[] = [
  {
    key: 'q.kw',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'I', 'V', 'X'],
    sources: ['T0'],
    format: 'text',
    width: '200px',
    i18nLabelKey: 'metric.q.kw',
    description: 'The keyword or query string.',
  },
  {
    key: 'q.intent',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.q.intent',
    description: 'Classified search intent.',
  },
  {
    key: 'q.funnel',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    width: '100px',
    i18nLabelKey: 'metric.q.funnel',
    description: 'Funnel stage (TOFU / MOFU / BOFU).',
  },
  {
    key: 'q.volume',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'V'],
    sources: ['T0', 'T5'],
    format: 'number',
    width: '80px',
    unit: 'count',
    i18nLabelKey: 'metric.q.volume',
    description: 'Monthly search volume.',
  },
  {
    key: 'q.difficulty',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'V'],
    sources: ['T3', 'T5'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.q.difficulty',
    description: 'Keyword SEO difficulty score.',
  },
  {
    key: 'q.ourRank',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'V', 'T'],
    sources: ['T0'],
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.q.ourRank',
    description: 'Current best ranking position for the site.',
  },
  {
    key: 'q.bestRankUrl',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'I', 'A', 'E'],
    sources: ['T0'],
    format: 'url',
    width: '200px',
    i18nLabelKey: 'metric.q.bestRankUrl',
    description: 'URL that ranks highest for this keyword.',
  },
  {
    key: 'q.serpFeatures',
    namespace: 'q',
    level: 'Q',
    roles: ['I'],
    sources: ['T5'],
    format: 'list',
    width: '120px',
    i18nLabelKey: 'metric.q.serpFeatures',
    description: 'SERP features present for this query.',
  },
  {
    key: 'q.localized',
    namespace: 'q',
    level: 'Q',
    roles: ['L'],
    sources: ['T0'],
    format: 'boolean',
    width: '70px',
    i18nLabelKey: 'metric.q.localized',
    description: 'Whether the query has local intent.',
  },
  {
    key: 'q.seasonality',
    namespace: 'q',
    level: 'Q',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'score',
    width: '80px',
    i18nLabelKey: 'metric.q.seasonality',
    description: 'Seasonality index for this keyword.',
  },
  {
    key: 'q.trendSlope',
    namespace: 'q',
    level: 'Q',
    roles: ['I', 'V', 'A'],
    sources: ['T1'],
    format: 'number',
    width: '80px',
    i18nLabelKey: 'metric.q.trendSlope',
    description: 'Recent trend direction and magnitude.',
  },
  {
    key: 'q.clusterId',
    namespace: 'q',
    level: 'Q',
    roles: ['L', 'V'],
    sources: ['T6'],
    format: 'text',
    width: '100px',
    i18nLabelKey: 'metric.q.clusterId',
    description: 'Keyword cluster grouping identifier.',
  },
  {
    key: 'q.opportunityScore',
    namespace: 'q',
    level: 'Q',
    roles: ['G', 'V', 'A'],
    sources: ['T0'],
    format: 'score',
    width: '100px',
    i18nLabelKey: 'metric.q.opportunityScore',
    description: 'Composite opportunity score combining volume, difficulty, and current rank.',
  },
];
