import type { MetricDef } from '@seesby/types';

export const entityMetrics: MetricDef[] = [
  {
    key: 'e.competitor.domain',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'R', 'V', 'X'],
    sources: ['T3'],
    format: 'text',
    i18nLabelKey: 'metric.e.competitor.domain',
    description: 'Competitor domain.',
  },
  {
    key: 'e.competitor.kwOverlap',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'R', 'V', 'K'],
    sources: ['T0', 'T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.competitor.kwOverlap',
    description: 'Keyword overlap score between site and competitor.',
  },
  {
    key: 'e.competitor.serpOverlap',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V'],
    sources: ['T5'],
    format: 'score',
    i18nLabelKey: 'metric.e.competitor.serpOverlap',
    description: 'SERP result overlap percentage with competitor.',
  },
  {
    key: 'e.competitor.sovOrganic',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V', 'K', 'T'],
    sources: ['T0', 'T3'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.sovOrganic',
    description: 'Share of voice in organic results vs competitor.',
  },
  {
    key: 'e.competitor.sovPaid',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V', 'T'],
    sources: ['T0', 'T3'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.sovPaid',
    description: 'Share of voice in paid results vs competitor.',
  },
  {
    key: 'e.competitor.sovSocial',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V', 'T'],
    sources: ['T3'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.sovSocial',
    description: 'Share of voice in social mentions vs competitor.',
  },
  {
    key: 'e.competitor.backlinkOverlap',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.competitor.backlinkOverlap',
    description: 'Backlink profile overlap score with competitor.',
  },
  {
    key: 'e.competitor.contentVelocity',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.contentVelocity',
    description: 'Content publishing velocity of competitor per month.',
  },
  {
    key: 'e.competitor.pricing',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V', 'B'],
    sources: ['T3', 'T5'],
    format: 'money',
    i18nLabelKey: 'metric.e.competitor.pricing',
    description: 'Competitor pricing for comparable products or plans.',
  },
  {
    key: 'e.competitor.employeeEst',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.employeeEst',
    description: 'Estimated employee count of competitor.',
  },
  {
    key: 'e.competitor.funding',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V'],
    sources: ['T3'],
    format: 'money',
    i18nLabelKey: 'metric.e.competitor.funding',
    description: 'Total funding raised by competitor.',
  },
  {
    key: 'e.competitor.revEst',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V'],
    sources: ['T3', 'T6'],
    format: 'money',
    i18nLabelKey: 'metric.e.competitor.revEst',
    description: 'Estimated annual revenue of competitor.',
  },
  {
    key: 'e.competitor.techStack',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.techStack',
    description: 'Technologies detected on competitor site.',
  },
  {
    key: 'e.competitor.wins',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.wins',
    description: 'Number of SERP positions where site outranks competitor.',
  },
  {
    key: 'e.competitor.losses',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.losses',
    description: 'Number of SERP positions where competitor outranks site.',
  },
  {
    key: 'e.competitor.priceDelta',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V', 'A', 'E'],
    sources: ['T3', 'T5'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.priceDelta',
    description: 'Price difference between site and competitor.',
  },
  {
    key: 'e.competitor.contentGapShared',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.contentGapShared',
    description: 'Shared content gaps between site and competitor.',
  },
  {
    key: 'e.local.napScore',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T0', 'T3', 'T6'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.napScore',
    description: 'NAP consistency score across local citations.',
  },
  {
    key: 'e.local.gbpLinked',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbpLinked',
    description: 'Whether a Google Business Profile is linked.',
  },
  {
    key: 'e.local.gbpVerified',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbpVerified',
    description: 'Whether the Google Business Profile is verified.',
  },
  {
    key: 'e.local.gbpCompleteness',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'S', 'A'],
    sources: ['T0'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.gbpCompleteness',
    description: 'Completeness score of Google Business Profile listing.',
  },
  {
    key: 'e.local.reviewsCountGoogle',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'K'],
    sources: ['T0', 'T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.local.reviewsCountGoogle',
    description: 'Total number of Google reviews.',
  },
  {
    key: 'e.local.reviewsAvgGoogle',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'K', 'S'],
    sources: ['T0', 'T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.reviewsAvgGoogle',
    description: 'Average Google review rating.',
    defaultVisible: true,
    gate: { industries: ['local', 'restaurant', 'healthcare'] },
  },
  {
    key: 'e.local.rankGeogrid',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'T'],
    sources: ['T5'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.rankGeogrid',
    description: 'Geogrid local ranking visibility score.',
    defaultVisible: true,
    gate: { industries: ['local', 'restaurant', 'healthcare'] },
  },
  {
    key: 'e.local.citationsCount',
    namespace: 'e.local',
    level: 'E',
    roles: ['G', 'V', 'A'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.local.citationsCount',
    description: 'Number of local citation references found.',
  },

  // ── EX-K: Local Expansion ──
  {
    key: 'e.local.nap.consistency.phone',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.nap.consistency.phone',
    description: 'Phone number consistency across citations.',
  },
  {
    key: 'e.local.nap.consistency.name',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.nap.consistency.name',
    description: 'Business name consistency across citations.',
  },
  {
    key: 'e.local.nap.consistency.address',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.nap.consistency.address',
    description: 'Address consistency across citations.',
  },
  {
    key: 'e.local.nap.consistency.website',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.local.nap.consistency.website',
    description: 'Website URL consistency across citations.',
  },
  {
    key: 'e.local.gbp.completeness.name',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.name',
    description: 'GBP name field filled.',
  },
  {
    key: 'e.local.gbp.completeness.description',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.description',
    description: 'GBP description field filled.',
  },
  {
    key: 'e.local.gbp.completeness.category',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.category',
    description: 'GBP category selected.',
  },
  {
    key: 'e.local.gbp.completeness.photos',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.photos',
    description: 'GBP photos uploaded.',
  },
  {
    key: 'e.local.gbp.completeness.posts',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.posts',
    description: 'GBP has recent posts.',
  },
  {
    key: 'e.local.gbp.completeness.qa',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'boolean',
    i18nLabelKey: 'metric.e.local.gbp.completeness.qa',
    description: 'GBP Q&A section populated.',
  },
  {
    key: 'e.local.reviews.rating.distribution',
    namespace: 'e.local',
    level: 'E',
    roles: ['I', 'V'],
    sources: ['T8'],
    format: 'json',
    i18nLabelKey: 'metric.e.local.reviews.rating.distribution',
    description: 'Star rating distribution (1-5 count).',
  },
  {
    key: 'e.local.reviews.keywords.positive',
    namespace: 'e.local',
    level: 'E',
    roles: ['I', 'V'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.e.local.reviews.keywords.positive',
    description: 'Top positive keywords in reviews.',
  },
  {
    key: 'e.local.reviews.keywords.negative',
    namespace: 'e.local',
    level: 'E',
    roles: ['I', 'V'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.e.local.reviews.keywords.negative',
    description: 'Top negative keywords in reviews.',
  },
  {
    key: 'e.local.reviews.responseTime',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T8'],
    format: 'duration',
    i18nLabelKey: 'metric.e.local.reviews.responseTime',
    description: 'Average owner response time.',
  },
  {
    key: 'e.local.reviews.sentiment.trend',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'T'],
    sources: ['T8'],
    format: 'json',
    i18nLabelKey: 'metric.e.local.reviews.sentiment.trend',
    description: 'Review sentiment trend time-series.',
  },
  {
    key: 'e.local.citations.sources.count',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.local.citations.sources.count',
    description: 'Number of citation sources found.',
  },
  {
    key: 'e.local.citations.sources.list',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'X'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.local.citations.sources.list',
    description: 'List of citation sources with status.',
  },
  {
    key: 'e.local.citations.inconsistencies',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'A', 'E'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.local.citations.inconsistencies',
    description: 'Citations with NAP inconsistencies.',
  },
  {
    key: 'e.local.rankGeogrid.center',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'json',
    i18nLabelKey: 'metric.e.local.rankGeogrid.center',
    description: 'Geogrid center coordinates.',
  },
  {
    key: 'e.local.rankGeogrid.radius',
    namespace: 'e.local',
    level: 'E',
    roles: ['V'],
    sources: ['T8'],
    format: 'number',
    unit: 'km',
    i18nLabelKey: 'metric.e.local.rankGeogrid.radius',
    description: 'Geogrid radius in km/miles.',
  },
  {
    key: 'e.local.rankGeogrid.avg',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'K'],
    sources: ['T8'],
    format: 'number',
    i18nLabelKey: 'metric.e.local.rankGeogrid.avg',
    description: 'Average local pack rank across grid.',
  },
  {
    key: 'e.local.rankGeogrid.trend',
    namespace: 'e.local',
    level: 'E',
    roles: ['V', 'T'],
    sources: ['T8'],
    format: 'json',
    i18nLabelKey: 'metric.e.local.rankGeogrid.trend',
    description: 'Geogrid average rank trend.',
  },

  // ─── EX-O: Entity Expansion — Competitor Overview ──────────────
  {
    key: 'e.competitor.overview',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'X'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.overview',
    description: 'Competitor overview: {domain, traffic, keywords, da, pages}',
  },
  {
    key: 'e.competitor.topPages',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.topPages',
    description: 'Top 10 competitor pages by traffic',
  },
  {
    key: 'e.competitor.topKeywords',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.topKeywords',
    description: 'Top 20 competitor keywords',
  },
  {
    key: 'e.competitor.contentTypes',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.contentTypes',
    description: 'Competitor content type distribution',
  },
  {
    key: 'e.competitor.updateFrequency',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.updateFrequency',
    description: 'Average content updates per week',
  },
  {
    key: 'e.competitor.schemaTypes',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.schemaTypes',
    description: 'Schema types used by competitor',
  },
  {
    key: 'e.competitor.techStackDetail',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.techStackDetail',
    description: 'Detailed tech stack breakdown',
  },

  // ─── EX-O: Entity Expansion — Competitor Backlinks ─────────────
  {
    key: 'e.competitor.backlinks.total',
    namespace: 'e.competitor.backlinks',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.backlinks.total',
    description: 'Competitor total backlinks',
  },
  {
    key: 'e.competitor.backlinks.refDomains',
    namespace: 'e.competitor.backlinks',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.backlinks.refDomains',
    description: 'Competitor referring domains',
  },
  {
    key: 'e.competitor.backlinks.da',
    namespace: 'e.competitor.backlinks',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'score',
    i18nLabelKey: 'metric.e.competitor.backlinks.da',
    description: 'Competitor domain authority',
  },

  // ─── EX-O: Entity Expansion — Competitor Organic ───────────────
  {
    key: 'e.competitor.organic.traffic',
    namespace: 'e.competitor.organic',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.organic.traffic',
    description: 'Competitor estimated organic traffic',
  },
  {
    key: 'e.competitor.organic.keywords',
    namespace: 'e.competitor.organic',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.organic.keywords',
    description: 'Competitor organic keyword count',
  },
  {
    key: 'e.competitor.organic.trafficTrend',
    namespace: 'e.competitor.organic',
    level: 'E',
    roles: ['R', 'V', 'T'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.organic.trafficTrend',
    description: 'Competitor organic traffic trend',
  },

  // ─── EX-O: Entity Expansion — Competitor Paid ──────────────────
  {
    key: 'e.competitor.paid.traffic',
    namespace: 'e.competitor.paid',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.paid.traffic',
    description: 'Competitor estimated paid traffic',
  },
  {
    key: 'e.competitor.paid.keywords',
    namespace: 'e.competitor.paid',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'number',
    i18nLabelKey: 'metric.e.competitor.paid.keywords',
    description: 'Competitor paid keyword count',
  },
  {
    key: 'e.competitor.paid.spend',
    namespace: 'e.competitor.paid',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'money',
    i18nLabelKey: 'metric.e.competitor.paid.spend',
    description: 'Competitor estimated ad spend',
  },

  // ─── EX-O: Entity Expansion — Competitor Social ────────────────
  {
    key: 'e.competitor.social.profiles',
    namespace: 'e.competitor.social',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.social.profiles',
    description: 'Competitor social media profiles',
  },
  {
    key: 'e.competitor.social.followers',
    namespace: 'e.competitor.social',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T3'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.social.followers',
    description: 'Competitor follower counts per platform',
  },

  // ─── EX-O: Entity Expansion — Competitor SERP ──────────────────
  {
    key: 'e.competitor.serp.features',
    namespace: 'e.competitor.serp',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T5'],
    format: 'json',
    i18nLabelKey: 'metric.e.competitor.serp.features',
    description: 'Competitor SERP feature ownership',
  },

  // ─── EX-O: Entity Expansion — Competitor Content ───────────────
  {
    key: 'e.competitor.content.quality',
    namespace: 'e.competitor.content',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.e.competitor.content.quality',
    description: 'Competitor average content quality score',
  },
  {
    key: 'e.competitor.content.gaps',
    namespace: 'e.competitor.content',
    level: 'E',
    roles: ['R', 'V', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.content.gaps',
    description: "Topics competitors cover but we don't",
  },
  {
    key: 'e.competitor.content.ourGaps',
    namespace: 'e.competitor.content',
    level: 'E',
    roles: ['R', 'V', 'A'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.content.ourGaps',
    description: "Topics we cover but competitor doesn't",
  },

  // ─── EX-O: Entity Expansion — Competitor Links ─────────────────
  {
    key: 'e.competitor.link.gaps',
    namespace: 'e.competitor.link',
    level: 'E',
    roles: ['R', 'V', 'A'],
    sources: ['T3'],
    format: 'list',
    i18nLabelKey: 'metric.e.competitor.link.gaps',
    description: 'Link opportunities: sites linking to competitor but not us',
  },

  // ─── EX-O: Entity Expansion — Competitor Win/Loss ──────────────
  {
    key: 'e.competitor.winRate',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.winRate',
    description: 'Percentage of keywords where we outrank competitor',
  },
  {
    key: 'e.competitor.lossRate',
    namespace: 'e.competitor',
    level: 'E',
    roles: ['R', 'V'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.e.competitor.lossRate',
    description: 'Percentage of keywords where competitor outranks us',
  },
  // ── EX-Q.6: Entity Author Metrics ──
  { key: 'e.author.name', namespace: 'e.author', level: 'E', roles: ['I', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.author.name', description: 'Author name' },
  { key: 'e.author.url', namespace: 'e.author', level: 'E', roles: ['I', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.e.author.url', description: 'Author page URL' },
  { key: 'e.author.pageCount', namespace: 'e.author', level: 'E', roles: ['R', 'K'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.author.pageCount', description: 'Total pages authored' },
  { key: 'e.author.totalTraffic', namespace: 'e.author', level: 'E', roles: ['R', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.author.totalTraffic', description: 'Total traffic to author content' },
  { key: 'e.author.avgTraffic', namespace: 'e.author', level: 'E', roles: ['R', 'V'], sources: ['T7'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.author.avgTraffic', description: 'Average traffic per author page' },
  { key: 'e.author.topPage.url', namespace: 'e.author', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.e.author.topPage.url', description: 'URL of author\'s most-visited page' },
  { key: 'e.author.topPage.traffic', namespace: 'e.author', level: 'E', roles: ['R', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.author.topPage.traffic', description: 'Traffic to author\'s most-visited page' },
  { key: 'e.author.schemaPresent', namespace: 'e.author', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.author.schemaPresent', description: 'Whether author has Person schema' },
  { key: 'e.author.schemaLinked', namespace: 'e.author', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.author.schemaLinked', description: 'Whether author schema links to external profiles' },
  { key: 'e.author.topClusters', namespace: 'e.author', level: 'E', roles: ['R', 'V'], sources: ['T6'], format: 'list', i18nLabelKey: 'metric.e.author.topClusters', description: 'Top topic clusters this author writes about' },
  { key: 'e.author.contentVelocity', namespace: 'e.author', level: 'E', roles: ['R', 'V'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.e.author.contentVelocity', description: 'Articles published per month' },
  { key: 'e.author.avgFreshness', namespace: 'e.author', level: 'E', roles: ['R', 'K'], sources: ['T0'], unit: 'days', format: 'number', i18nLabelKey: 'metric.e.author.avgFreshness', description: 'Average days since last publish' },
  { key: 'e.author.totalBacklinks', namespace: 'e.author', level: 'E', roles: ['R', 'K'], sources: ['T3'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.author.totalBacklinks', description: 'Total backlinks to author\'s content' },
  { key: 'e.author.authority', namespace: 'e.author', level: 'E', roles: ['R', 'K'], sources: ['T3'], format: 'score', i18nLabelKey: 'metric.e.author.authority', description: 'Author\'s overall authority score' },
  // ── EX-Q.6: Entity Product Metrics ──
  { key: 'e.product.name', namespace: 'e.product', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.product.name', description: 'Product name' },
  { key: 'e.product.url', namespace: 'e.product', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.e.product.url', description: 'Product page URL' },
  { key: 'e.product.price', namespace: 'e.product', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'money', i18nLabelKey: 'metric.e.product.price', description: 'Product price' },
  { key: 'e.product.currency', namespace: 'e.product', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.product.currency', description: 'Currency code' },
  { key: 'e.product.availability', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'enum', i18nLabelKey: 'metric.e.product.availability', description: 'In stock, out of stock, pre-order, discontinued' },
  { key: 'e.product.rating', namespace: 'e.product', level: 'E', roles: ['R', 'V'], sources: ['T0'], format: 'score', i18nLabelKey: 'metric.e.product.rating', description: 'Product rating (1-5)' },
  { key: 'e.product.reviewCount', namespace: 'e.product', level: 'E', roles: ['R', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.product.reviewCount', description: 'Number of reviews' },
  { key: 'e.product.schemaValid', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.product.schemaValid', description: 'Whether Product schema is valid' },
  { key: 'e.product.schemaComplete', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.product.schemaComplete', description: 'Whether all required Product schema fields present' },
  { key: 'e.product.inStockIndexed', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.product.inStockIndexed', description: 'Whether in-stock product is indexed' },
  { key: 'e.product.outOfStockIndexed', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.product.outOfStockIndexed', description: 'Whether out-of-stock product is indexed' },
  { key: 'e.product.richResultEligible', namespace: 'e.product', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.product.richResultEligible', description: 'Eligible for product rich results' },
  { key: 'e.product.competitorCount', namespace: 'e.product', level: 'E', roles: ['R', 'V'], sources: ['T5'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.product.competitorCount', description: 'Number of competitors for this product' },
  { key: 'e.product.serpFeatures', namespace: 'e.product', level: 'E', roles: ['R', 'V'], sources: ['T5'], format: 'list', i18nLabelKey: 'metric.e.product.serpFeatures', description: 'SERP features shown for product queries' },
  { key: 'e.product.priceCompetitiveness', namespace: 'e.product', level: 'E', roles: ['R', 'V'], sources: ['T5'], format: 'score', i18nLabelKey: 'metric.e.product.priceCompetitiveness', description: 'Price competitiveness vs competitors' },
  // ── EX-Q.6: Entity Location Metrics ──
  { key: 'e.location.name', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.location.name', description: 'Location name' },
  { key: 'e.location.url', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'url', i18nLabelKey: 'metric.e.location.url', description: 'Location page URL' },
  { key: 'e.location.address', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.location.address', description: 'Full address' },
  { key: 'e.location.phone', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'text', i18nLabelKey: 'metric.e.location.phone', description: 'Phone number' },
  { key: 'e.location.hours', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.e.location.hours', description: 'Business hours schema' },
  { key: 'e.location.gmbConnected', namespace: 'e.location', level: 'E', roles: ['R', 'A'], sources: ['T0'], format: 'boolean', i18nLabelKey: 'metric.e.location.gmbConnected', description: 'Google Business Profile connected' },
  { key: 'e.location.citationCount', namespace: 'e.location', level: 'E', roles: ['R', 'K'], sources: ['T3'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.location.citationCount', description: 'Number of local citations' },
  { key: 'e.location.citationConsistent', namespace: 'e.location', level: 'E', roles: ['R', 'A'], sources: ['T7'], format: 'boolean', i18nLabelKey: 'metric.e.location.citationConsistent', description: 'NAP consistency across citations' },
  { key: 'e.location.reviewCount', namespace: 'e.location', level: 'E', roles: ['R', 'V'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.e.location.reviewCount', description: 'Total reviews across platforms' },
  { key: 'e.location.avgRating', namespace: 'e.location', level: 'E', roles: ['R', 'V'], sources: ['T0'], format: 'score', i18nLabelKey: 'metric.e.location.avgRating', description: 'Average rating across platforms' },
  { key: 'e.location.mapPackRank', namespace: 'e.location', level: 'E', roles: ['R', 'V'], sources: ['T5'], format: 'number', i18nLabelKey: 'metric.e.location.mapPackRank', description: 'Local pack/map pack ranking' },
  { key: 'e.location.distanceKm', namespace: 'e.location', level: 'E', roles: ['R', 'V'], sources: ['T5'], format: 'number', i18nLabelKey: 'metric.e.location.distanceKm', description: 'Distance from user search location' },
  { key: 'e.location.serviceRadius', namespace: 'e.location', level: 'E', roles: ['R', 'X'], sources: ['T0'], format: 'number', i18nLabelKey: 'metric.e.location.serviceRadius', description: 'Service radius in km' },
];
