import type { MetricDef } from '@seesby/types';

export const CONV_METRICS: MetricDef[] = [
  // ── EX-F: Analytics / Conversion Expansion (behavioral buckets) ──
  {
    key: 'p.conv.rageClicks.bucket',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.conv.rageClicks.bucket.label',
    description: 'Rage click severity bucket (none, low, medium, high).',
  },
  {
    key: 'p.conv.rageClicks.trend',
    namespace: 'p.conv',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T2'],
    format: 'json',
    i18nLabelKey: 'metric.p.conv.rageClicks.trend.label',
    description: 'Rage click trend time-series.',
  },
  {
    key: 'p.conv.deadClicks.bucket',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.conv.deadClicks.bucket.label',
    description: 'Dead click severity bucket (none, low, medium, high).',
  },
  {
    key: 'p.conv.errorClicks.bucket',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.conv.errorClicks.bucket.label',
    description: 'Error click severity bucket (none, low, medium, high).',
  },
  {
    key: 'p.conv.uTurns.bucket',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.conv.uTurns.bucket.label',
    description: 'U-turn severity bucket (none, low, medium, high).',
  },
  {
    key: 'p.conv.scrollDead.bucket',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.conv.scrollDead.bucket.label',
    description: 'Scroll dead zone severity bucket (none, low, medium, high).',
  },
  {
    key: 'p.conv.frictionScore',
    namespace: 'p.conv',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'A'],
    sources: ['T7'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.conv.frictionScore.label',
    description: 'Composite friction score (rage + dead + error + u-turns).',
  },
];
