import type { MetricDef } from '@seesby/types';

export const COMMERCE_METRICS: MetricDef[] = [
	{
		key: 'p.commerce.isProduct',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'L', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.isProduct.label',
		description: 'Whether this page is a product page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.commerce.isCategory',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.isCategory.label',
		description: 'Whether this page is a category/listing page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.sku',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0', 'T6'],
		format: 'text',
		i18nLabelKey: 'metric.p.commerce.sku.label',
		description: 'Product SKU identifier.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.price',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T0', 'T6'],
		format: 'money',
		i18nLabelKey: 'metric.p.commerce.price.label',
		description: 'Current selling price of the product.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.commerce.priceSchema',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.priceSchema.label',
		description: 'Whether price is present in structured data schema.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.currency',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0', 'T6'],
		format: 'text',
		i18nLabelKey: 'metric.p.commerce.currency.label',
		description: 'Currency code for the product price.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.priceHistory',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V', 'T', 'B'],
		sources: ['T0', 'T6'],
		format: 'list',
		i18nLabelKey: 'metric.p.commerce.priceHistory.label',
		description: 'Historical price data points for the product.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.compareAtPrice',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'money',
		i18nLabelKey: 'metric.p.commerce.compareAtPrice.label',
		description: 'Original/compare-at price before discount.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.discountPct',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T0', 'T6'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.discountPct.label',
		description: 'Discount percentage from compare-at price.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.availability',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'L', 'V', 'A', 'E'],
		sources: ['T0', 'T6'],
		format: 'enum',
		i18nLabelKey: 'metric.p.commerce.availability.label',
		description: 'Product availability status (in_stock, oos, backorder, preorder).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.commerce.oosDuration',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A', 'E'],
		sources: ['T0', 'T6', 'T8'],
		format: 'duration',
		i18nLabelKey: 'metric.p.commerce.oosDuration.label',
		description: 'How long the product has been out of stock.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.variantCount',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.variantCount.label',
		description: 'Number of product variants (size, color, etc.).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviewsCount',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V', 'S', 'A'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.reviewsCount.label',
		description: 'Total number of reviews for this product.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
		defaultVisible: true,
	},
	{
		key: 'p.commerce.reviewsAvg',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V', 'K', 'S'],
		sources: ['T0', 'T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.commerce.reviewsAvg.label',
		description: 'Average review rating score.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviewsSchemaOk',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.reviewsSchemaOk.label',
		description: 'Whether review schema markup is correctly implemented.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.faqPresent',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.faqPresent.label',
		description: 'Whether FAQ section is present on the product page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.sizeGuidePresent',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.sizeGuidePresent.label',
		description: 'Whether a size guide is present on the product page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.shippingInfo',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.shippingInfo.label',
		description: 'Whether shipping information is present on the product page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.returnsInfo',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.returnsInfo.label',
		description: 'Whether return policy information is present on the product page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.productVideo',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.productVideo.label',
		description: 'Whether a product video is embedded on the page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.imagesPerProduct',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.imagesPerProduct.label',
		description: 'Number of product images on the page.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.altImageCoverage',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.altImageCoverage.label',
		description: 'Percentage of product images with alt text.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.breadcrumbValid',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.breadcrumbValid.label',
		description: 'Whether breadcrumb navigation is valid and matches schema.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.inCategory',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['L', 'X'],
		sources: ['T0', 'T6'],
		format: 'text',
		i18nLabelKey: 'metric.p.commerce.inCategory.label',
		description: 'Category this product belongs to.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.crossSellPresent',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.crossSellPresent.label',
		description: 'Whether cross-sell recommendations are present.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.upsellPresent',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I'],
		sources: ['T0', 'T6'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.upsellPresent.label',
		description: 'Whether upsell recommendations are present.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.addToCartRate',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T0', 'T6', 'T7'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.addToCartRate.label',
		description: 'Add-to-cart conversion rate.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.commerce.checkoutRate',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T0', 'T6', 'T7'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.checkoutRate.label',
		description: 'Checkout initiation rate.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.commerce.abandonRate',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'E'],
		sources: ['T0', 'T6', 'T7'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.abandonRate.label',
		description: 'Cart abandonment rate.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'], requireConnected: ['ga4'] },
	},
	{
		key: 'p.commerce.searchOnSiteRank',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T6', 'T7'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.searchOnSiteRank.label',
		description: 'Internal search ranking position for this product.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.feedPresent',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'R', 'A'],
		sources: ['T6', 'T8'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.feedPresent.label',
		description: 'Whether the product appears in a shopping feed.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.feedErrors',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A', 'E'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.feedErrors.label',
		description: 'Number of feed errors for this product.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.feedAttrsMissing',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A', 'E'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.feedAttrsMissing.label',
		description: 'Number of required feed attributes missing.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.feedPriceMismatch',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A', 'E'],
		sources: ['T0', 'T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.feedPriceMismatch.label',
		description: 'Whether feed price matches page price.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.shoppingRanks',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T6', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.shoppingRanks.label',
		description: 'Google Shopping ranking position.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviewSchemaOk',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'boolean',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
		i18nLabelKey: 'metric.p.commerce.reviewSchemaOk',
		description: 'Whether review schema is correctly implemented on the product page.',
	},
	// ── EX-J: Commerce Expansion metrics ──
	{
		key: 'p.commerce.price.formatted',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T0'],
		format: 'text',
		i18nLabelKey: 'metric.p.commerce.price.formatted',
		description: 'Price as displayed on page (with currency symbol).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.price.schemaType',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'enum',
		i18nLabelKey: 'metric.p.commerce.price.schemaType',
		description: 'Schema price type (price, lowPrice, highPrice).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.price.normalized',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7'],
		format: 'money',
		i18nLabelKey: 'metric.p.commerce.price.normalized',
		description: 'Price normalized to USD for comparison.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.price.trend',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3', 'T5'],
		format: 'json',
		i18nLabelKey: 'metric.p.commerce.price.trend',
		description: 'Price history time-series.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.availability.lastOos',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'date',
		i18nLabelKey: 'metric.p.commerce.availability.lastOos',
		description: 'Last date product was out of stock.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.availability.oosFreq',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.availability.oosFreq',
		description: 'Number of OOS periods in last 90 days.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.count.bucket',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T7'],
		format: 'enum',
		i18nLabelKey: 'metric.p.commerce.reviews.count.bucket',
		description: 'Review count bucket: high (>100), medium (10-100), low (1-10), none (0).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.avg.bucket',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T7'],
		format: 'enum',
		i18nLabelKey: 'metric.p.commerce.reviews.avg.bucket',
		description: 'Review rating bucket: excellent (4.5-5), good (4.0-4.4), average (3.0-3.9), poor (<3.0).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.trend',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T3'],
		format: 'json',
		i18nLabelKey: 'metric.p.commerce.reviews.trend',
		description: 'Review count trend time-series.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.sentiment',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T6'],
		format: 'score',
		i18nLabelKey: 'metric.p.commerce.reviews.sentiment',
		description: 'Review sentiment score (-1 to 1).',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.topPositive',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T3'],
		format: 'list',
		i18nLabelKey: 'metric.p.commerce.reviews.topPositive',
		description: 'Top positive review snippets.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.reviews.topNegative',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'X'],
		sources: ['T3'],
		format: 'list',
		i18nLabelKey: 'metric.p.commerce.reviews.topNegative',
		description: 'Top negative review snippets.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.images.count',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'number',
		i18nLabelKey: 'metric.p.commerce.images.count',
		description: 'Number of product images.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.images.avgSize',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'bytes',
		i18nLabelKey: 'metric.p.commerce.images.avgSize',
		description: 'Average product image size.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.images.withAlt',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T0'],
		format: 'percent',
		i18nLabelKey: 'metric.p.commerce.images.withAlt',
		description: 'Product images with alt text.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.schema.productOk',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.schema.productOk',
		description: 'Whether Product schema is valid and complete.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.schema.offerOk',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.schema.offerOk',
		description: 'Whether Offer schema within Product is valid.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
	{
		key: 'p.commerce.schema.reviewOk',
		namespace: 'p.commerce',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.commerce.schema.reviewOk',
		description: 'Whether AggregateRating/Review schema is valid.',
		gate: { industries: ['ecommerce'], modes: ['commerce', 'fullAudit'] },
	},
];
