import type { MetricDef } from '@seesby/types';

export const UX_METRICS: MetricDef[] = [
  {
    key: 'p.ux.roleClassified',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'L', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.ux.roleClassified.label',
    description: 'Classified page role: entry, mid, conv, form, confirm, or utility.',
  },
  {
    key: 'p.ux.engagementRate',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'percent',
    scoreComponent: 'ux',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.engagementRate.label',
    description: 'User engagement rate for this page.',
  },
  {
    key: 'p.ux.engagementTime',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    format: 'duration',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.engagementTime.label',
    description: 'Average active engagement time on this page.',
  },
  {
    key: 'p.ux.bounceRate',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.bounceRate.label',
    description: 'Bounce rate for this page.',
  },
  {
    key: 'p.ux.scrollP50',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.scrollP50.label',
    description: 'Median scroll depth (50th percentile) on this page.',
  },
  {
    key: 'p.ux.scrollP90',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    format: 'percent',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.scrollP90.label',
    description: '90th percentile scroll depth on this page.',
  },
  {
    key: 'p.ux.rageClicks',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'L', 'V', 'A', 'E'],
    sources: ['T0', 'T1', 'T2'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.rageClicks.label',
    description: 'Number of rage click events detected on this page.',
  },
  {
    key: 'p.ux.deadClicks',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'L', 'A'],
    sources: ['T0', 'T1', 'T2'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.deadClicks.label',
    description: 'Number of dead click events (clicks on non-interactive elements) on this page.',
  },
  {
    key: 'p.ux.errorClicks',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T1', 'T2'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.errorClicks.label',
    description: 'Number of clicks that resulted in JavaScript errors on this page.',
  },
  {
    key: 'p.ux.uTurns',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T1', 'T2'],
    unit: 'count',
    format: 'number',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.uTurns.label',
    description: 'Number of U-turn navigation patterns detected on this page.',
  },
  {
    key: 'p.ux.scrollDead',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0', 'T1', 'T2'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.ux.scrollDead.label',
    description: 'Whether users scroll past content without interacting (dead scroll).',
  },
  {
    key: 'p.ux.messageMatchToAd',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'score',
    width: '70px',
    gate: { requireConnected: ['ga4'] },
    i18nLabelKey: 'metric.p.ux.messageMatchToAd.label',
    description: 'Score measuring alignment between ad copy and landing page content.',
  },
  {
    key: 'p.ux.messageMatchToSerp',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0', 'T1', 'T2', 'T3', 'T4', 'T5', 'T6'],
    format: 'score',
    width: '70px',
    i18nLabelKey: 'metric.p.ux.messageMatchToSerp.label',
    description: 'Score measuring alignment between SERP snippet and page content.',
  },
  {
    key: 'p.ux.conversionPaths',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'list',
    gate: { requireConnected: ['ga4'] },
    i18nLabelKey: 'metric.p.ux.conversionPaths.label',
    description: 'Top conversion paths leading through or from this page.',
  },
  {
    key: 'p.ux.heatmapPresent',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    format: 'boolean',
    width: '60px',
    i18nLabelKey: 'metric.p.ux.heatmapPresent.label',
    description: 'Whether a heatmap recording exists for this page.',
  },
  // ── EX-L: UX Expansion metrics ──
  {
    key: 'p.ux.scroll.depth.p25',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.scroll.depth.p25',
    description: '25th percentile scroll depth.',
  },
  {
    key: 'p.ux.scroll.depth.p50',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.scroll.depth.p50',
    description: 'Median scroll depth.',
  },
  {
    key: 'p.ux.scroll.depth.p75',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.scroll.depth.p75',
    description: '75th percentile scroll depth.',
  },
  {
    key: 'p.ux.scroll.depth.p90',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.scroll.depth.p90',
    description: '90th percentile scroll depth.',
  },
  {
    key: 'p.ux.scroll.depth.avg',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.scroll.depth.avg',
    description: 'Average scroll depth.',
  },
  {
    key: 'p.ux.scroll.deadZones',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T2'],
    format: 'list',
    i18nLabelKey: 'metric.p.ux.scroll.deadZones',
    description: 'Scroll dead zone areas (no engagement zones).',
  },
  {
    key: 'p.ux.timeOnPage.avg',
    namespace: 'p.ux',
    level: 'P',
    roles: ['G', 'I', 'V', 'A'],
    sources: ['T0'],
    format: 'duration',
    i18nLabelKey: 'metric.p.ux.timeOnPage.avg',
    description: 'Average time on page.',
  },
  {
    key: 'p.ux.timeOnPage.p50',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'duration',
    i18nLabelKey: 'metric.p.ux.timeOnPage.p50',
    description: 'Median time on page.',
  },
  {
    key: 'p.ux.timeOnPage.p90',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T0'],
    format: 'duration',
    i18nLabelKey: 'metric.p.ux.timeOnPage.p90',
    description: '90th percentile time on page.',
  },
  {
    key: 'p.ux.interactions.count',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T2'],
    format: 'number',
    i18nLabelKey: 'metric.p.ux.interactions.count',
    description: 'Total interaction events (clicks, scrolls, inputs).',
  },
  {
    key: 'p.ux.interactions.rageRate',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.interactions.rageRate',
    description: 'Rage click rate (rage clicks / total clicks).',
  },
  {
    key: 'p.ux.interactions.deadRate',
    namespace: 'p.ux',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T2'],
    format: 'percent',
    i18nLabelKey: 'metric.p.ux.interactions.deadRate',
    description: 'Dead click rate (dead clicks / total clicks).',
  },
];
