import type { MetricDef } from '@seesby/types';

export const TECH_METRICS: MetricDef[] = [
  {
    key: 'p.tech.perf.loadClass',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'R', 'L', 'V', 'S', 'A', 'E'],
    sources: ['T1', 'T5'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.loadClass',
    description: 'Page load speed classification: fast, ok, slow, or veryslow.',
  },
  {
    key: 'p.tech.perf.loadMs',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T1', 'T5'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.perf.loadMs',
    description: 'Total page load time in milliseconds.',
  },
  {
    key: 'p.tech.perf.ttfb',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'S'],
    sources: ['T1', 'T5'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.perf.ttfb',
    description: 'Time to First Byte.',
  },
  {
    key: 'p.tech.perf.sizeBytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.perf.sizeBytes',
    description: 'Total page size in bytes.',
    deprecated: true,
    fallbackKey: 'p.tech.perf.size.total',
  },
  {
    key: 'p.tech.perf.domNodes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.perf.domNodes',
    description: 'Number of DOM nodes in the rendered page.',
  },
  {
    key: 'p.tech.perf.resourceCount',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.perf.resourceCount',
    description: 'Total number of resources loaded by the page.',
    deprecated: true,
    fallbackKey: 'p.tech.perf.resources.total',
  },
  {
    key: 'p.tech.cwv.lcp',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'S', 'A'],
    sources: ['T1', 'T5'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.lcp',
    description: 'Largest Contentful Paint in seconds.',
  },
  {
    key: 'p.tech.cwv.inp',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'S', 'A'],
    sources: ['T1', 'T5'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.inp',
    description: 'Interaction to Next Paint.',
  },
  {
    key: 'p.tech.cwv.cls',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'S', 'A'],
    sources: ['T1', 'T5'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.cls',
    description: 'Cumulative Layout Shift score.',
  },
  {
    key: 'p.tech.cwv.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'R', 'L', 'V', 'S', 'A', 'E'],
    sources: ['T1', 'T5'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.cwv.bucket',
    description: 'Core Web Vitals pass/fail bucket: good, needs-improvement, or poor.',
    scoreComponent: 'tech',
    defaultVisible: true,
  },
  {
    key: 'p.tech.cwv.device',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L', 'V'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.cwv.device',
    description: 'Device type for CWV data: mobile or desktop.',
  },
  {
    key: 'p.tech.cwv.sampleSize',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I'],
    sources: ['T1'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.sampleSize',
    description: 'Number of Chrome UX Report sessions sampled.',
  },
  {
    key: 'p.tech.cwv.deltaMoM',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'A', 'E', 'T'],
    sources: ['T1'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.deltaMoM',
    description: 'Month-over-month change in CWV bucket.',
  },
  {
    key: 'p.tech.renderBlocking',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.renderBlocking',
    description: 'Number of render-blocking resources.',
    deprecated: true,
    fallbackKey: 'p.tech.renderBlocking.total',
  },
  {
    key: 'p.tech.thirdPartyScripts',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdPartyScripts',
    description: 'Number of third-party scripts loaded.',
    deprecated: true,
    fallbackKey: 'p.tech.thirdParty.scripts.count',
  },
  {
    key: 'p.tech.thirdPartyDomains',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdPartyDomains',
    description: 'Number of unique third-party domains contacted.',
    deprecated: true,
    fallbackKey: 'p.tech.thirdParty.domains.count',
  },
  {
    key: 'p.tech.jsRenderDep',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'R', 'L', 'A', 'S'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.jsRenderDep',
    description: 'Percentage of content dependent on JavaScript rendering.',
  },
  {
    key: 'p.tech.jsDiff.linksDelta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.jsDiff.linksDelta',
    description: 'Difference in link count between raw HTML and rendered DOM.',
  },
  {
    key: 'p.tech.jsDiff.imagesDelta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.jsDiff.imagesDelta',
    description: 'Difference in image count between raw HTML and rendered DOM.',
  },
  {
    key: 'p.tech.jsDiff.schemaDelta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.jsDiff.schemaDelta',
    description: 'Difference in schema objects between raw and rendered.',
  },
  {
    key: 'p.tech.jsDiff.wordDelta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.jsDiff.wordDelta',
    description: 'Difference in word count between raw HTML and rendered DOM.',
  },
  {
    key: 'p.tech.jsDiff.hydrationMismatch',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.jsDiff.hydrationMismatch',
    description: 'Whether server and client HTML differ significantly.',
  },
  {
    key: 'p.tech.mobileFriendly',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'L', 'A', 'S'],
    sources: ['T1', 'T5'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.mobileFriendly',
    description: 'Whether the page passes mobile-friendly test.',
  },
  {
    key: 'p.tech.sec.grade',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'R', 'S'],
    sources: ['T1', 'T5'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.sec.grade',
    description: 'Security grade: A through F.',
  },
  {
    key: 'p.tech.sec.hsts',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.hsts',
    description: 'Whether HSTS header is set.',
  },
  {
    key: 'p.tech.sec.csp',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.csp',
    description: 'Whether a Content Security Policy header is present.',
  },
  {
    key: 'p.tech.sec.mixedContent',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.mixedContent',
    description: 'Whether the page loads HTTP resources on HTTPS.',
  },
  {
    key: 'p.tech.sec.exposedKeys',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.exposedKeys',
    description: 'Number of exposed API keys found in page source.',
  },
  {
    key: 'p.tech.sec.exposedEmails',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.exposedEmails',
    description: 'Number of email addresses exposed in page source.',
  },
  {
    key: 'p.tech.sec.cookies',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'json',
    i18nLabelKey: 'metric.p.tech.sec.cookies',
    description: 'Cookie security flags summary.',
  },
  {
    key: 'p.tech.sec.sriMissing',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.sriMissing',
    description: 'Count of script/link tags missing SRI.',
  },
  {
    key: 'p.tech.sec.sslDays',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T1', 'T3'],
    unit: 'days',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.sslDays',
    description: 'Days until SSL certificate expires.',
  },
  {
    key: 'p.tech.sec.tlsVersion',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.tech.sec.tlsVersion',
    description: 'TLS version in use.',
  },
  {
    key: 'p.tech.sec.openRedirect',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.openRedirect',
    description: 'Whether open redirect vulnerability detected.',
  },
  {
    key: 'p.tech.sec.blacklist',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.blacklist',
    description: 'Whether domain is on any blacklist.',
  },
  {
    key: 'p.tech.a11y.score',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'R', 'V', 'S', 'A'],
    sources: ['T1', 'T5'],
    format: 'score',
    i18nLabelKey: 'metric.p.tech.a11y.score',
    description: 'Accessibility audit score (0-100).',
  },
  {
    key: 'p.tech.a11y.violations',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1', 'T5'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.violations',
    description: 'Number of accessibility violations found.',
  },
  {
    key: 'p.tech.a11y.contrast',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.contrast',
    description: 'Color contrast violations count.',
  },
  {
    key: 'p.tech.a11y.altMissing',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1', 'T5'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.altMissing',
    description: 'Number of images missing alt text.',
  },
  {
    key: 'p.tech.a11y.landmarks',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.landmarks',
    description: 'Whether ARIA landmarks are present.',
  },
  {
    key: 'p.tech.a11y.skipLink',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.skipLink',
    description: 'Whether a skip-to-content link exists.',
  },
  {
    key: 'p.tech.a11y.tapTargets',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.tapTargets',
    description: 'Tap target size violations count.',
  },
  {
    key: 'p.tech.a11y.fontMin',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.fontMin',
    description: 'Whether minimum font size is enforced.',
  },
  {
    key: 'p.tech.a11y.formLabels',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.formLabels',
    description: 'Form inputs missing labels count.',
  },
  {
    key: 'p.tech.a11y.aria',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.aria',
    description: 'ARIA attribute errors count.',
  },
  {
    key: 'p.tech.a11y.headingOrder',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.headingOrder',
    description: 'Whether heading levels are sequential.',
  },
  {
    key: 'p.tech.a11y.tablesHeaders',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.tablesHeaders',
    description: 'Whether tables have proper headers.',
  },
  {
    key: 'p.tech.a11y.viewportZoom',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.a11y.viewportZoom',
    description: 'Whether viewport allows user scaling.',
  },
  {
    key: 'p.tech.energy.carbonPerView',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R', 'V', 'S'],
    sources: ['T7'],
    unit: 'mg',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.energy.carbonPerView',
    description: 'Estimated carbon per page view.',
  },
  {
    key: 'p.tech.consent.mode',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.tech.consent.mode',
    description: 'Google Consent Mode version detected.',
  },
  {
    key: 'p.tech.cookieless',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.cookieless',
    description: 'Whether site operates without third-party cookies.',
  },
  {
    key: 'p.tech.coreUpdate.flag',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.coreUpdate.flag',
    description: 'Whether a Google core update overlaps with this page\'s trend.',
  },
  {
    key: 'p.tech.logFile.signals',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    format: 'text',
    i18nLabelKey: 'metric.p.tech.logFile.signals',
    description: 'Notable signals from server log file analysis.',
  },
  {
    key: 'p.tech.crawlBudget.spent',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.crawlBudget.spent',
    description: 'Estimated crawl budget consumed.',
  },
  {
    key: 'p.tech.crawlBudget.waste',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A', 'E'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.crawlBudget.waste',
    description: 'Percentage of crawl budget wasted on duplicates/errors.',
  },
  // ── EX-C: Technical Expansion ──
  {
    key: 'p.tech.perf.loadClassMobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.loadClassMobile',
    description: 'Performance classification for mobile',
  },
  {
    key: 'p.tech.perf.loadClassDesktop',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.loadClassDesktop',
    description: 'Performance classification for desktop',
  },
  {
    key: 'p.tech.perf.loadClassDelta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.loadClassDelta',
    description: 'Performance class change vs previous crawl',
  },
  {
    key: 'p.tech.perf.ttfb.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.ttfb.bucket',
    description: 'TTFB bucket for grid filtering',
  },
  {
    key: 'p.tech.perf.fcp.s',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'S', 'A'],
    sources: ['T1', 'T2'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.perf.fcp.s',
    description: 'First Contentful Paint (seconds, p75)',
  },
  {
    key: 'p.tech.perf.fcp.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.fcp.bucket',
    description: 'FCP bucket',
  },
  {
    key: 'p.tech.perf.sii',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T2'],
    format: 'score',
    i18nLabelKey: 'metric.p.tech.perf.sii',
    description: 'Speed Index score',
  },
  {
    key: 'p.tech.perf.tbt',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T2'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.perf.tbt',
    description: 'Total Blocking Time (ms)',
  },
  {
    key: 'p.tech.perf.lcp.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.lcp.bucket',
    description: 'LCP bucket for grid filtering',
  },
  {
    key: 'p.tech.perf.inp.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.inp.bucket',
    description: 'INP bucket for grid filtering',
  },
  {
    key: 'p.tech.perf.cls.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.perf.cls.bucket',
    description: 'CLS bucket for grid filtering',
  },
  {
    key: 'p.tech.cwv.lcp.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.bucket',
    description: 'LCP bucket',
  },
  {
    key: 'p.tech.cwv.inp.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.cwv.inp.bucket',
    description: 'INP bucket',
  },
  {
    key: 'p.tech.cwv.cls.bucket',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T1'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.cwv.cls.bucket',
    description: 'CLS bucket',
  },
  {
    key: 'p.tech.cwv.lcp.p50',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.p50',
    description: 'LCP 50th percentile',
  },
  {
    key: 'p.tech.cwv.lcp.p90',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.p90',
    description: 'LCP 90th percentile',
  },
  {
    key: 'p.tech.cwv.lcp.good',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.good',
    description: 'LCP good experiences percentage',
  },
  {
    key: 'p.tech.cwv.lcp.poor',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.poor',
    description: 'LCP poor experiences percentage',
  },
  {
    key: 'p.tech.cwv.inp.p50',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.inp.p50',
    description: 'INP 50th percentile',
  },
  {
    key: 'p.tech.cwv.inp.p90',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.inp.p90',
    description: 'INP 90th percentile',
  },
  {
    key: 'p.tech.cwv.inp.good',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.inp.good',
    description: 'INP good experiences percentage',
  },
  {
    key: 'p.tech.cwv.inp.poor',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.inp.poor',
    description: 'INP poor experiences percentage',
  },
  {
    key: 'p.tech.cwv.cls.p50',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.cls.p50',
    description: 'CLS 50th percentile',
  },
  {
    key: 'p.tech.cwv.cls.p90',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.cls.p90',
    description: 'CLS 90th percentile',
  },
  {
    key: 'p.tech.cwv.cls.good',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.cls.good',
    description: 'CLS good experiences percentage',
  },
  {
    key: 'p.tech.cwv.cls.poor',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T1'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.cwv.cls.poor',
    description: 'CLS poor experiences percentage',
  },
  {
    key: 'p.tech.cwv.lcp.delta7d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.delta7d',
    description: 'LCP delta vs 7 days ago',
  },
  {
    key: 'p.tech.cwv.lcp.delta28d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.delta28d',
    description: 'LCP delta vs 28 days ago',
  },
  {
    key: 'p.tech.cwv.inp.delta7d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.inp.delta7d',
    description: 'INP delta vs 7 days ago',
  },
  {
    key: 'p.tech.cwv.inp.delta28d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    unit: 'ms',
    format: 'duration',
    i18nLabelKey: 'metric.p.tech.cwv.inp.delta28d',
    description: 'INP delta vs 28 days ago',
  },
  {
    key: 'p.tech.cwv.cls.delta7d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.cls.delta7d',
    description: 'CLS delta vs 7 days ago',
  },
  {
    key: 'p.tech.cwv.cls.delta28d',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T1'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cwv.cls.delta28d',
    description: 'CLS delta vs 28 days ago',
  },
  {
    key: 'p.tech.cwv.lcp.trend',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T1'],
    format: 'json',
    i18nLabelKey: 'metric.p.tech.cwv.lcp.trend',
    description: 'LCP trend data (time-series for charts)',
  },
  {
    key: 'p.tech.cwv.inp.trend',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T1'],
    format: 'json',
    i18nLabelKey: 'metric.p.tech.cwv.inp.trend',
    description: 'INP trend data',
  },
  {
    key: 'p.tech.cwv.cls.trend',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T1'],
    format: 'json',
    i18nLabelKey: 'metric.p.tech.cwv.cls.trend',
    description: 'CLS trend data',
  },
  {
    key: 'p.tech.renderBlocking.css',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.renderBlocking.css',
    description: 'Render-blocking CSS resources',
  },
  {
    key: 'p.tech.renderBlocking.js',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.renderBlocking.js',
    description: 'Render-blocking JavaScript resources',
  },
  {
    key: 'p.tech.renderBlocking.total',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.renderBlocking.total',
    description: 'Total render-blocking resources',
  },
  {
    key: 'p.tech.renderBlocking.bytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.renderBlocking.bytes',
    description: 'Total size of render-blocking resources',
  },
  {
    key: 'p.tech.thirdParty.scripts.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdParty.scripts.count',
    description: 'Third-party script count',
  },
  {
    key: 'p.tech.thirdParty.scripts.bytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.thirdParty.scripts.bytes',
    description: 'Third-party script payload size',
  },
  {
    key: 'p.tech.thirdParty.domains.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdParty.domains.count',
    description: 'Unique third-party domain count',
  },
  {
    key: 'p.tech.thirdParty.domains.list',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.tech.thirdParty.domains.list',
    description: 'List of third-party domains loaded',
  },
  {
    key: 'p.tech.thirdParty.css.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdParty.css.count',
    description: 'Third-party CSS file count',
  },
  {
    key: 'p.tech.thirdParty.css.bytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.thirdParty.css.bytes',
    description: 'Third-party CSS payload size',
  },
  {
    key: 'p.tech.thirdParty.images.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdParty.images.count',
    description: 'Third-party image count',
  },
  {
    key: 'p.tech.thirdParty.images.bytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.thirdParty.images.bytes',
    description: 'Third-party image payload size',
  },
  {
    key: 'p.tech.thirdParty.fonts.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.thirdParty.fonts.count',
    description: 'Third-party font count',
  },
  {
    key: 'p.tech.thirdParty.fonts.bytes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.thirdParty.fonts.bytes',
    description: 'Third-party font payload size',
  },
  {
    key: 'p.tech.jsRenderDep.mobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.jsRenderDep.mobile',
    description: 'JS render dependency on mobile',
  },
  {
    key: 'p.tech.jsRenderDep.delta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.jsRenderDep.delta',
    description: 'JS render dependency change vs previous crawl',
  },
  {
    key: 'p.tech.sec.grade.mobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.sec.grade.mobile',
    description: 'Security grade on mobile',
  },
  {
    key: 'p.tech.sec.headers.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.headers.count',
    description: 'Count of security-related headers present',
  },
  {
    key: 'p.tech.sec.headers.missing',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.tech.sec.headers.missing',
    description: 'Missing security headers (HSTS, CSP, X-Frame-Options, etc.)',
  },
  {
    key: 'p.tech.sec.xFrameOptions',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.xFrameOptions',
    description: 'X-Frame-Options header present',
  },
  {
    key: 'p.tech.sec.xContentTypeOptions',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.xContentTypeOptions',
    description: 'X-Content-Type-Options header present',
  },
  {
    key: 'p.tech.sec.referrerPolicy',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.referrerPolicy',
    description: 'Referrer-Policy header present',
  },
  {
    key: 'p.tech.sec.permissionsPolicy',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.permissionsPolicy',
    description: 'Permissions-Policy header present',
  },
  {
    key: 'p.tech.sec.hsts.maxAge',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.hsts.maxAge',
    description: 'HSTS max-age directive value',
  },
  {
    key: 'p.tech.sec.hsts.includeSubDomains',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.hsts.includeSubDomains',
    description: 'HSTS includeSubDomains directive',
  },
  {
    key: 'p.tech.sec.hsts.preload',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.hsts.preload',
    description: 'HSTS preload directive',
  },
  {
    key: 'p.tech.sec.csp.directiveCount',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.csp.directiveCount',
    description: 'Number of CSP directives',
  },
  {
    key: 'p.tech.sec.csp.reportOnly',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.csp.reportOnly',
    description: 'Whether CSP is in report-only mode',
  },
  {
    key: 'p.tech.sec.cookies.total',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.cookies.total',
    description: 'Total cookie count',
  },
  {
    key: 'p.tech.sec.cookies.insecure',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.cookies.insecure',
    description: 'Insecure cookies (not Secure flag on HTTPS)',
  },
  {
    key: 'p.tech.sec.cookies.sameSite',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.cookies.sameSite',
    description: 'Cookies with SameSite attribute',
  },
  {
    key: 'p.tech.sec.cookies.httpOnly',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.cookies.httpOnly',
    description: 'Cookies with HttpOnly flag',
  },
  {
    key: 'p.tech.sec.cookies.thirdParty',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.sec.cookies.thirdParty',
    description: 'Third-party cookies detected',
  },
  {
    key: 'p.tech.sec.ssl.issuer',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T1'],
    format: 'text',
    i18nLabelKey: 'metric.p.tech.sec.ssl.issuer',
    description: 'SSL certificate issuer',
  },
  {
    key: 'p.tech.sec.ssl.subject',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T1'],
    format: 'text',
    i18nLabelKey: 'metric.p.tech.sec.ssl.subject',
    description: 'SSL certificate subject',
  },
  {
    key: 'p.tech.sec.ssl.wildcard',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.ssl.wildcard',
    description: 'Whether SSL cert is wildcard',
  },
  {
    key: 'p.tech.sec.ssl.selfSigned',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T1'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.sec.ssl.selfSigned',
    description: 'Whether SSL cert is self-signed',
  },
  {
    key: 'p.tech.sec.mixedContent.types',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'list',
    i18nLabelKey: 'metric.p.tech.sec.mixedContent.types',
    description: 'Types of mixed content (image, script, iframe, etc.)',
  },
  {
    key: 'p.tech.a11y.score.mobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'L'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.tech.a11y.score.mobile',
    description: 'Accessibility score on mobile viewport',
  },
  {
    key: 'p.tech.a11y.score.delta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.score.delta',
    description: 'Accessibility score change vs previous crawl',
  },
  {
    key: 'p.tech.a11y.violations.critical',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'E'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.violations.critical',
    description: 'Critical accessibility violations',
  },
  {
    key: 'p.tech.a11y.violations.serious',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.violations.serious',
    description: 'Serious accessibility violations',
  },
  {
    key: 'p.tech.a11y.violations.moderate',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.violations.moderate',
    description: 'Moderate accessibility violations',
  },
  {
    key: 'p.tech.a11y.violations.minor',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.violations.minor',
    description: 'Minor accessibility violations',
  },
  {
    key: 'p.tech.a11y.violations.types',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'list',
    i18nLabelKey: 'metric.p.tech.a11y.violations.types',
    description: 'Unique violation rule IDs triggered',
  },
  {
    key: 'p.tech.a11y.passes',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.passes',
    description: 'Number of axe rules passed',
  },
  {
    key: 'p.tech.a11y.incomplete',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.incomplete',
    description: 'Number of axe rules needing manual review',
  },
  {
    key: 'p.tech.a11y.inapplicable',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.a11y.inapplicable',
    description: 'Number of axe rules not applicable',
  },
  {
    key: 'p.tech.energy.carbonPerViewMobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V'],
    sources: ['T7'],
    unit: 'mg',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.energy.carbonPerViewMobile',
    description: 'Carbon per view for mobile rendering',
  },
  {
    key: 'p.tech.energy.rating',
    namespace: 'p.tech',
    level: 'P',
    roles: ['G', 'L'],
    sources: ['T7'],
    format: 'enum',
    i18nLabelKey: 'metric.p.tech.energy.rating',
    description: 'Carbon efficiency grade',
  },
  {
    key: 'p.tech.energy.transferSize',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    unit: 'bytes',
    format: 'bytes',
    i18nLabelKey: 'metric.p.tech.energy.transferSize',
    description: 'Total page transfer size (all resources)',
  },
  {
    key: 'p.tech.energy.requests',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T0'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.energy.requests',
    description: 'Total HTTP requests',
  },
  {
    key: 'p.tech.crawlBudget.wasted_pct',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'percent',
    i18nLabelKey: 'metric.p.tech.crawlBudget.wasted_pct',
    description: 'Percentage of crawl budget wasted (duplicates, params, 404s)',
  },
  {
    key: 'p.tech.crawlBudget.googlebotHits',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.crawlBudget.googlebotHits',
    description: 'Googlebot crawl hits in last 30 days.',
  },
  {
    key: 'p.tech.crawlBudget.lastCrawl',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.p.tech.crawlBudget.lastCrawl',
    description: 'Last date Googlebot crawled this page.',
  },
  {
    key: 'p.tech.crawlBudget.crawlFrequency',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.crawlBudget.crawlFrequency',
    description: 'Average Googlebot visits per week.',
  },
  {
    key: 'p.tech.crawlBudget.vsTraffic',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'score',
    i18nLabelKey: 'metric.p.tech.crawlBudget.vsTraffic',
    description: 'Crawl budget efficiency vs traffic value.',
  },
  {
    key: 'p.tech.coreUpdate.impact.lcp',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.coreUpdate.impact.lcp',
    description: 'LCP change during core update period.',
  },
  {
    key: 'p.tech.coreUpdate.impact.content',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.coreUpdate.impact.content',
    description: 'Content-related ranking impact during update.',
  },
  {
    key: 'p.tech.coreUpdate.impact.links',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'V', 'T'],
    sources: ['T7'],
    format: 'number',
    i18nLabelKey: 'metric.p.tech.coreUpdate.impact.links',
    description: 'Link-related ranking impact during update.',
  },
  {
    key: 'p.tech.consent.modeDetected',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R'],
    sources: ['T2'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.consent.modeDetected',
    description: 'Whether consent mode is detected.',
  },
  {
    key: 'p.tech.consent.gdprCompliant',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R', 'A'],
    sources: ['T2'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.consent.gdprCompliant',
    description: 'Whether GDPR consent flow appears compliant.',
  },
  {
    key: 'p.tech.cookieless.trackers',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T2'],
    format: 'list',
    i18nLabelKey: 'metric.p.tech.cookieless.trackers',
    description: 'Cookieless tracking technologies detected.',
  },
  {
    key: 'p.tech.cookieless.count',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'R'],
    sources: ['T2'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.cookieless.count',
    description: 'Count of cookieless tracking methods.',
  },
  {
    key: 'p.tech.domNodes.mobile',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T0'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.domNodes.mobile',
    description: 'DOM node count on mobile.',
  },
  {
    key: 'p.tech.domNodes.delta',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A', 'T'],
    sources: ['T7'],
    unit: 'count',
    format: 'number',
    i18nLabelKey: 'metric.p.tech.domNodes.delta',
    description: 'DOM node count change vs previous crawl.',
  },
  {
    key: 'p.tech.httpVersion.isModern',
    namespace: 'p.tech',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T7'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.tech.httpVersion.isModern',
    description: 'Whether using HTTP/2 or HTTP/3 (modern).',
  },
  // ── EX-Q.5: More Per-Metric Detail ──
  { key: 'p.tech.perf.resources.total', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.total', description: 'Total resource requests' },
  { key: 'p.tech.perf.resources.js', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.js', description: 'JavaScript resource count' },
  { key: 'p.tech.perf.resources.css', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.css', description: 'CSS resource count' },
  { key: 'p.tech.perf.resources.img', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.img', description: 'Image resource count' },
  { key: 'p.tech.perf.resources.font', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.font', description: 'Font resource count' },
  { key: 'p.tech.perf.resources.other', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.other', description: 'Other resource count' },
  { key: 'p.tech.perf.size.js', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.js', description: 'JavaScript payload size' },
  { key: 'p.tech.perf.size.css', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.css', description: 'CSS payload size' },
  { key: 'p.tech.perf.size.img', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.img', description: 'Image payload size' },
  { key: 'p.tech.perf.size.font', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.font', description: 'Font payload size' },
  { key: 'p.tech.perf.size.html', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.html', description: 'HTML document size' },
  { key: 'p.tech.perf.size.total', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.total', description: 'Total page weight' },
  { key: 'p.tech.perf.size.totalCompressed', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.size.totalCompressed', description: 'Total compressed page weight' },
  { key: 'p.tech.sec.headers.all', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.p.tech.sec.headers.all', description: 'All response headers (full list)' },
  { key: 'p.tech.sec.headers.security', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], format: 'json', i18nLabelKey: 'metric.p.tech.sec.headers.security', description: 'Security-specific headers only' },
  // ── EX-Q.6: Additional Detail Metrics ──
  { key: 'p.tech.perf.resources.jsCount', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.jsCount', description: 'JavaScript file count' },
  { key: 'p.tech.perf.resources.cssCount', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.cssCount', description: 'CSS file count' },
  { key: 'p.tech.perf.resources.imgCount', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.imgCount', description: 'Image resource count' },
  { key: 'p.tech.perf.resources.fontCount', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.fontCount', description: 'Font file count' },
  { key: 'p.tech.perf.resources.xhrCount', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.xhrCount', description: 'XHR/fetch request count' },
  { key: 'p.tech.perf.resources.totalSize', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.resources.totalSize', description: 'Total resource payload size' },
  { key: 'p.tech.perf.resources.jsSize', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.resources.jsSize', description: 'JavaScript payload size' },
  { key: 'p.tech.perf.resources.cssSize', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.resources.cssSize', description: 'CSS payload size' },
  { key: 'p.tech.perf.resources.imgSize', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'bytes', i18nLabelKey: 'metric.p.tech.perf.resources.imgSize', description: 'Image payload size' },
  { key: 'p.tech.perf.resources.totalRequests', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'count', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.totalRequests', description: 'Total HTTP requests' },
  { key: 'p.tech.perf.resources.totalSizeKb', namespace: 'p.tech', level: 'P', roles: ['I', 'X'], sources: ['T0'], unit: 'bytes', format: 'number', i18nLabelKey: 'metric.p.tech.perf.resources.totalSizeKb', description: 'Total page weight in KB' },
  // ── EX-Q.6: Comparison Metrics ──
  { key: 'p.tech.cwv.lcp.vsPrev30d', namespace: 'p.tech', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'duration', i18nLabelKey: 'metric.p.tech.cwv.lcp.vsPrev30d', description: 'LCP change vs previous 30d measurement' },
  { key: 'p.tech.cwv.inp.vsPrev30d', namespace: 'p.tech', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'duration', i18nLabelKey: 'metric.p.tech.cwv.inp.vsPrev30d', description: 'INP change vs previous 30d measurement' },
  { key: 'p.tech.cwv.cls.vsPrev30d', namespace: 'p.tech', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.tech.cwv.cls.vsPrev30d', description: 'CLS change vs previous 30d measurement' },
];
