import type { MetricDef } from '@seesby/types';

export const backgroundMetrics: MetricDef[] = [
  {
    key: 'b.backlinks.refresh',
    namespace: 'b.backlinks',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T3', 'T4'],
    format: 'date',
    i18nLabelKey: 'metric.b.backlinks.refresh',
    description: 'Last backlink profile refresh timestamp.',
  },
  {
    key: 'b.wayback.age',
    namespace: 'b.wayback',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'duration',
    i18nLabelKey: 'metric.b.wayback.age',
    description: 'Oldest Wayback Machine snapshot age.',
  },
  {
    key: 'b.whois.age',
    namespace: 'b.whois',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'duration',
    i18nLabelKey: 'metric.b.whois.age',
    description: 'Domain registration age from WHOIS data.',
  },
  {
    key: 'b.bing.wmt',
    namespace: 'b.bing',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.bing.wmt',
    description: 'Last Bing Webmaster Tools data refresh.',
  },
  {
    key: 'b.gsc.daily',
    namespace: 'b.gsc',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.gsc.daily',
    description: 'Last Google Search Console daily import.',
  },
  {
    key: 'b.ga4.daily',
    namespace: 'b.ga4',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.ga4.daily',
    description: 'Last Google Analytics 4 daily import.',
  },
  {
    key: 'b.crux.monthly',
    namespace: 'b.crux',
    level: 'B',
    roles: ['B'],
    sources: ['T1'],
    format: 'date',
    i18nLabelKey: 'metric.b.crux.monthly',
    description: 'Last Chrome UX Report monthly dataset ingested.',
  },
  {
    key: 'b.serp.scrape',
    namespace: 'b.serp',
    level: 'B',
    roles: ['B'],
    sources: ['T5'],
    format: 'date',
    i18nLabelKey: 'metric.b.serp.scrape',
    description: 'Last SERP scrape run timestamp.',
  },
  {
    key: 'b.ai.harness',
    namespace: 'b.ai',
    level: 'B',
    roles: ['B'],
    sources: ['T6'],
    format: 'date',
    i18nLabelKey: 'metric.b.ai.harness',
    description: 'Last AI analysis harness run timestamp.',
  },
  {
    key: 'b.social.mentions',
    namespace: 'b.social',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T5'],
    format: 'date',
    i18nLabelKey: 'metric.b.social.mentions',
    description: 'Last social mentions crawl timestamp.',
  },
  {
    key: 'b.social.followers',
    namespace: 'b.social',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T3'],
    format: 'date',
    i18nLabelKey: 'metric.b.social.followers',
    description: 'Last social followers count update.',
  },
  {
    key: 'b.news.coverage',
    namespace: 'b.news',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T6'],
    format: 'date',
    i18nLabelKey: 'metric.b.news.coverage',
    description: 'Last news coverage crawl timestamp.',
  },
  {
    key: 'b.podcast.mentions',
    namespace: 'b.podcast',
    level: 'B',
    roles: ['B'],
    sources: ['T3', 'T5'],
    format: 'date',
    i18nLabelKey: 'metric.b.podcast.mentions',
    description: 'Last podcast mentions crawl timestamp.',
  },
  {
    key: 'b.youtube.transcripts',
    namespace: 'b.youtube',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T5'],
    format: 'date',
    i18nLabelKey: 'metric.b.youtube.transcripts',
    description: 'Last YouTube transcript ingestion timestamp.',
  },
  {
    key: 'b.commerce.prices',
    namespace: 'b.commerce',
    level: 'B',
    roles: ['B'],
    sources: ['T3', 'T5'],
    format: 'date',
    i18nLabelKey: 'metric.b.commerce.prices',
    description: 'Last commerce price monitoring update.',
  },
  {
    key: 'b.brand.reviews',
    namespace: 'b.brand',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T3'],
    format: 'date',
    i18nLabelKey: 'metric.b.brand.reviews',
    description: 'Last brand review aggregation timestamp.',
  },
  {
    key: 'b.blacklist',
    namespace: 'b.blacklist',
    level: 'B',
    roles: ['B'],
    sources: ['T1', 'T3'],
    format: 'date',
    i18nLabelKey: 'metric.b.blacklist',
    description: 'Last blacklist check timestamp.',
  },
  {
    key: 'b.core.update.events',
    namespace: 'b.core.update',
    level: 'B',
    roles: ['B'],
    sources: ['T1'],
    format: 'date',
    i18nLabelKey: 'metric.b.core.update.events',
    description: 'Last core algorithm update detection timestamp.',
  },
  {
    key: 'b.logfile.ingest',
    namespace: 'b.logfile',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.logfile.ingest',
    description: 'Last server log file ingestion timestamp.',
  },
  {
    key: 'b.shopping.feed',
    namespace: 'b.shopping',
    level: 'B',
    roles: ['B'],
    sources: ['T0', 'T3'],
    format: 'date',
    i18nLabelKey: 'metric.b.shopping.feed',
    description: 'Last shopping feed sync timestamp.',
  },
  {
    key: 'b.internal.search.ingest',
    namespace: 'b.internal.search',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.internal.search.ingest',
    description: 'Last internal search log ingestion timestamp.',
  },
  {
    key: 'b.gbp.sync',
    namespace: 'b.gbp',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'date',
    i18nLabelKey: 'metric.b.gbp.sync',
    description: 'Last GBP listing sync timestamp.',
  },
  {
    key: 'b.ad.library.scan',
    namespace: 'b.ad.library',
    level: 'B',
    roles: ['B'],
    sources: ['T3'],
    format: 'date',
    i18nLabelKey: 'metric.b.ad.library.scan',
    description: 'Last ad library scan timestamp.',
  },

  // ─── EX-N: Background Expansion (non-duplicate entries only) ────
  {
    key: 'b.blacklist.status',
    namespace: 'b.blacklist',
    level: 'B',
    roles: ['B'],
    sources: ['T1', 'T3'],
    format: 'enum',
    i18nLabelKey: 'metric.b.blacklist.status',
    description: 'Current blacklist status',
  },
  {
    key: 'b.logfile.coverage',
    namespace: 'b.logfile',
    level: 'B',
    roles: ['B'],
    sources: ['T0'],
    format: 'percent',
    i18nLabelKey: 'metric.b.logfile.coverage',
    description: 'Percentage of pages with log data',
  },
];
