import type { MetricDef } from '@seesby/types';

export const ACTIONS_METRICS: MetricDef[] = [
  {
    key: 'p.actions.primary',
    namespace: 'p.actions',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.actions.primary.label',
    description: 'Primary recommended action for this page.',
  },
  {
    key: 'p.actions.content',
    namespace: 'p.actions',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.actions.content.label',
    description: 'Content-specific recommended action.',
  },
  {
    key: 'p.actions.technical',
    namespace: 'p.actions',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.actions.technical.label',
    description: 'Technical recommended action.',
  },
  {
    key: 'p.actions.estimatedImpact',
    namespace: 'p.actions',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.actions.estimatedImpact.label',
    description: 'Estimated impact of the recommended action.',
  },
  {
    key: 'p.actions.priority',
    namespace: 'p.actions',
    level: 'P',
    roles: ['G', 'I', 'V', 'A', 'S'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.actions.priority.label',
    description: 'Priority level of the recommended action.',
  },

  // ─── EX-Q.3: Action Outcome Tracking (page-level) ─────────────────
  {
    key: 'p.action.triggered',
    namespace: 'p.action',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'boolean',
    i18nLabelKey: 'metric.p.action.triggered',
    description: 'Whether any action is triggered for this page.',
  },
  {
    key: 'p.action.count',
    namespace: 'p.action',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'number',
    unit: 'count',
    i18nLabelKey: 'metric.p.action.count',
    description: 'Number of actions triggered for this page.',
  },
  {
    key: 'p.action.topAction',
    namespace: 'p.action',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'text',
    i18nLabelKey: 'metric.p.action.topAction',
    description: 'Highest-scoring action code for this page.',
    defaultVisible: true,
  },
  {
    key: 'p.action.score',
    namespace: 'p.action',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'score',
    i18nLabelKey: 'metric.p.action.score',
    description: 'Top action score for this page.',
  },
  {
    key: 'p.action.band',
    namespace: 'p.action',
    level: 'P',
    roles: ['G', 'I', 'A'],
    sources: ['T6'],
    format: 'enum',
    i18nLabelKey: 'metric.p.action.band',
    description: 'Priority band of top action.',
  },
  {
    key: 'p.action.estimatedDelta',
    namespace: 'p.action',
    level: 'P',
    roles: ['I', 'A'],
    sources: ['T6'],
    format: 'number',
    i18nLabelKey: 'metric.p.action.estimatedDelta',
    description: 'Estimated delta from top action.',
  },
  {
    key: 'p.action.effortMinutes',
    namespace: 'p.action',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'number',
    unit: 'count',
    i18nLabelKey: 'metric.p.action.effortMinutes',
    description: 'Estimated effort minutes for top action.',
  },
  {
    key: 'p.action.allActions',
    namespace: 'p.action',
    level: 'P',
    roles: ['I', 'X'],
    sources: ['T6'],
    format: 'list',
    i18nLabelKey: 'metric.p.action.allActions',
    description: 'All triggered actions for this page.',
  },
];
