import type { MetricDef } from '@seesby/types';

export const GA_METRICS: MetricDef[] = [
	{
		key: 'p.ga.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.sessions.label',
		description: 'Total sessions for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.users',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.users.label',
		description: 'Number of unique users for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.views',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.views.label',
		description: 'Total pageviews for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.engagementRate',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'S'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.engagementRate.label',
		description: 'GA4 engagement rate (non-bounce sessions).',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.engagementTime',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'duration',
		i18nLabelKey: 'metric.p.ga.engagementTime.label',
		description: 'Average engagement time per session.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.bounce',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.bounce.label',
		description: 'Bounce rate for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.scrollP50',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.scrollP50.label',
		description: 'Median scroll depth percentage.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.scrollP90',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.scrollP90.label',
		description: '90th percentile scroll depth percentage.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.conversions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.conversions.label',
		description: 'Total conversions for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.conversionRate',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.conversionRate.label',
		description: 'Conversion rate for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.revenue',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A', 'T'],
		sources: ['T7', 'T8'],
		format: 'money',
		i18nLabelKey: 'metric.p.ga.revenue.label',
		description: 'Total revenue attributed to this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.transactions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.transactions.label',
		description: 'Number of completed transactions.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.addToCart',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.addToCart.label',
		description: 'Number of add-to-cart events.',
		gate: { requireConnected: ['ga4'], industries: ['ecommerce'] },
	},
	{
		key: 'p.ga.checkouts',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.checkouts.label',
		description: 'Number of checkout initiation events.',
		gate: { requireConnected: ['ga4'], industries: ['ecommerce'] },
	},
	{
		key: 'p.ga.goalCompletions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.goalCompletions.label',
		description: 'Number of goal completions for this page.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.sessionsDelta',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'E', 'T'],
		sources: ['T7', 'T8'],
		format: 'number',
		i18nLabelKey: 'metric.p.ga.sessionsDelta.label',
		description: 'Absolute change in sessions vs previous period.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.sessionsDeltaPct',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'A', 'E', 'T'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.sessionsDeltaPct.label',
		description: 'Percentage change in sessions vs previous period.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelOrganic',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelOrganic.label',
		description: 'Percentage of traffic from organic search.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelDirect',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelDirect.label',
		description: 'Percentage of traffic from direct visits.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelSocial',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelSocial.label',
		description: 'Percentage of traffic from social channels.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelPaid',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelPaid.label',
		description: 'Percentage of traffic from paid channels.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelEmail',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelEmail.label',
		description: 'Percentage of traffic from email.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.channelReferral',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'percent',
		i18nLabelKey: 'metric.p.ga.channelReferral.label',
		description: 'Percentage of traffic from referral sources.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.newVsReturn',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T7', 'T8'],
		format: 'text',
		i18nLabelKey: 'metric.p.ga.newVsReturn.label',
		description: 'Ratio of new vs returning visitors.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.revenuePerView',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'R', 'V', 'K', 'S', 'A'],
		sources: ['T7', 'T8'],
		format: 'money',
		i18nLabelKey: 'metric.p.ga.revenuePerView.label',
		description: 'Revenue per pageview.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.revenuePerSession',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'V', 'K'],
		sources: ['T7', 'T8'],
		format: 'money',
		i18nLabelKey: 'metric.p.ga.revenuePerSession.label',
		description: 'Revenue per session.',
		gate: { requireConnected: ['ga4'] },
	},
	{
		key: 'p.ga.isRevenueLosing',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'I', 'L', 'A', 'E'],
		sources: ['T7', 'T8'],
		format: 'boolean',
		i18nLabelKey: 'metric.p.ga.isRevenueLosing.label',
		description: 'Whether this page is losing revenue compared to previous period.',
		gate: { requireConnected: ['ga4'] },
	},

	// ── EX-F: Analytics / Conversion Expansion ──
	// ── Time-window sessions ──
	{
		key: 'p.ga.sessions7d',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'A', 'T'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.sessions7d.label',
		description: 'Sessions (7d).',
	},
	{
		key: 'p.ga.sessions90d',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.sessions90d.label',
		description: 'Sessions (90d).',
	},
	{
		key: 'p.ga.sessions365d',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.sessions365d.label',
		description: 'Sessions (365d).',
	},

	// ── Trend time-series ──
	{
		key: 'p.ga.sessionsTrend',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.sessionsTrend.label',
		description: 'Sessions trend time-series (weekly).',
	},
	{
		key: 'p.ga.conversionsTrend',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.conversionsTrend.label',
		description: 'Conversions trend time-series.',
	},
	{
		key: 'p.ga.revenueTrend',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.revenueTrend.label',
		description: 'Revenue trend time-series.',
	},

	// ── Device breakdowns ──
	{
		key: 'p.ga.device.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.device.sessions.label',
		description: 'Sessions by device (mobile/desktop/tablet).',
	},
	{
		key: 'p.ga.device.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.device.cvr.label',
		description: 'Conversion rate by device.',
	},
	{
		key: 'p.ga.device.revenue',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.device.revenue.label',
		description: 'Revenue by device.',
	},
	{
		key: 'p.ga.device.bounce',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.device.bounce.label',
		description: 'Bounce rate by device.',
	},

	// ── Country breakdowns ──
	{
		key: 'p.ga.country.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.country.sessions.label',
		description: 'Sessions by country (top 10).',
	},
	{
		key: 'p.ga.country.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.country.cvr.label',
		description: 'Conversion rate by country.',
	},
	{
		key: 'p.ga.country.revenue',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.country.revenue.label',
		description: 'Revenue by country.',
	},

	// ── Channel deep-dive ──
	{
		key: 'p.ga.channel.organic.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.organic.sessions.label',
		description: 'Organic sessions (28d).',
	},
	{
		key: 'p.ga.channel.organic.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.organic.cvr.label',
		description: 'Organic conversion rate.',
	},
	{
		key: 'p.ga.channel.organic.revenue',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'money',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.organic.revenue.label',
		description: 'Organic revenue.',
	},
	{
		key: 'p.ga.channel.paid.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.paid.sessions.label',
		description: 'Paid sessions (28d).',
	},
	{
		key: 'p.ga.channel.paid.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.paid.cvr.label',
		description: 'Paid conversion rate.',
	},
	{
		key: 'p.ga.channel.paid.revenue',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'money',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.paid.revenue.label',
		description: 'Paid revenue.',
	},
	{
		key: 'p.ga.channel.social.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.social.sessions.label',
		description: 'Social sessions (28d).',
	},
	{
		key: 'p.ga.channel.social.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.social.cvr.label',
		description: 'Social conversion rate.',
	},
	{
		key: 'p.ga.channel.email.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.email.sessions.label',
		description: 'Email sessions (28d).',
	},
	{
		key: 'p.ga.channel.email.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.email.cvr.label',
		description: 'Email conversion rate.',
	},
	{
		key: 'p.ga.channel.referral.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.referral.sessions.label',
		description: 'Referral sessions (28d).',
	},
	{
		key: 'p.ga.channel.referral.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.referral.cvr.label',
		description: 'Referral conversion rate.',
	},
	{
		key: 'p.ga.channel.direct.sessions',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.direct.sessions.label',
		description: 'Direct sessions (28d).',
	},
	{
		key: 'p.ga.channel.direct.cvr',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		format: 'percent',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.direct.cvr.label',
		description: 'Direct conversion rate.',
	},
	{
		key: 'p.ga.channel.organic.trend',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.organic.trend.label',
		description: 'Organic sessions trend.',
	},
	{
		key: 'p.ga.channel.paid.trend',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V', 'T'],
		sources: ['T0'],
		format: 'json',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.channel.paid.trend.label',
		description: 'Paid sessions trend.',
	},

	// ── Revenue bucketing & derived ──
	{
		key: 'p.ga.revenuePerView.bucket',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T7'],
		format: 'enum',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.revenuePerView.bucket.label',
		description: 'Revenue per view bucket (high, medium, low, none).',
	},
	{
		key: 'p.ga.isRevenueLosing.velocity',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'A', 'E'],
		sources: ['T7'],
		format: 'money',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.isRevenueLosing.velocity.label',
		description: 'Rate of revenue decline (per week).',
	},

	// ── Conversion rate bucketing ──
	{
		key: 'p.ga.conversionRate.bucket',
		namespace: 'p.ga',
		level: 'P',
		roles: ['G', 'L'],
		sources: ['T7'],
		format: 'enum',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.conversionRate.bucket.label',
		description: 'Conversion rate bucket (high: >5%, average: 1-5%, low: 0.5-1%, very-low: <0.5%).',
	},
	{
		key: 'p.ga.conversionRate.vsAvg',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'A'],
		sources: ['T7'],
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.conversionRate.vsAvg.label',
		description: 'Conversion rate vs site average (multiplier).',
	},

	// ── Funnel metrics ──
	{
		key: 'p.ga.funnel.entry',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.funnel.entry.label',
		description: 'Funnel entry count (users entering funnel here).',
	},
	{
		key: 'p.ga.funnel.exit',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.funnel.exit.label',
		description: 'Funnel exit count (users dropping off here).',
	},
	{
		key: 'p.ga.funnel.conversion',
		namespace: 'p.ga',
		level: 'P',
		roles: ['I', 'V'],
		sources: ['T0'],
		unit: 'count',
		format: 'number',
		width: '70px',
		gate: { requireConnected: ['ga4'] },
		i18nLabelKey: 'metric.p.ga.funnel.conversion.label',
		description: 'Funnel conversion count (users completing this step).',
	},
	// ── EX-Q.6: Comparison Metrics ──
	{ key: 'p.ga.sessions.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.ga.sessions.vsPrev7d', description: 'Sessions change vs previous 7d period' },
	{ key: 'p.ga.sessions.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.ga.sessions.vsPrev28d', description: 'Sessions change vs previous 28d period' },
	{ key: 'p.ga.conversions.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.ga.conversions.vsPrev7d', description: 'Conversions change vs previous 7d period' },
	{ key: 'p.ga.conversions.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'number', i18nLabelKey: 'metric.p.ga.conversions.vsPrev28d', description: 'Conversions change vs previous 28d period' },
	{ key: 'p.ga.revenue.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'money', i18nLabelKey: 'metric.p.ga.revenue.vsPrev7d', description: 'Revenue change vs previous 7d period' },
	{ key: 'p.ga.revenue.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'money', i18nLabelKey: 'metric.p.ga.revenue.vsPrev28d', description: 'Revenue change vs previous 28d period' },
	{ key: 'p.ga.cvr.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.cvr.vsPrev7d', description: 'CVR change vs previous 7d period' },
	{ key: 'p.ga.cvr.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.cvr.vsPrev28d', description: 'CVR change vs previous 28d period' },
	{ key: 'p.ga.bounce.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.bounce.vsPrev7d', description: 'Bounce rate change vs previous 7d' },
	{ key: 'p.ga.bounce.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.bounce.vsPrev28d', description: 'Bounce rate change vs previous 28d' },
	{ key: 'p.ga.engagementRate.vsPrev7d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.engagementRate.vsPrev7d', description: 'Engagement rate change vs previous 7d' },
	{ key: 'p.ga.engagementRate.vsPrev28d', namespace: 'p.ga', level: 'P', roles: ['I', 'A', 'T'], sources: ['T7'], format: 'percent', i18nLabelKey: 'metric.p.ga.engagementRate.vsPrev28d', description: 'Engagement rate change vs previous 28d' },
];
